Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2022-07, with the labels that each got.

#976 Issue 850 Configuration General params Thematic trimming (#967)
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  webapp/package.json
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/utils.ts
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/components/common/fieldEditors/SwitchFE.tsx
  webapp/src/hooks/useAutoUpdateRef.tsx
  webapp/src/services/api/study.ts
  webapp/src/theme.ts
Labels: size/XL

#977 Set default to zipped ouput import
  antarest/launcher/model.py
  antarest/launcher/service.py
  tests/launcher/test_service.py
  webapp/src/components/App/Studies/LauncherDialog.tsx
  webapp/src/services/api/study.ts
Labels: size/M

#970 Link styles in map
  antarest/study/business/link_management.py
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/utils.ts
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CandidateForm.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CreateCandidateDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/App/Studies/StudiesList/index.tsx
  webapp/src/services/api/studydata.ts
Labels: size/L

#915 Add task workers
  antarest/core/config.py
  antarest/core/interfaces/eventbus.py
  antarest/core/tasks/model.py
  antarest/core/tasks/service.py
  antarest/core/utils/utils.py
  antarest/eventbus/business/interfaces.py
  antarest/eventbus/business/local_eventbus.py
  antarest/eventbus/business/redis_eventbus.py
  antarest/eventbus/service.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/main.py
  antarest/worker/__init__.py
  antarest/worker/archive_worker.py
  antarest/worker/worker.py
  tests/conftest.py
  tests/core/test_tasks.py
  tests/core/test_utils.py
  tests/eventbus/test_local_eventbus.py
  tests/eventbus/test_redis_event_bus.py
  tests/eventbus/test_service.py
  tests/storage/conftest.py
  tests/worker/__init__.py
  tests/worker/test_worker.py
Labels: size/XL

#979 fix enr_modelling
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
Labels: size/XS

#980 Better job historing sorting
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/index.tsx
Labels: size/S

#986 Fix possible relaunch of an invalid xpansion study + Slurm loop
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
Labels: size/M

#989 Fix some styles
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/styles.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Load.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/MiscGen.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/PropertiesForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Reserve.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Solar.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Wind.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkMatrixView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/index.tsx
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/Fieldset.tsx
  webapp/src/components/common/FileTable.tsx
  webapp/src/components/common/MatrixInput/MatrixAssignDialog.tsx
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/MatrixInput/style.ts
Labels: size/XL

#994 Issue in Form component with formState proxy
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/wrappers/LoginWrapper.tsx
Labels: size/S

#995 Fix handle submit for unchanging values
  webapp/src/components/common/Form/utils.ts
Labels: size/S

#997 Add launcher load info
  antarest/core/config.py
  antarest/launcher/repository.py
  antarest/launcher/service.py
  antarest/launcher/web.py
  tests/conftest.py
  tests/launcher/test_repository.py
  tests/launcher/test_service.py
Labels: size/L

#998 Keep zip on output import
  antarest/study/common/studystorage.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/study_download_utils.py
  antarest/study/web/studies_blueprint.py
  tests/storage/business/test_raw_study_service.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/common/types.ts
Labels: size/M

#1001 Add enable info to cluster info
  antarest/study/business/area_management.py
  tests/storage/business/test_arealink_manager.py
Labels: size/XS

#1003 issue-850-Configuration_General_params_Thematic_trimming
  webapp/src/components/App/Settings/Groups/Header.tsx
  webapp/src/components/App/Settings/Groups/index.tsx
  webapp/src/components/App/Settings/Tokens/Header.tsx
  webapp/src/components/App/Settings/Tokens/index.tsx
  webapp/src/components/App/Settings/Users/Header.tsx
  webapp/src/components/App/Settings/Users/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
  webapp/src/components/App/Studies/HeaderBottom.tsx
  webapp/src/components/common/PropertiesView.tsx
  webapp/src/components/common/fieldEditors/SearchFE.tsx
  webapp/src/theme.ts
  webapp/src/utils/textUtils.ts
Labels: size/L

#1004 Add launcher tags
  webapp/src/common/types.ts
  webapp/src/components/App/Tasks/index.tsx
  webapp/src/services/api/study.ts
Labels: size/M

#958 implement cluster list
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/variant_study_service.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/Commands/Edition/commandTypes.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/preview.png
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/preview.png
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalMatrixView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/AddClusterDialog/AddClusterForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/AddClusterDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/ClusterView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/utils.ts
  webapp/src/components/App/Singlestudy/explore/TabWrapper.tsx
  webapp/src/components/common/FormGenerator/AutoSubmitGenerator.tsx
  webapp/src/components/common/FormGenerator/index.tsx
  webapp/src/components/common/fieldEditors/BooleanFE.tsx
  webapp/src/redux/selectors.ts
Labels: size/XXL

#999 issue 946 Add a launcher option
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/LauncherDialog.tsx
  webapp/src/components/App/Tasks/JobTableView.tsx
  webapp/src/components/common/LoadIndicator.tsx
  webapp/src/services/api/study.ts
Labels: size/L

#1007 Fix area position modification
  antarest/study/business/area_management.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  tests/integration/test_integration.py
  tests/storage/business/test_arealink_manager.py
Labels: size/M

#1009 Readd alt adequacy patch + auto unzip option
  antarest/launcher/model.py
  antarest/launcher/service.py
  antarest/study/service.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/LauncherDialog.tsx
  webapp/src/services/api/study.ts
Labels: size/L

#982 Issue 852 Configuration Time series management
  antarest/study/business/config_management.py
  tests/storage/business/test_config_manager.py
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/utils.ts
  webapp/src/components/App/Singlestudy/explore/TabWrapper.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/dialogs/FormDialog.tsx
  webapp/src/components/common/fieldEditors/CheckBoxFE.tsx
  webapp/src/components/common/fieldEditors/NumberFE.tsx
  webapp/src/hoc/reactHookFormSupport.tsx
  webapp/src/hooks/useDebouncedState.tsx
Labels: size/XL

#1011 Change antares web html page title when on specific study
  webapp/src/components/App/Data/index.tsx
  webapp/src/components/App/Singlestudy/index.tsx
  webapp/src/components/App/Tasks/index.tsx
  webapp/src/components/common/EditableMatrix/MatrixGraphView.tsx
Labels: size/S

#1012 Update React to v18.2.0
  webapp/.eslintrc.json
  webapp/package.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/index.tsx
  webapp/src/components/App/Studies/BatchModeMenu.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/MatrixInput/MatrixAssignDialog.tsx
  webapp/src/components/common/dialogs/BasicDialog.tsx
  webapp/src/components/common/page/RootPage.tsx
  webapp/src/index.tsx
Labels: size/M
