Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2022-06, with the labels that each got.

#932 Add folder info + enlarge card width + reduce card height
  webapp/src/components/studies/StudiesList/index.tsx
  webapp/src/components/studies/StudyCard.tsx
Labels: size/M

#924 add map/areas layout
  antarest/core/interfaces/eventbus.py
  antarest/study/service.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/App.tsx
  webapp/src/common/types.ts
  webapp/src/components/singlestudy/explore/Modelization/Areas/AreaPropsView.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/AreasTab.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Hydro/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Hydro/preview.png
  webapp/src/components/singlestudy/explore/Modelization/Areas/Load/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Load/preview.png
  webapp/src/components/singlestudy/explore/Modelization/Areas/MiscGen/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/MiscGen/preview.png
  webapp/src/components/singlestudy/explore/Modelization/Areas/Properties/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Properties/preview.png
  webapp/src/components/singlestudy/explore/Modelization/Areas/Reserve/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Reserve/preview.png
  webapp/src/components/singlestudy/explore/Modelization/Areas/Thermal/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Thermal/preview.png
  webapp/src/components/singlestudy/explore/Modelization/Areas/Wind/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Wind/preview.png
  webapp/src/components/singlestudy/explore/Modelization/Areas/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Map/MapPropsView.tsx
  webapp/src/components/singlestudy/explore/Modelization/Map/NodeListing.tsx
  webapp/src/components/singlestudy/explore/Modelization/Map/PanelView.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/CandidateListing.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/XpansionPropsView.tsx
  webapp/src/components/singlestudy/explore/common/ListElement.tsx
  webapp/src/components/singlestudy/explore/hooks/useStudyData.ts
  webapp/src/pages/SingleStudy/index.tsx
  webapp/src/redux/ducks/index.ts
  webapp/src/redux/ducks/studyDataSynthesis.ts
  webapp/src/redux/selectors.ts
  webapp/src/services/webSockets.ts
Labels: size/XL

#933 issue 849 Configuration General params
  webapp/.eslintrc.json
  webapp/src/components/common/Fieldset.tsx
  webapp/src/components/common/Form.tsx
  webapp/src/components/common/dialogs/FormDialog.tsx
  webapp/src/components/common/fieldEditors/CheckboxesTagsFE.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/components/common/loaders/BackdropLoading.tsx
  webapp/src/components/settings/Groups/dialog/CreateGroupDialog.tsx
  webapp/src/components/settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/settings/Groups/dialog/UpdateGroupDialog.tsx
  webapp/src/components/settings/Tokens/dialog/CreateTokenDialog.tsx
  webapp/src/components/settings/Tokens/dialog/TokenFormDialog/TokenForm.tsx
  webapp/src/components/settings/Users/dialog/CreateUserDialog.tsx
  webapp/src/components/settings/Users/dialog/UpdateUserDialog.tsx
  webapp/src/components/settings/Users/dialog/UserFormDialog/UserForm.tsx
  webapp/src/components/studies/FilterDrawer.tsx
  webapp/src/components/studies/MoveStudyDialog.tsx
Labels: size/L

#923 Add archive system for outputs
  antarest/core/utils/utils.py
  antarest/launcher/adapters/abstractlauncher.py
  antarest/launcher/adapters/local_launcher/local_launcher.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  antarest/launcher/web.py
  antarest/study/common/studystorage.py
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/helpers.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/study_download_utils.py
  antarest/study/storage/utils.py
  antarest/study/web/studies_blueprint.py
  examples/studies/STA-mini.zip
  tests/launcher/test_service.py
  tests/launcher/test_slurm_launcher.py
  tests/launcher/test_web.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/business/test_study_service_utils.py
  tests/storage/web/test_studies_bp.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/studies/LauncherDialog/index.tsx
  webapp/src/services/api/study.ts
Labels: size/XL

#935 Update Form component with auto submit feature
  webapp/src/components/common/Form.tsx
  webapp/src/components/common/dialogs/FormDialog.tsx
  webapp/src/components/settings/Groups/dialog/GroupFormDialog/index.tsx
  webapp/src/components/settings/Groups/dialog/UpdateGroupDialog.tsx
  webapp/src/components/settings/Tokens/dialog/TokenFormDialog/TokenForm.tsx
  webapp/src/components/settings/Users/dialog/UserFormDialog/index.tsx
  webapp/src/components/studies/MoveStudyDialog.tsx
Labels: size/L

#937 Add solver stats in db
  alembic/versions/26c50ef2a0e1_add_job_solver_stats.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  scripts/rollback.sh
  tests/launcher/test_service.py
  tests/storage/business/test_raw_study_service.py
Labels: size/L

#940 Fix a TS issue in Form component
  webapp/src/components/common/Form.tsx
Labels: size/S

#938 Auto unarchive zipped imported output
  antarest/study/service.py
Labels: size/S

#925 Issue 920 editable matrix view
  antarest/matrixstore/business/matrix_editor.py
  antarest/study/business/matrix_management.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/output_series_matrix.py
  antarest/study/storage/utils.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  tests/storage/business/test_study_service_utils.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/common/types.ts
  webapp/src/components/common/EditableMatrix/MatrixGraphView.tsx
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/EditableMatrix/style.css
  webapp/src/components/common/EditableMatrix/style.ts
  webapp/src/components/common/EditableMatrix/utils.test.ts
  webapp/src/components/common/EditableMatrix/utils.ts
  webapp/src/components/common/FileTable.tsx
  webapp/src/components/common/ImportForm.tsx
  webapp/src/components/common/MatrixView/index.tsx
  webapp/src/components/common/MatrixView/utils.ts
  webapp/src/components/common/dialogs/DataViewerDialog/index.tsx
  webapp/src/components/common/dialogs/ImportDialog.tsx
  webapp/src/components/data/MatrixDialog.tsx
  webapp/src/components/singlestudy/explore/Modelization/DebugView/StudyDataView/StudyFileView.tsx
  webapp/src/components/singlestudy/explore/Modelization/DebugView/StudyDataView/StudyMatrixView.tsx
  webapp/src/components/singlestudy/explore/Modelization/DebugView/StudyDataView/StudyMatrixView/StudyMatrixView.tsx
  webapp/src/components/singlestudy/explore/Modelization/DebugView/StudyDataView/StudyMatrixView/style.ts
  webapp/src/components/singlestudy/explore/Modelization/DebugView/StudyDataView/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/DebugView/StudyDataView/style.ts
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Capacities/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Files/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Settings/index.tsx
  webapp/src/components/studies/HeaderTopRight.tsx
  webapp/src/services/api/matrix.ts
Labels: size/XXL

#939 Add batch studies action (launch)
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/singlestudy/HomeView/InformationView/index.tsx
  webapp/src/components/singlestudy/NavHeader.tsx
  webapp/src/components/studies/BatchModeMenu.tsx
  webapp/src/components/studies/LauncherDialog.tsx
  webapp/src/components/studies/LauncherDialog/style.ts
  webapp/src/components/studies/StudiesList/StudyCardCell.tsx
  webapp/src/components/studies/StudiesList/index.tsx
  webapp/src/components/studies/StudyCard.tsx
Labels: size/L

#941 Matrix stats columns
  webapp/src/common/types.ts
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/EditableMatrix/utils.ts
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Load.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/MiscGen.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Reserve.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Solar.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Wind.tsx
Labels: size/L

#943 issue-849-Configuration_General_params
  webapp/src/components/common/Form.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/components/common/fieldEditors/SwitchFE.tsx
Labels: size/L

#942 Use construct in some pydantic model to skip costly validation
  antarest/matrixstore/service.py
  antarest/study/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/study_download_utils.py
  antarest/study/storage/utils.py
  antarest/study/web/raw_studies_blueprint.py
  tests/matrixstore/test_service.py
  tests/storage/integration/test_write_STA_mini.py
Labels: size/L

#947 Fixes : trad, variant cache bug, user config preservation on variant generation (xpansion)
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/variantstudy/model/test_variant_model.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/singlestudy/HomeView/InformationView/index.tsx
  webapp/src/components/studies/HeaderTopRight.tsx
  webapp/src/pages/Data.tsx
  webapp/src/pages/Tasks.tsx
Labels: size/L

#949 Add strict folder filter
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/studies/StudiesList/index.tsx
  webapp/src/pages/Studies/utils.ts
  webapp/src/redux/ducks/studies.ts
Labels: size/M

#951 Outputs summary view
  antarest/study/storage/abstract_storage_service.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/App.tsx
  webapp/src/components/singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/singlestudy/explore/Results/ResultDetails/preview.png
  webapp/src/components/singlestudy/explore/Results/index.tsx
Labels: size/L

#950 implement links
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/common/types.ts
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/components/singlestudy/explore/Configuration/General/Fields/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/AreaPropsView.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Links/LinkPropsView.tsx
  webapp/src/components/singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/singlestudy/explore/Modelization/Links/LinkView/LinkMatrixView.tsx
  webapp/src/components/singlestudy/explore/Modelization/Links/LinkView/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Links/LinkView/utils.ts
  webapp/src/components/singlestudy/explore/Modelization/Links/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Links/preview.png
  webapp/src/components/singlestudy/explore/common/ListElement.tsx
  webapp/src/redux/ducks/studyDataSynthesis.ts
  webapp/src/redux/selectors.ts
Labels: size/XL

#953 Fix trad
  webapp/public/locales/fr/main.json
Labels: size/XS

#954 Multiple fixes
  webapp/.eslintrc.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/SnackErrorMessage.tsx
  webapp/src/components/common/TagTextInput.tsx
  webapp/src/components/common/dialogs/DataViewerDialog/index.tsx
  webapp/src/components/common/fieldEditors/BooleanFE.tsx
  webapp/src/components/common/fieldEditors/ColorPickerFE/index.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/components/common/fieldEditors/SwitchFE.tsx
  webapp/src/components/data/DataListing.tsx
  webapp/src/components/data/DatasetCreationDialog.tsx
  webapp/src/components/settings/Tokens/index.tsx
  webapp/src/components/singlestudy/Commands/Edition/DraggableCommands/CommandListView.tsx
  webapp/src/components/singlestudy/explore/Configuration/General/Fields/index.tsx
  webapp/src/components/singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Areas/Properties/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/DebugView/StudyDataView/StudyMatrixView/StudyMatrixView.tsx
  webapp/src/components/singlestudy/explore/Modelization/Links/LinkView/index.tsx
  webapp/src/components/singlestudy/explore/Modelization/Map/LinksView.tsx
  webapp/src/components/singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/singlestudy/explore/Results/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/studies/LauncherDialog.tsx
  webapp/src/components/studies/StudiesList/StudyCardCell.tsx
  webapp/src/components/studies/StudiesList/index.tsx
  webapp/src/components/studies/StudyCard.tsx
  webapp/src/hooks/useDebounce.ts
  webapp/src/hooks/useDebouncedEffect.ts
  webapp/src/hooks/usePromise.ts
  webapp/src/hooks/usePromiseWithSnackbarError.ts
  webapp/src/pages/wrappers/LoginWrapper.tsx
  webapp/src/utils/reactUtils.ts
Labels: size/XL

#956 Add study config manager for thematic trimming
  antarest/study/business/config_management.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  tests/storage/business/test_config_manager.py
Labels: size/L

#959 Add commands apply for raw studies
  antarest/study/business/utils.py
  antarest/study/main.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/filestudytree.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/variant_blueprint.py
Labels: size/M

#962 Add link UI + add study listing search filters
  antarest/study/business/link_management.py
  antarest/study/service.py
  antarest/study/storage/utils.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/test_service.py
Labels: size/L

#967 Issue 850 Configuration General params Thematic trimming
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  webapp/package.json
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/utils.ts
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/components/common/fieldEditors/SwitchFE.tsx
  webapp/src/hooks/useAutoUpdateRef.tsx
  webapp/src/services/api/study.ts
  webapp/src/theme.ts
Labels: size/XL
