Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2022-10, with the labels that each got.

#1096 Refactor PropertiesDialog
  webapp/src/components/App/Singlestudy/NavHeader.tsx
  webapp/src/components/App/Singlestudy/PropertiesDialog/index.tsx
Labels: size/L

#1116 fix(storage): unformatted resolved matrix
  antarest/matrixstore/uri_resolver_service.py
  antarest/study/storage/rawstudy/model/filesystem/lazy_node.py
  antarest/study/web/watcher_blueprint.py
  tests/storage/business/test_url_resolver_service.py
  tests/storage/repository/filesystem/test_lazy_node.py
Labels: size/M

#1111 Add AdvancedParameters form
  antarest/study/business/advanced_parameters_management.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/utils.ts
Labels: size/XL

#1119 fix(study): update study state after changes
  webapp/src/components/App/Singlestudy/NavHeader.tsx
  webapp/src/components/App/Singlestudy/PropertiesDialog/index.tsx
  webapp/src/components/App/Singlestudy/index.tsx
Labels: size/S

#1123 feat(studies): add filter for variants
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/common/types.ts
  webapp/src/components/App/Studies/FilterDrawer.tsx
  webapp/src/components/App/Studies/HeaderBottom.tsx
  webapp/src/components/App/Studies/StudyCard.tsx
  webapp/src/redux/ducks/studies.ts
  webapp/src/utils/studiesUtils.ts
Labels: size/L

#1121 Changelog
  .github/workflows/deploy.yml
Labels: documentation, size/XS

#1075 feat(model): add table mode
  antarest/study/business/table_mode_management.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/folder_node.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/areas/areas.py
  antarest/study/storage/variantstudy/business/default_values.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  tests/integration/test_integration_table_mode_manager.py
  tests/variantstudy/model/command/test_create_link.py
  webapp/.eslintrc.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/BindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/CreateTemplateTableDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/TableTemplateFormDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/UpdateTemplateTableDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
  webapp/src/components/App/Singlestudy/explore/common/ListElement.tsx
  webapp/src/components/App/index.tsx
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/EditableMatrix/style.ts
  webapp/src/components/common/EditableMatrix/utils.ts
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/FormTable/Table.tsx
  webapp/src/components/common/FormTable/index.tsx
  webapp/src/components/common/FormTable/utils.ts
  webapp/src/components/common/Handsontable.tsx
  webapp/src/components/common/PropertiesView.tsx
  webapp/src/components/common/dialogs/FormDialog.tsx
  webapp/src/components/common/fieldEditors/ListFE/index.tsx
  webapp/src/components/common/fieldEditors/ListFE/utils.ts
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/hoc/reactHookFormSupport.tsx
  webapp/src/services/api/forms/tableMode.ts
  webapp/src/services/utils/localStorage.ts
  webapp/src/theme.ts
  webapp/src/utils/feUtils.ts
Labels: size/XXL

#1134 feat(storage): add playlist weights
  antarest/study/business/config_management.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/helpers.py
  antarest/study/storage/variantstudy/business/command_extractor.py
  antarest/study/storage/variantstudy/model/command/update_playlist.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  tests/storage/rawstudies/test_factory.py
  tests/storage/rawstudies/test_helpers.py
Labels: size/L

#1136 refactor(eslint): enforce consistent brace style for all control statements
  webapp/.eslintrc.json
  webapp/src/components/App/Data/DatasetCreationDialog.tsx
  webapp/src/components/App/Data/utils.tsx
  webapp/src/components/App/Singlestudy/Commands/Edition/DraggableCommands/CommandImportButton.tsx
  webapp/src/components/App/Singlestudy/Commands/Edition/DraggableCommands/CommandListView.tsx
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/index.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/Notes/utils.ts
  webapp/src/components/App/Singlestudy/HomeView/InformationView/index.tsx
  webapp/src/components/App/Singlestudy/HomeView/StudyTreeView/index.tsx
  webapp/src/components/App/Singlestudy/NavHeader.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/AddConstraintTermForm/OptionsList.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/BindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/OptionsList.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/index.tsx
  webapp/src/components/App/Singlestudy/explore/TabWrapper.tsx
  webapp/src/components/App/Singlestudy/index.tsx
  webapp/src/components/App/Studies/ExportModal/index.tsx
  webapp/src/components/common/fieldEditors/ColorPickerFE/utils.ts
  webapp/src/components/common/loaders/AppLoader.tsx
  webapp/src/components/wrappers/MaintenanceWrapper/MessageInfoDialog.tsx
  webapp/src/redux/selectors.ts
  webapp/src/services/utils/index.ts
Labels: size/L

#1132 1006 submit creation launch modal with
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantModal/index.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/index.tsx
  webapp/src/components/App/Singlestudy/PropertiesDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/CreateAreaModal.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CreateCandidateDialog.tsx
  webapp/src/components/App/Studies/CreateStudyDialog.tsx
  webapp/src/components/common/Fieldset.tsx
Labels: size/L

#1137 perf(storage): Update study listing cache instead of invalidation
  antarest/core/interfaces/cache.py
  antarest/study/common/utils.py
  antarest/study/repository.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/web/studies_blueprint.py
  tests/integration/test_integration.py
  tests/storage/repository/test_study.py
Labels: size/L

#1141 feat: add GitHub login in auto generate branch name and fix with '/' in prefix replace
  .github/issue-branch.yml
Labels: size/XS

#1139 feat(launcher): add zipped output import
  antarest/core/utils/utils.py
  antarest/launcher/adapters/abstractlauncher.py
  antarest/launcher/adapters/local_launcher/local_launcher.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  antarest/launcher/web.py
  antarest/study/common/utils.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/inode.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/output.py
  antarest/study/storage/utils.py
  tests/core/test_utils.py
  tests/launcher/test_service.py
  tests/launcher/test_web.py
  tests/storage/test_service.py
Labels: size/XL

#1144 fix(launcher): add check to be sure that study is launched with slurm launcher
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  tests/launcher/test_slurm_launcher.py
Labels: size/M

#1145 fix: some issue with form and field HOC
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/CreateTemplateTableDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/TableTemplateFormDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/UpdateTemplateTableDialog.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/hoc/reactHookFormSupport.tsx
Labels: bug, size/L

#1147 fix(storage): fix output variable extraction for filtered outputs
  antarest/study/storage/rawstudy/model/filesystem/lazy_node.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/mcall/areas/item/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/mcall/areas/item/set.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/mcall/links/item/item.py
  antarest/study/storage/rawstudy/model/filesystem/utils.py
  antarest/study/storage/study_download_utils.py
Labels: size/L

#1148 fix(storage): add alternative cluster id key for removal
  antarest/study/storage/study_download_utils.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
Labels: size/M

#1151 refactor: refactor some default values
  antarest/study/business/table_mode_management.py
  antarest/study/common/default_values.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/create_link.py
  tests/variantstudy/model/command/test_create_link.py
Labels: size/L

#1150 feat(storage): add default matrix values
  antarest/study/storage/rawstudy/model/filesystem/common/area_matrix_list.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/constants.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/bindingconstraints/bindingcontraints.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/load/load.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/miscgen/miscgen.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/renewables/series.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/reserves/reserves.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/solar/solar.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/thermal/series/area/thermal/thermal.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/wind/wind.py
  antarest/study/storage/variantstudy/business/matrix_constants/common.py
  antarest/study/storage/variantstudy/business/matrix_constants_generator.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  tests/integration/test_integration_variantmanager_tool.py
  tests/storage/integration/test_STA_mini.py
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Reserve.tsx
Labels: size/L

#1153 feat(model): add hydro forms
  antarest/study/business/hydro_management.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/constants.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/series/area/area.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  tests/integration/test_integration_variantmanager_tool.py
  tests/storage/integration/test_STA_mini.py
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Allocation.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/DailyPower.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/EnergyCredits.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ReservoirLevels.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/TimeSeries/HydroStorage.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/TimeSeries/RunOfRiver.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/TimeSeries/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/WaterValues.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/preview.png
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/style.ts
  webapp/src/components/App/Singlestudy/explore/TabWrapper.tsx
  webapp/src/components/App/index.tsx
  webapp/src/components/common/fieldEditors/SwitchFE.tsx
Labels: size/XL

#1155 refactor(ui): extract output filters
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/PropertiesForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/utils.ts
  webapp/src/components/App/Singlestudy/explore/common/OutputFilters.tsx
  webapp/src/components/App/Singlestudy/explore/common/types.ts
Labels: size/L
