Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2022-08, with the labels that each got.

#1010 Clean up use promise
  webapp/src/components/App/Singlestudy/explore/Xpansion/Capacities/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Files/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/index.tsx
Labels: size/L

#1015 Add delete output endpoint
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/web/studies_blueprint.py
  tests/integration/test_integration.py
Labels: size/M

#1020 Update libs + some fixes
  webapp/.eslintrc.json
  webapp/package.json
  webapp/src/components/App/Settings/Groups/dialog/CreateGroupDialog.tsx
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/App/Settings/Groups/dialog/UpdateGroupDialog.tsx
  webapp/src/components/App/Settings/Tokens/dialog/CreateTokenDialog.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenFormDialog/TokenForm.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenInfoDialog.tsx
  webapp/src/components/App/Settings/Users/dialog/CreateUserDialog.tsx
  webapp/src/components/App/Settings/Users/dialog/UpdateUserDialog.tsx
  webapp/src/components/App/Settings/Users/dialog/UserFormDialog/UserForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/AddClusterDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/ClusterView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/utils.ts
  webapp/src/components/App/Singlestudy/explore/Xpansion/Capacities/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Files/index.tsx
  webapp/src/components/App/Singlestudy/explore/hooks/useStudyData.ts
  webapp/src/components/App/Studies/MoveStudyDialog.tsx
  webapp/src/components/App/Studies/RefreshButton.tsx
  webapp/src/components/App/Studies/StudiesList/index.tsx
  webapp/src/components/App/Studies/index.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/FormGenerator/AutoSubmitGenerator.tsx
  webapp/src/components/common/FormGenerator/index.tsx
  webapp/src/components/common/utils/UsePromiseCond.tsx
  webapp/src/components/wrappers/LoginWrapper.tsx
  webapp/src/hooks/useAutoUpdateRef.ts
  webapp/src/hooks/useDebouncedState.ts
  webapp/src/redux/components/UseAsyncAppSelectorCond.tsx
  webapp/src/redux/hooks/useAsyncAppSelector.ts
Labels: size/XL

#1037 Fix fetch_all_user error for non admin users
  antarest/core/jwt.py
  antarest/login/service.py
  tests/login/test_service.py
Labels: size/M

#1034 Add unarchive (windows) worker
  .github/workflows/deploy.yml
  antarest/core/config.py
  antarest/core/core_blueprint.py
  antarest/core/tasks/service.py
  antarest/core/utils/utils.py
  antarest/main.py
  antarest/study/service.py
  antarest/worker/archive_worker.py
  antarest/worker/archive_worker_service.py
  antarest/worker/worker.py
  sonar-project.properties
  tests/core/test_tasks.py
  tests/storage/conftest.py
  tests/storage/test_service.py
  tests/worker/test_archive_worker.py
  tests/worker/test_worker.py
Labels: size/L

#1040 Fix missing edition event on variant command appending
  antarest/study/service.py
Labels: size/S

#1042 Allow variant to work with archived parent
  antarest/study/service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/variant_study_service.py
Labels: size/M

#1041 Refacto services entry point
  antarest/core/interfaces/service.py
  antarest/main.py
  antarest/matrixstore/matrix_garbage_collector.py
  antarest/singleton_services.py
  antarest/study/storage/rawstudy/watcher.py
  antarest/utils.py
  antarest/worker/archive_worker_service.py
  antarest/worker/worker.py
Labels: size/XL

#1047 Add 8.3 version support
  antarest/study/business/config_management.py
  antarest/study/model.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/date_serializer.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/areas/item/adequacy_patch.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/areas/item/item.py
  antarest/study/storage/rawstudy/model/filesystem/root/settings/generaldata.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  docs/architecture/2-add-new-antares-version.md
  resources/empty_study_830.zip
  scripts/package_antares_web.sh
  tests/storage/business/test_config_manager.py
Labels: size/L

#1051 Issue with auto submit in Form component
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/Form/utils.ts
Labels: size/S

#1039 Time series management
  antarest/core/utils/string.py
  antarest/study/business/timeseries_config_management.py
  antarest/study/business/utils.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/storage/business/test_timeseries_config_manager.py
  tests/storage/test_service.py
  webapp/.eslintrc.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/AddClusterDialog/AddClusterForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/common/fieldEditors/CheckBoxFE.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/components/common/fieldEditors/SwitchFE.tsx
Labels: size/XXL

#1053 Add adequacy patch configuration interfaces
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/PropertiesForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/utils.ts
Labels: size/L

#1054 Add easier launch options
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/LauncherDialog.tsx
Labels: size/M

#1059 issue 856 Configuration Optimization preferences
  antarest/study/business/optimization_management.py
  antarest/study/business/timeseries_config_management.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  tests/storage/business/test_timeseries_config_manager.py
  webapp/.eslintrc.json
  webapp/config-overrides.js
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/OptimizationPreferences/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/index.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/Form/utils.ts
  webapp/src/hoc/reactHookFormSupport.tsx
  webapp/src/hooks/useBlocker.ts
  webapp/src/hooks/usePrompt.ts
  webapp/src/utils/muiUtils.ts
Labels: size/XL

#1062 Issue 1050 Form auto submit
  webapp/src/components/common/Form/index.tsx
Labels: size/S

#1063 Fix xpansion trad
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
Labels: size/S

#1048 Add launch progression status,
  antarest/core/interfaces/eventbus.py
  antarest/launcher/adapters/abstractlauncher.py
  antarest/launcher/adapters/factory_launcher.py
  antarest/launcher/adapters/local_launcher/local_launcher.py
  antarest/launcher/adapters/log_manager.py
  antarest/launcher/adapters/log_parser.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/extensions/adequacy_patch/extension.py
  antarest/launcher/main.py
  antarest/launcher/service.py
  antarest/launcher/web.py
  antarest/utils.py
  tests/launcher/test_local_launcher.py
  tests/launcher/test_log_parser.py
  tests/launcher/test_service.py
  tests/launcher/test_slurm_launcher.py
  tests/launcher/test_web.py
Labels: size/L

#1066 Add study update name/version on directory scan
  antarest/study/service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/test_service.py
Labels: size/L

#1065 Create xpansion configuration require a page refresh to work
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/ClusterView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/DebugView/StudyDataView/StudyMatrixView/StudyMatrixView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Capacities/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Files/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/index.tsx
  webapp/src/components/common/MatrixInput/MatrixAssignDialog.tsx
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/page/SimpleContent.tsx
  webapp/src/components/common/utils/UsePromiseCond.tsx
Labels: size/L

#1045 Add automatic archival service
  alembic/versions/e65e0c04606b_add_last_access_study_prop.py
  antarest/core/config.py
  antarest/main.py
  antarest/singleton_services.py
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/storage/auto_archive_service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/utils.py
  scripts/rollback.sh
  tests/storage/business/test_autoarchive_service.py
  tests/storage/test_service.py
Labels: size/L

#1017 Refacto append commands + auto add matrix in store for managed studies
  antarest/study/business/utils.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/business/utils.py
  antarest/study/storage/variantstudy/model/model.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/variant_blueprint.py
  tests/integration/test_integration.py
  tests/variantstudy/conftest.py
  tests/variantstudy/model/test_variant_model.py
  tests/variantstudy/test_utils.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/Commands/Edition/DraggableCommands/CommandListItem/CommandMatrixViewer.tsx
  webapp/src/components/App/Singlestudy/Commands/Edition/DraggableCommands/CommandListItem/index.tsx
  webapp/src/components/common/dialogs/DataViewerDialog/index.tsx
Labels: size/L

#1070 Go to parent study when deleting a variant
  webapp/src/components/App/Singlestudy/NavHeader.tsx
Labels: size/XS

#1073 Add download button to matrix views
  webapp/src/components/App/Singlestudy/explore/Modelization/DebugView/StudyDataView/StudyFileView.tsx
  webapp/src/components/App/Studies/HeaderTopRight.tsx
  webapp/src/components/common/FileTable.tsx
  webapp/src/components/common/MatrixInput/index.tsx
Labels: size/M

#988 Issue 848 binding constraints
  antarest/core/exceptions.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/business/link_management.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/PropertiesForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddBindingConstDialog/AddBindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddBindingConstDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstPropsView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/AddConstraintTermForm/OptionsList.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/AddConstraintTermForm/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/BindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/OptionsList.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/constraintviews/ConstraintElement.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/constraintviews/OffsetInput.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/constraintviews/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/common/FormGenerator/index.tsx
  webapp/src/redux/ducks/studyDataSynthesis.ts
  webapp/src/redux/selectors.ts
  webapp/src/services/api/studydata.ts
Labels: size/XXL
