Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2022-12, with the labels that each got.

#1189 feat(ui-outputs): add output view
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/common/types.ts
  webapp/src/components/App/Settings/Groups/Header.tsx
  webapp/src/components/App/Settings/Tokens/Header.tsx
  webapp/src/components/App/Settings/Users/Header.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/SelectionDrawer.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/preview.png
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/utils.ts
  webapp/src/components/App/Singlestudy/explore/Results/index.tsx
  webapp/src/components/App/Studies/StudiesList/index.tsx
  webapp/src/components/common/PropertiesView.tsx
  webapp/src/components/common/fieldEditors/BooleanFE.tsx
  webapp/src/components/common/fieldEditors/RadioFE.tsx
  webapp/src/components/common/fieldEditors/SearchFE.tsx
  webapp/src/redux/selectors.ts
Labels: size/XXL

#1191 fix(storage): fix ouput file load
  antarest/study/storage/rawstudy/model/filesystem/matrix/output_series_matrix.py
Labels: size/M

#1192 perf(storage): remove file_exist check for ouput tree building
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/binding_const.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/link.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/set.py
  antarest/study/storage/study_download_utils.py
  tests/storage/integration/test_STA_mini.py
Labels: size/M

#1193 feat(storage): add migration between study version
  antarest/study/storage/study_version_upgrader.py
  antarest/study/web/studies_blueprint.py
  resources/templates/empty_study_840.zip
  tests/storage/business/test_study_version_upgrader.py
Labels: size/M

#1195 fix(ui-model): issue with renewable and thermal forms
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/utils.ts
Labels: bug, size/M

#1197 feat(storage): add map layers management
  antarest/core/exceptions.py
  antarest/study/business/area_management.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  tests/storage/business/test_arealink_manager.py
Labels: size/L
