Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2022-09, with the labels that each got.

#1069 Add a launch progress bar to task view and job history view
  antarest/launcher/adapters/abstractlauncher.py
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/JobStepper.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/index.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/style.ts
  webapp/src/components/App/Studies/LauncherDialog.tsx
  webapp/src/components/App/Tasks/JobTableView.tsx
  webapp/src/components/App/Tasks/index.tsx
  webapp/src/components/common/LinearProgressWithLabel.tsx
  webapp/src/services/api/tasks.ts
Labels: size/L

#1072 Add output archive management
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/web/studies_blueprint.py
  tests/storage/test_service.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/explore/Results/index.tsx
  webapp/src/services/api/study.ts
Labels: size/L

#1074 Add checkbox to delete all variants children
  antarest/study/service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/studies_blueprint.py
  tests/storage/test_service.py
  tests/storage/web/test_studies_bp.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/NavHeader.tsx
  webapp/src/components/App/Studies/StudyCard.tsx
  webapp/src/redux/ducks/studies.ts
  webapp/src/services/api/study.ts
Labels: size/L

#1081 Remove unnecessary endpoint
  antarest/study/business/link_management.py
  antarest/study/web/study_data_blueprint.py
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/index.tsx
  webapp/src/redux/selectors.ts
Labels: size/L

#1080 Add new playlist update command + api endpoint
  antarest/study/business/config_management.py
  antarest/study/storage/rawstudy/model/helpers.py
  antarest/study/storage/variantstudy/business/command_extractor.py
  antarest/study/storage/variantstudy/business/command_reverter.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_playlist.py
  antarest/study/web/study_data_blueprint.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#1088 Add delete all commands button
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
  webapp/src/components/App/Singlestudy/Commands/Edition/style.ts
Labels: size/M

#1089 Allow user to download the matrix dataset related to a variant commands
  antarest/matrixstore/service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/variant_blueprint.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
  webapp/src/services/api/variant.ts
Labels: size/L

#1098 Add xpansion direct/indirect link profiles
  antarest/study/business/xpansion_management.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CandidateForm.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/share/styles.ts
  webapp/src/components/App/Singlestudy/explore/Xpansion/types.ts
Labels: size/L

#1097 Add xpansion constraints and weights new directory support
  antarest/study/business/xpansion_management.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/constraint_resources.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/expansion.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/matrix_resources.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/integration/test_integration_xpansion.py
  tests/storage/business/test_xpansion_manager.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Xpansion/Capacities.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Capacities/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Constraints.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/FileList.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Files/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Weights.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/types.ts
  webapp/src/components/App/index.tsx
  webapp/src/services/api/xpansion.ts
Labels: size/XXL

#1099 Add sensitivity parameters edition
  antarest/study/business/xpansion_management.py
  antarest/study/storage/rawstudy/model/filesystem/json_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/expansion.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/sensitivity.py
  tests/integration/test_integration_xpansion.py
  tests/storage/business/test_xpansion_manager.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/types.ts
Labels: size/L
