Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2022-05, with the labels that each got.

#835 issue-771-Refacto_patch_service_/_get_study_information_so_that_everything_is_in_db
  alembic/versions/e6bb88859884_add_study_additional_data.py
  antarest/core/interfaces/cache.py
  antarest/core/logging/utils.py
  antarest/study/business/area_management.py
  antarest/study/common/studystorage.py
  antarest/study/main.py
  antarest/study/model.py
  antarest/study/repository.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/patch_service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/remove_area.py
  antarest/study/storage/variantstudy/model/command/remove_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_district.py
  antarest/study/storage/variantstudy/model/command/remove_link.py
  antarest/study/storage/variantstudy/model/command/remove_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/replace_matrix.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_comments.py
  antarest/study/storage/variantstudy/model/command/update_config.py
  antarest/study/storage/variantstudy/model/command/update_raw_file.py
  antarest/study/storage/variantstudy/model/command/utils_extractor.py
  antarest/study/storage/variantstudy/model/command_context.py
  antarest/study/storage/variantstudy/variant_command_extractor.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/study_data_blueprint.py
  antarest/tools/lib.py
  tests/integration/test_integration.py
  tests/matrixstore/test_matrix_garbage_collector.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/business/test_import.py
  tests/storage/business/test_patch_service.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/business/test_variant_study_service.py
  tests/storage/integration/conftest.py
  tests/storage/test_service.py
  tests/variantstudy/model/command/conftest.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_manage_district.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/model/command/test_remove_cluster.py
  tests/variantstudy/model/command/test_remove_link.py
  tests/variantstudy/model/command/test_remove_renewables_cluster.py
  tests/variantstudy/model/command/test_replace_matrix.py
  tests/variantstudy/model/command/test_update_comments.py
  tests/variantstudy/model/command/test_update_config.py
  tests/variantstudy/model/test_variant_model.py
  tests/variantstudy/test_command_factory.py
  webapp/src/services/api/study.ts
  webapp_v2/src/pages/SingleStudy/index.tsx
  webapp_v2/src/pages/Studies/index.tsx
  webapp_v2/src/services/api/study.ts
Labels: size/XXL

#883 Add params to use promise
  webapp/src/components/settings/Groups/index.tsx
  webapp/src/components/settings/Maintenance/index.tsx
  webapp/src/components/settings/Tokens/index.tsx
  webapp/src/components/settings/Users/index.tsx
  webapp/src/hooks/usePromise.ts
  webapp/src/hooks/usePromiseWithSnackbarError.ts
Labels: size/M

#808 Xpansion page integration
  antarest/study/business/xpansion_management.py
  antarest/study/service.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/storage/business/test_xpansion_manager.py
  webapp/public/locales/en/main.json
  webapp/public/locales/en/xpansion.json
  webapp/public/locales/fr/main.json
  webapp/public/locales/fr/xpansion.json
  webapp/src/App.tsx
  webapp/src/components/common/BasicModal.tsx
  webapp/src/components/common/FilledTextInput.tsx
  webapp/src/components/common/LogModal.tsx
  webapp/src/components/common/MatrixView/index.tsx
  webapp/src/components/common/MatrixView/style.ts
  webapp/src/components/common/SelectMulti.tsx
  webapp/src/components/common/SelectSingle.tsx
  webapp/src/components/common/TagTextInput.tsx
  webapp/src/components/common/dialogs/BasicDialog.tsx
  webapp/src/components/singlestudy/Commands/Edition/DraggableCommands/CommandListItem/index.tsx
  webapp/src/components/singlestudy/HomeView/InformationView/CreateVariantModal.tsx
  webapp/src/components/singlestudy/PropertiesModal.tsx
  webapp/src/components/singlestudy/explore/Modelization/Map/LinksView.tsx
  webapp/src/components/singlestudy/explore/Modelization/Map/NodeListing.tsx
  webapp/src/components/singlestudy/explore/Modelization/Map/PanelView.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/CandidateForm.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/CandidateListing.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/CreateCandidateModal.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/XpansionPropsView.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Capacities/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Files/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Settings/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/XpansionTable.tsx
  webapp/src/components/singlestudy/explore/Xpansion/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/styles.ts
  webapp/src/components/singlestudy/explore/Xpansion/types.ts
  webapp/src/components/studies/CreateStudyModal.tsx
  webapp/src/components/studies/ExportModal/ExportFilter/Filter/MultipleLinkElement/index.tsx
  webapp/src/components/studies/ExportModal/ExportFilter/Filter/index.tsx
  webapp/src/components/studies/ExportModal/ExportFilter/index.tsx
  webapp/src/components/studies/ExportModal/index.tsx
  webapp/src/components/studies/StudiesList.tsx
  webapp/src/components/tasks/LaunchJobLogView.tsx
  webapp/src/i18n.js
  webapp/src/pages/SingleStudy/index.tsx
  webapp/src/pages/Tasks.tsx
  webapp/src/pages/wrappers/MenuWrapper/index.tsx
  webapp/src/services/api/xpansion.ts
  webapp/src/services/utils/index.ts
  webapp/src/theme.ts
Labels: size/XXL

#882 Fixes & Improvements
  antarest/study/business/area_management.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  webapp/public/locales/en/studymanager.json
  webapp/public/locales/fr/studymanager.json
  webapp/src/components/common/StarToggle.tsx
  webapp/src/components/singlestudy/HomeView/InformationView/index.tsx
  webapp/src/components/singlestudy/NavHeader.tsx
  webapp/src/components/singlestudy/explore/Modelization/Map/index.tsx
  webapp/src/components/studies/HeaderBottom.tsx
  webapp/src/components/studies/ImportStudyDialog.tsx
  webapp/src/components/studies/StudyCard.tsx
  webapp/src/pages/Studies/index.tsx
  webapp/src/services/api/study.ts
  webapp/src/services/utils/globalWsListeners.ts
  webapp/src/store/reducers.ts
  webapp/src/store/selectors.ts
  webapp/src/store/study.ts
Labels: size/L

#889 Fix sub variant generation
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/variantstudy/model/test_variant_model.py
Labels: size/S

#890 UI fixes
  webapp/src/common/types.ts
  webapp/src/components/common/BasicModal.tsx
  webapp/src/components/common/dialogs/ConfirmationDialog.tsx
  webapp/src/components/common/dialogs/FormDialog.tsx
  webapp/src/components/common/dialogs/OkDialog.tsx
  webapp/src/components/settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/settings/Groups/dialog/GroupFormDialog/index.tsx
  webapp/src/components/settings/Tokens/dialog/TokenFormDialog/TokenForm.tsx
  webapp/src/components/settings/Tokens/dialog/TokenFormDialog/index.tsx
  webapp/src/components/settings/Users/dialog/UserFormDialog/UserForm.tsx
  webapp/src/components/settings/Users/dialog/UserFormDialog/index.tsx
  webapp/src/components/singlestudy/HomeView/InformationView/Notes/NoteEditorModal.tsx
  webapp/src/components/singlestudy/PropertiesModal.tsx
  webapp/src/pages/SingleStudy/index.tsx
Labels: size/L

#892 Hot fixes
  antarest/login/main.py
  antarest/study/business/area_management.py
  antarest/study/model.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/mcind/mcind.py
  antarest/study/storage/rawstudy/model/filesystem/root/settings/generaldata.py
  antarest/study/storage/rawstudy/model/helpers.py
  tests/integration/test_integration.py
  tests/storage/rawstudies/helpers.py
  tests/storage/repository/filesystem/config/test_config_files.py
  webapp/src/components/settings/Tokens/dialog/CreateTokenDialog.tsx
Labels: size/M

#900 Add managed studies virtual folder management
  alembic/versions/c9dcca887456_move_folder_property.py
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/web/studies_blueprint.py
  tests/integration/test_integration.py
  webapp/public/locales/en/studymanager.json
  webapp/public/locales/fr/studymanager.json
  webapp/src/components/studies/MoveStudyDialog.tsx
  webapp/src/components/studies/StudyCard.tsx
  webapp/src/services/api/study.ts
Labels: size/L

#901 Add ts number type and view
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/ts_numbers/ts_numbers.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/ts_numbers/ts_numbers_data.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/repository/filesystem/test_ts_numbers_vector.py
  webapp/src/components/singlestudy/explore/Modelization/DebugView/StudyDataView/StudyFileView.tsx
Labels: size/L

#902 replace modals by dialogs
  webapp/.gitignore
  webapp/src/components/common/BasicModal.tsx
  webapp/src/components/common/ConfirmationModal.tsx
  webapp/src/components/common/LogModal.tsx
  webapp/src/components/common/dialogs/BasicDialog.tsx
  webapp/src/components/common/dialogs/DataViewerDialog/index.tsx
  webapp/src/components/common/dialogs/DataViewerDialog/styles.ts
  webapp/src/components/singlestudy/Commands/Edition/AddCommandDialog.tsx
  webapp/src/components/singlestudy/Commands/Edition/index.tsx
  webapp/src/components/singlestudy/HomeView/InformationView/CreateVariantModal/index.tsx
  webapp/src/components/singlestudy/HomeView/InformationView/CreateVariantModal/style.ts
  webapp/src/components/singlestudy/HomeView/InformationView/LauncherHistory/JobStepper.tsx
  webapp/src/components/singlestudy/HomeView/InformationView/Notes/NodeEditorModal/index.tsx
  webapp/src/components/singlestudy/HomeView/InformationView/Notes/NodeEditorModal/style.ts
  webapp/src/components/singlestudy/HomeView/InformationView/Notes/index.tsx
  webapp/src/components/singlestudy/HomeView/InformationView/index.tsx
  webapp/src/components/singlestudy/NavHeader.tsx
  webapp/src/components/singlestudy/PropertiesDialog/index.tsx
  webapp/src/components/singlestudy/PropertiesDialog/style.ts
  webapp/src/components/singlestudy/explore/Modelization/Map/CreateAreaModal.tsx
  webapp/src/components/singlestudy/explore/Modelization/Map/PanelView.tsx
  webapp/src/components/singlestudy/explore/Modelization/Map/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/CreateCandidateDialog.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Capacities/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Files/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Settings/index.tsx
  webapp/src/components/studies/CreateStudyDialog/index.tsx
  webapp/src/components/studies/CreateStudyDialog/style.ts
  webapp/src/components/studies/DeleteStudyModal.tsx
  webapp/src/components/studies/HeaderTopRight.tsx
  webapp/src/components/studies/LauncherDialog/index.tsx
  webapp/src/components/studies/LauncherDialog/style.ts
  webapp/src/components/studies/StudiesList.tsx
  webapp/src/components/studies/StudyCard.tsx
  webapp/src/pages/Tasks.tsx
  webapp/src/pages/wrappers/MaintenanceWrapper/MessageInfoDialog.tsx
  webapp/src/pages/wrappers/MaintenanceWrapper/index.tsx
  webapp/src/pages/wrappers/MenuWrapper/LogoutModal.tsx
  webapp/src/pages/wrappers/MenuWrapper/index.tsx
  webapp/src/pages/wrappers/MenuWrapper/styles.ts
Labels: size/XXL

#898 Issue 716 fix todos in commands
  antarest/study/business/area_management.py
  antarest/study/business/matrix_management.py
  antarest/study/business/utils.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/bindingconstraints/bindingcontraints.py
  antarest/study/storage/variantstudy/business/command_extractor.py
  antarest/study/storage/variantstudy/business/command_reverter.py
  antarest/study/storage/variantstudy/business/utils.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_cluster.py
  antarest/study/storage/variantstudy/model/command/create_district.py
  antarest/study/storage/variantstudy/model/command/create_link.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/remove_area.py
  antarest/study/storage/variantstudy/model/command/remove_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_district.py
  antarest/study/storage/variantstudy/model/command/remove_link.py
  antarest/study/storage/variantstudy/model/command/remove_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/replace_matrix.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_comments.py
  antarest/study/storage/variantstudy/model/command/update_config.py
  antarest/study/storage/variantstudy/model/command/update_raw_file.py
  antarest/study/storage/variantstudy/variant_command_extractor.py
  tests/integration/test_integration.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/storage/test_model.py
  tests/storage/test_service.py
  tests/variantstudy/model/command/test_alias_decoder.py
  tests/variantstudy/model/command/test_create_area.py
  tests/variantstudy/model/command/test_create_cluster.py
  tests/variantstudy/model/command/test_create_link.py
  tests/variantstudy/model/command/test_create_renewables_cluster.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_manage_district.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/model/command/test_remove_cluster.py
  tests/variantstudy/model/command/test_remove_link.py
  tests/variantstudy/model/command/test_remove_renewables_cluster.py
  tests/variantstudy/model/command/test_replace_matrix.py
  tests/variantstudy/model/command/test_update_comments.py
  tests/variantstudy/model/command/test_update_config.py
  tests/variantstudy/model/command/test_update_rawfile.py
  tests/variantstudy/test_command_factory.py
Labels: size/XXL

#907 Add api with information about outputs variables
  antarest/study/service.py
  antarest/study/storage/study_download_utils.py
  antarest/study/web/studies_blueprint.py
  tests/integration/test_integration.py
  tests/storage/integration/test_STA_mini.py
Labels: size/L

#910 Update doc
  docs/assets/media/img/mainmenu.png
  docs/assets/media/img/screenshot_apidoc.png
  docs/assets/media/img/screenshot_datalisting.png
  docs/assets/media/img/screenshot_information.png
  docs/assets/media/img/screenshot_joblisting.png
  docs/assets/media/img/screenshot_mainmenu.png
  docs/assets/media/img/screenshot_modal_datasetcreation.png
  docs/assets/media/img/screenshot_modal_permissions.png
  docs/assets/media/img/screenshot_studylisting1.png
  docs/assets/media/img/screenshot_studylisting2.png
  docs/assets/media/img/screenshot_tokencreation.png
  docs/assets/media/img/screenshot_tokenlisting.png
  docs/assets/media/img/screenshot_tokenresult.png
  docs/assets/media/img/screenshot_treeview.png
  docs/assets/media/img/screenshot_treeview2.png
  docs/assets/media/img/screenshot_useraccount.png
  docs/assets/media/img/screenshot_variant_edition.png
  docs/assets/media/img/screenshot_variant_tree.png
  docs/assets/media/img/studyinformation.png
  docs/assets/media/img/studylisting.png
  docs/assets/media/img/studyvariantedit.png
  docs/assets/media/img/userguide_apidoc.png
  docs/assets/media/img/userguide_dataset_creation.png
  docs/assets/media/img/userguide_dataset_listing.png
  docs/assets/media/img/userguide_mainmenu.png
  docs/assets/media/img/userguide_studyactions.png
  docs/assets/media/img/userguide_studylisting.png
  docs/assets/media/img/userguide_studyoverview.png
  docs/assets/media/img/userguide_token_creation.png
  docs/assets/media/img/userguide_token_listing.png
  docs/assets/media/img/userguide_token_result.png
  docs/assets/media/img/userguide_treeview_json.png
  docs/assets/media/img/userguide_treeview_matrix.png
  docs/assets/media/img/userguide_variantcommands.png
  docs/user-guide/1-interface.md
Labels: size/M

#913 Remove reverts from some commands, implement UpdateConfig
  antarest/study/business/utils.py
  antarest/study/storage/variantstudy/business/command_extractor.py
  antarest/study/storage/variantstudy/business/command_reverter.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_district.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_manage_district.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/model/command/test_remove_cluster.py
  tests/variantstudy/model/command/test_remove_link.py
  tests/variantstudy/model/command/test_remove_renewables_cluster.py
  tests/variantstudy/test_command_factory.py
Labels: size/XL

#911 Allow naming the output of a launch
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/service.py
  antarest/study/common/studystorage.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/utils.py
  tests/launcher/test_service.py
  webapp/src/components/studies/LauncherDialog/index.tsx
  webapp/src/services/api/study.ts
Labels: size/L

#914 Issue 840 Remove redux HOC
  webapp/src/components/common/DownloadLink.tsx
  webapp/src/components/common/LogModal.tsx
  webapp/src/components/settings/Groups/Header.tsx
  webapp/src/components/settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/settings/Groups/index.tsx
  webapp/src/components/settings/Tokens/dialog/TokenFormDialog/TokenForm.tsx
  webapp/src/components/settings/Tokens/index.tsx
  webapp/src/components/singlestudy/NavHeader.tsx
  webapp/src/components/studies/CreateStudyDialog/index.tsx
  webapp/src/components/studies/ImportStudyDialog.tsx
  webapp/src/components/studies/StudiesList.tsx
  webapp/src/components/tasks/NotificationBadge.tsx
  webapp/src/pages/Data.tsx
  webapp/src/pages/Settings.tsx
  webapp/src/pages/SingleStudy/index.tsx
  webapp/src/pages/Studies/index.tsx
  webapp/src/pages/Tasks.tsx
  webapp/src/pages/wrappers/MaintenanceWrapper/MessageInfoDialog.tsx
  webapp/src/pages/wrappers/MaintenanceWrapper/index.tsx
  webapp/src/pages/wrappers/MenuWrapper/index.tsx
  webapp/src/redux/selectors.ts
Labels: size/XL

#917 Issue Update usePromise hook
  .github/workflows/main.yml
  webapp/src/components/settings/Maintenance/index.tsx
  webapp/src/components/singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/hooks/usePromise.ts
  webapp/src/hooks/usePromiseWithSnackbarError.ts
  webapp/src/pages/wrappers/LoginWrapper.tsx
Labels: size/M

#916 Add sonar for front
  .github/workflows/main.yml
  sonar-project.properties
  webapp/package.json
  webapp/src/components/singlestudy/HomeView/InformationView/LauncherHistory/index.tsx
  webapp/src/services/api/matrix.ts
  webapp/src/services/api/study.ts
  webapp/src/services/api/xpansion.ts
Labels: size/M

#919 Fix pydantic new default deeepcopy on validation
  antarest/study/storage/variantstudy/model/command_context.py
  tests/storage/business/test_xpansion_manager.py
Labels: size/S

#921 Issue 918 Update Studies page
  webapp/.eslintrc.json
  webapp/public/locales/fr/main.json
  webapp/src/common/types.ts
  webapp/src/components/common/DownloadLink.tsx
  webapp/src/components/common/inputs/CheckboxesTags.tsx
  webapp/src/components/settings/Groups/Header.tsx
  webapp/src/components/settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/settings/Groups/index.tsx
  webapp/src/components/settings/Tokens/dialog/TokenFormDialog/TokenForm.tsx
  webapp/src/components/settings/Tokens/index.tsx
  webapp/src/components/singlestudy/HomeView/InformationView/index.tsx
  webapp/src/components/singlestudy/NavHeader.tsx
  webapp/src/components/studies/CreateStudyDialog/index.tsx
  webapp/src/components/studies/FilterDrawer.tsx
  webapp/src/components/studies/HeaderBottom.tsx
  webapp/src/components/studies/ImportStudyDialog.tsx
  webapp/src/components/studies/LauncherDialog/index.tsx
  webapp/src/components/studies/SideNav.tsx
  webapp/src/components/studies/StudiesList.tsx
  webapp/src/components/studies/StudiesList/StudyCardCell.tsx
  webapp/src/components/studies/StudiesList/index.tsx
  webapp/src/components/studies/StudyCard.tsx
  webapp/src/components/studies/StudyTree.tsx
  webapp/src/components/tasks/NotificationBadge.tsx
  webapp/src/index.tsx
  webapp/src/pages/Data.tsx
  webapp/src/pages/Settings.tsx
  webapp/src/pages/SingleStudy/index.tsx
  webapp/src/pages/Studies/index.tsx
  webapp/src/pages/Studies/utils.ts
  webapp/src/pages/Tasks.tsx
  webapp/src/pages/wrappers/LoginWrapper.tsx
  webapp/src/pages/wrappers/MaintenanceWrapper/MessageInfoDialog.tsx
  webapp/src/pages/wrappers/MaintenanceWrapper/index.tsx
  webapp/src/pages/wrappers/MenuWrapper/index.tsx
  webapp/src/redux/ducks/auth.ts
  webapp/src/redux/ducks/groups.ts
  webapp/src/redux/ducks/index.ts
  webapp/src/redux/ducks/studies.ts
  webapp/src/redux/ducks/users.ts
  webapp/src/redux/hooks.ts
  webapp/src/redux/hooks/useAppDispatch.ts
  webapp/src/redux/hooks/useAppSelector.ts
  webapp/src/redux/hooks/useAsyncAppSelector.ts
  webapp/src/redux/middlewares/localStorageMiddleware.ts
  webapp/src/redux/selectors.ts
  webapp/src/redux/utils.ts
  webapp/src/services/api/client.ts
  webapp/src/services/config.ts
  webapp/src/services/utils/localStorage.ts
  webapp/src/theme.ts
Labels: size/XXL

#922 Fix logmodal & subscription on websockets reconnection
  antarest/study/service.py
  antarest/study/web/raw_studies_blueprint.py
  webapp/src/components/common/LogModal.tsx
  webapp/src/pages/wrappers/LoginWrapper.tsx
  webapp/src/services/webSockets.ts
Labels: size/M

#929 build: fix issues with the production build
  webapp/package.json
  webapp/src/components/common/ImportForm.tsx
  webapp/src/components/common/ImportForm/index.tsx
  webapp/src/components/common/ImportForm/style.ts
  webapp/src/components/common/MatrixView/index.tsx
  webapp/src/components/common/MatrixView/style.ts
  webapp/src/components/common/dialogs/OkDialog.tsx
Labels: size/L
