Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2022-11, with the labels that each got.

#1159 feat(xpansion): update CreateCandidateDialog
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CandidateForm.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CreateCandidateDialog.tsx
Labels: size/M

#1156 feat(studies): update scan folder button location
  webapp/src/components/App/Studies/StudiesList/index.tsx
  webapp/src/components/App/Studies/StudyTree.tsx
Labels: size/L

#1162 feat(general): add thematic trimming settings for 'filtering' field
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields.tsx
Labels: size/M

#1163 fix(launcher): protect output import from db timeout
  antarest/launcher/service.py
Labels: size/M

#1165 feat(general): add playlist dialog form
  antarest/study/business/playlist_management.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/helpers.py
  antarest/study/storage/variantstudy/model/command/update_playlist.py
  antarest/study/web/study_data_blueprint.py
  webapp/.eslintrc.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/PlaylistDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/PlaylistDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/index.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/FormTable/Table.tsx
  webapp/src/components/common/FormTable/index.tsx
Labels: size/XL

#1167 feat(model): add geographic trimming templates on table mode
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/index.tsx
  webapp/src/components/App/Singlestudy/explore/common/ListElement.tsx
  webapp/src/services/utils/localStorage.ts
Labels: size/M

#1171 feat(api): update endpoints URI for form
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/PlaylistDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/utils.ts
  webapp/src/services/api/forms/tableMode.ts
Labels: size/L

#1173 feat(ui-model): allow to change table template name in table mode
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/CreateTemplateTableDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/TableTemplateFormDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/UpdateTemplateTableDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/index.tsx
  webapp/src/components/App/Singlestudy/explore/common/ListElement.tsx
Labels: size/M

#1177 fix(storage): limit number of cache listing updates
  antarest/study/repository.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/variant_study_service.py
Labels: size/S

#1179 feat(launcher): improve job listing
  antarest/launcher/service.py
  antarest/study/repository.py
  tests/launcher/test_service.py
Labels: size/M

#1178 v2.10.1
  antarest/__init__.py
  antarest/core/interfaces/eventbus.py
  antarest/gui.py
  antarest/launcher/service.py
  antarest/study/repository.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/tools/admin_lib.py
  setup.py
  sonar-project.properties
  tests/launcher/test_service.py
  webapp/package.json
Labels: size/M

#1175 fix(storage): add db context to autoarchiver service
  antarest/study/storage/auto_archive_service.py
Labels: size/M

#1182 fix(storage): remove full output scan before import
  antarest/study/storage/abstract_storage_service.py
Labels: size/XS

#1180 feat(ui-common/ui-hoc): allow async default values on Form component and display skeleton for fields
  webapp/.eslintrc.json
  webapp/src/components/App/Settings/Groups/dialog/CreateGroupDialog.tsx
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/App/Settings/Groups/dialog/UpdateGroupDialog.tsx
  webapp/src/components/App/Settings/Tokens/dialog/CreateTokenDialog.tsx
  webapp/src/components/App/Settings/Users/dialog/CreateUserDialog.tsx
  webapp/src/components/App/Settings/Users/dialog/UpdateUserDialog.tsx
  webapp/src/components/App/Settings/Users/dialog/UserFormDialog/UserForm.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantModal/index.tsx
  webapp/src/components/App/Singlestudy/PropertiesDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/PlaylistDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/styles.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/PropertiesForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/AddClusterDialog/AddClusterForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/AddClusterDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddBindingConstDialog/AddBindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddBindingConstDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/AddConstraintTermForm/OptionsList.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/AddConstraintTermForm/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/BindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/CreateAreaModal.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/CreateTemplateTableDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/dialogs/UpdateTemplateTableDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CreateCandidateDialog.tsx
  webapp/src/components/App/Singlestudy/explore/common/OutputFilters.tsx
  webapp/src/components/App/Studies/CreateStudyDialog.tsx
  webapp/src/components/App/Studies/MoveStudyDialog.tsx
  webapp/src/components/common/Fieldset.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/Form/types.ts
  webapp/src/components/common/Form/useDefaultValuesPlus.ts
  webapp/src/components/common/FormGenerator/index.tsx
  webapp/src/components/common/FormTable/Table.tsx
  webapp/src/components/common/FormTable/index.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/components/wrappers/LoginWrapper.tsx
  webapp/src/hoc/reactHookFormSupport.tsx
  webapp/src/hooks/useMemoLocked.ts
  webapp/src/utils/muiUtils.ts
Labels: size/XL

#1183 feat(ui-model): add new options for transmission capa global settings
  antarest/study/business/optimization_management.py
  antarest/study/storage/rawstudy/model/filesystem/root/settings/generaldata.py
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/utils.ts
Labels: size/M

#1185 feat: add 8.4.0 simulator support
  antarest/study/business/optimization_management.py
  antarest/study/model.py
  antarest/study/storage/rawstudy/model/filesystem/root/settings/generaldata.py
  resources/empty_study_840.zip
  tests/integration/test_integration.py
Labels: size/S

#1187 feat(storage): assign same folder for variant creation
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/variantstudy/model/test_variant_model.py
Labels: size/XS

#1110 feat(core): add simulator remote worker
  Dockerfile
  antarest/singleton_services.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/web/study_data_blueprint.py
  antarest/utils.py
  antarest/worker/simulator_worker.py
  antarest/worker/worker.py
  tests/integration/launcher.py
  tests/integration/launcher_mock.sh
  tests/worker/test_simulator_worker.py
Labels: size/L

#1176 feat(storage): add migration between study version
  antarest/core/tasks/model.py
  antarest/core/tasks/service.py
  antarest/study/service.py
  antarest/study/storage/study_version_upgrader.py
  antarest/study/web/studies_blueprint.py
  antarest/tools/cli.py
  tests/core/test_tasks.py
  tests/storage/business/assets/little_study_700.zip
  tests/storage/business/assets/little_study_720.zip
  tests/storage/business/test_study_version_upgrader.py
  tests/storage/test_service.py
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/NavHeader.tsx
  webapp/src/components/App/Tasks/JobTableView.tsx
  webapp/src/components/App/Tasks/NotificationBadge.tsx
  webapp/src/services/api/study.ts
  webapp/src/services/api/tasks.ts
Labels: size/XL
