Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-05, with the labels that each got.

#1491 Release v2.13.2 to master
  antarest/__init__.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  docs/CHANGELOG.md
  setup.py
  sonar-project.properties
  tests/worker/test_worker.py
  webapp/package.json
Labels: size/M

#1490 Release v2.13.2 to dev
  antarest/__init__.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  docs/CHANGELOG.md
  setup.py
  sonar-project.properties
  tests/worker/test_worker.py
  webapp/package.json
Labels: size/M

#1475 feat(core): enhance `/version` API endpoint to show dependency versions
  antarest/core/core_blueprint.py
  antarest/core/version_info.py
  tests/core/test_version_info.py
  tests/integration/test_core_blueprint.py
Labels: size/L

#1401 fix(package): do not create symlink for `AntaresWebServer` during package creation
  scripts/package_antares_web.sh
Labels: bug, size/XS

#1498 Issue with "Last day" field in Configuration > General
  antarest/study/business/general_management.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields.tsx
Labels: size/M

#1500 test(api): add unit tests for `GeneralFormFields` validation
  antarest/study/business/general_management.py
  tests/integration/study_data_blueprint/test_config_general.py
Labels: size/M

#1496 Add Hydro matrix dialog
  antarest/core/exceptions.py
  antarest/study/business/allocation_management.py
  antarest/study/business/correlation_management.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
  tests/integration/study_data_blueprint/test_hydro_correlation.py
  tests/study/business/test_allocation_manager.py
  tests/study/business/test_correlation_manager.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Allocation/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Allocation/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Correlation/CorrelationField.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Correlation/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Correlation/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Correlation/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrixDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/InflowStructure.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ViewMatrixButton.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
  webapp/src/components/common/DynamicList.tsx
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/MatrixInput/index.tsx
Labels: size/XL

#1501 Set manual submit on forms
  antarest/study/business/adequacy_patch_management.py
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/index.tsx
  webapp/src/components/common/Form/FormContext.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/Form/utils.ts
  webapp/src/hoc/reactHookFormSupport.tsx
Labels: size/L

#1511 Fix issue in Adequacy Patch form
  antarest/study/business/adequacy_patch_management.py
  antarest/study/business/general_management.py
  antarest/study/business/optimization_management.py
  antarest/study/business/thematic_trimming_management.py
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/Fields.tsx
  webapp/src/components/common/Fieldset.tsx
Labels: size/L

#1505 v2.14 on dev
  antarest/__init__.py
  docs/CHANGELOG.md
  setup.py
  sonar-project.properties
  tests/integration/test_studies_upgrade.py
  webapp/package-lock.json
  webapp/package.json
Labels: size/M

#1517 hotfix/2.14.1 on master
  antarest/__init__.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  docs/CHANGELOG.md
  setup.py
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
Labels: size/S

#1518 feat(ui-map): add map zoom buttons
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapControlButtons.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapGraph.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/utils.ts
Labels: size/L

#1461 fix(command): update_config to support API PUT v1/studies/{uuid}/raw
  antarest/study/storage/rawstudy/io/reader/ini_reader.py
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/json_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/allocation/allocation.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/allocation/area.py
  tests/integration/test_integration_variantmanager_tool.py
  tests/storage/repository/antares_io/reader/test_ini_reader.py
  tests/storage/repository/filesystem/test_ini_file_node.py
  tests/variantstudy/model/command/test_update_config.py
Labels: size/XL

#1526 fix(web): change API response_model to avoid ValidationError
  antarest/study/web/watcher_blueprint.py
Labels: size/XS

#1485 feat(business): add xpansion batch size back office
  antarest/study/business/xpansion_management.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/settings.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/integration/test_integration_xpansion.py
  tests/storage/business/test_xpansion_manager.py
Labels: size/L, xpansion

#1540 test(api): simplify initialization of the database in unit tests
  antarest/tools/admin_lib.py
  tests/conftest.py
  tests/core/test_file_transfer.py
  tests/core/test_maintenance.py
  tests/core/test_tasks.py
  tests/integration/conftest.py
  tests/launcher/test_local_launcher.py
  tests/launcher/test_repository.py
  tests/launcher/test_service.py
  tests/launcher/test_slurm_launcher.py
  tests/login/test_repository.py
  tests/matrixstore/test_matrix_garbage_collector.py
  tests/matrixstore/test_repository.py
  tests/matrixstore/test_service.py
  tests/storage/business/test_watcher.py
  tests/storage/integration/conftest.py
  tests/storage/repository/test_study.py
  tests/variantstudy/conftest.py
  tests/variantstudy/model/test_variant_model.py
Labels: testing story, size/L, api

#1536 Add undo/redo feature on forms
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/Rulesets.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Allocation/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Correlation/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/Form/types.ts
  webapp/src/components/common/Form/useFormApiPlus.ts
  webapp/src/components/common/Form/useFormUndoRedo.ts
  webapp/src/components/wrappers/LoginWrapper.tsx
Labels: size/XL

#1543 feat(ui-config): enable undo/redo in adequacy patch form
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/index.tsx
Labels: size/XS
