Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-11, with the labels that each got.

#1795 chore(api): modify `ThermalConfig` in API example to avoid `ValidationError`
  antarest/study/business/areas/thermal_management.py
Labels: size/XS

#1801 feat(ui-study): translate generate button in command view
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
Labels: front-end, size/XS, feature request

#1786 fix(tasks): resolve incorrect UTC timezone usage for task completion dates in list view
  antarest/core/tasks/service.py
  antarest/launcher/service.py
  antarest/matrixstore/service.py
  tests/core/tasks/test_task_job_service.py
Labels: size/M

#1798 feat(api): add renewable clusters to API endpoints
  antarest/study/business/areas/renewable_management.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_renewables_cluster.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_renewable.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/integration/test_integration.py
  tests/integration/variant_blueprint/test_renewable_cluster.py
Labels: size/XL

#1793 chore: fix typo in the documentation of shell scripts
  scripts/create_db_migration.sh
  scripts/rollback.sh
Labels: documentation, size/XS, back-end

#1804 fix(upgrade): remove tmp files when upgrading
  antarest/study/storage/study_upgrader/__init__.py
  tests/storage/business/test_study_version_upgrader.py
Labels: bug, size/L

#1808 feat(launcher): add information about which user launched a study
  alembic/versions/d495746853cc_add_owner_id_to_jobresult.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  docs/architecture/1-database.md
  scripts/create_db_migration.sh
  scripts/linter.sh
  scripts/pre-start.sh
  scripts/rollback.sh
  scripts/start-dev.sh
  scripts/start.sh
  tests/conftest_db.py
  tests/integration/test_integration.py
  tests/launcher/test_model.py
  tests/launcher/test_repository.py
  tests/launcher/test_service.py
  tests/launcher/test_web.py
  tests/variantstudy/model/test_variant_model.py
Labels: size/XL, api, back-end

#1809 build: 2.15.5
  alembic/versions/d495746853cc_add_owner_id_to_jobresult.py
  antarest/__init__.py
  antarest/core/exceptions.py
  antarest/core/interfaces/cache.py
  antarest/core/tasks/repository.py
  antarest/core/tasks/service.py
  antarest/core/tasks/web.py
  antarest/core/utils/utils.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  antarest/launcher/web.py
  antarest/matrixstore/matrix_garbage_collector.py
  antarest/matrixstore/service.py
  antarest/study/repository.py
  antarest/study/storage/study_upgrader/__init__.py
  antarest/study/storage/utils.py
  antarest/study/storage/variantstudy/model/dbmodel.py
  antarest/study/storage/variantstudy/repository.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/raw_studies_blueprint.py
  docs/CHANGELOG.md
  docs/architecture/1-database.md
  requirements-doc.txt
  scripts/create_db_migration.sh
  scripts/linter.sh
  scripts/pre-start.sh
  scripts/rollback.sh
  scripts/start-dev.sh
  scripts/start.sh
  setup.py
  sonar-project.properties
  tests/conftest_db.py
  tests/core/tasks/test_task_job_service.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
  tests/integration/test_integration.py
  tests/integration/variant_blueprint/test_thermal_cluster.py
  tests/launcher/test_model.py
  tests/launcher/test_repository.py
  tests/launcher/test_service.py
  tests/launcher/test_web.py
  tests/storage/business/test_study_version_upgrader.py
  tests/storage/test_service.py
  tests/study/storage/variantstudy/model/__init__.py
  tests/study/storage/variantstudy/model/test_dbmodel.py
  tests/study/storage/variantstudy/test_snapshot_generator.py
  tests/variantstudy/model/test_variant_model.py
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
  webapp/src/components/App/Studies/HeaderBottom.tsx
  webapp/src/components/common/fieldEditors/SearchFE.tsx
  webapp/src/redux/ducks/studies.ts
  webapp/src/redux/middlewares/localStorageMiddleware.ts
  webapp/src/services/utils/localStorage.ts
Labels: size/XXL

#1791 feat(ui-storages): add storages list view and form
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/AreasTab.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Form.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/utils.ts
  webapp/src/components/App/index.tsx
  webapp/src/components/common/GroupedDataTable/CreateRowDialog.tsx
  webapp/src/components/common/GroupedDataTable/index.tsx
  webapp/src/components/common/fieldEditors/SearchFE.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
Labels: size/XL

#1762 feat(utils): support 7z import for studies, outputs and matrices
  antarest/core/utils/utils.py
  antarest/matrixstore/service.py
  antarest/study/common/studystorage.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/web/studies_blueprint.py
  docs/assets/media/how-to/studies-import-drop-file-dialog.png
  docs/assets/media/how-to/studies-import-main-view.png
  docs/assets/media/how-to/studies-import-studies-list.png
  docs/assets/media/how-to/studies-upgrade-menu_version.png
  docs/how-to/studies-import.md
  docs/how-to/studies-upgrade.md
  docs/user-guide/1-interface.md
  mkdocs.yml
  requirements.txt
  tests/core/utils/__init__.py
  tests/core/utils/test_extract_zip.py
  tests/integration/assets/STA-mini.7z
  tests/integration/assets/matrices.7z
  tests/integration/assets/matrices.zip
  tests/integration/assets/output_adq.7z
  tests/integration/assets/output_adq.zip
  tests/integration/test_integration.py
  tests/storage/business/test_import.py
Labels: size/L

#1815 fix(st-storage): the `initial_level` value must be between 0 and 1
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/variant_blueprint/test_st_storage.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/study/business/areas/test_st_storage_management.py
Labels: bug, size/M, back-end

#1797 test(apidoc): add unit test for apidoc page
  tests/integration/test_apidoc.py
Labels: technical story, size/S

#1807 feat(ui-thermal): update thermal clusters list view and form labels
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
Labels: size/M

#1811 fix(ui): update dynamic areaId segment URL path on area change
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/AreasTab.tsx
Labels: size/S

#1816 fix(ui-tasks): filter deleted studies jobs
  webapp/src/components/App/Tasks/index.tsx
  webapp/src/services/api/study.ts
Labels: size/S

#1819 feat(ui): reduce studies header height
  webapp/src/components/App/Singlestudy/NavHeader/Actions.tsx
  webapp/src/components/App/Singlestudy/NavHeader/index.tsx
  webapp/src/theme.ts
Labels: enhancement, front-end, size/M, feature request

#1820 fix(ui-study): prevent study tasks list to contain all studies tasks
  webapp/src/services/api/study.ts
Labels: size/S

#1817 feat(api-raw): add the `create_missing` flag to allow creating missing files when uploading a file
  antarest/study/service.py
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
Labels: size/L

#1825 feat(ui-areas): add version check for storage tab
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/AreasTab.tsx
Labels: bug, enhancement, front-end, size/M

#1833 docs(rtd): correct the configuration for ReadTheDocs
  readthedocs.yml
  requirements-doc.txt
Labels: size/S

#1832 Hotfix v2.15.6 to master
  antarest/__init__.py
  antarest/study/storage/utils.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  docs/CHANGELOG.md
  readthedocs.yml
  requirements-doc.txt
  setup.py
  sonar-project.properties
  tests/study/storage/variantstudy/test_snapshot_generator.py
  webapp/package-lock.json
  webapp/package.json
Labels: hot, size/L

#1836 feat(api-storage): update initial level field default value
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  tests/study/business/areas/test_st_storage_management.py
  tests/variantstudy/model/command/test_create_st_storage.py
Labels: size/S

#1827 perf(api-study): optimize study overview display in Antares Web
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/factory.py
  antarest/study/storage/rawstudy/raw_study_service.py
  tests/db_statement_recorder.py
  tests/integration/conftest.py
  tests/integration/studies_blueprint/__init__.py
  tests/integration/studies_blueprint/assets/__init__.py
  tests/integration/studies_blueprint/assets/test_comments/raw_study.comments.xml
  tests/integration/studies_blueprint/assets/test_synthesis/raw_study.synthesis.json
  tests/integration/studies_blueprint/assets/test_synthesis/variant_study.synthesis.json
  tests/integration/studies_blueprint/test_comments.py
  tests/integration/studies_blueprint/test_synthesis.py
  tests/integration/test_integration.py
  tests/xml_compare.py
Labels: size/XXL

#1831 fix(xpansion): add missing `separation_parameter` field in the settings
  .github/workflows/compatibility.yml
  README.md
  antarest/core/utils/utils.py
  antarest/study/business/xpansion_management.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/settings.py
  docs/install/0-INSTALL.md
  requirements.txt
  tests/core/test_utils.py
  tests/integration/test_integration_xpansion.py
  tests/storage/business/test_xpansion_manager.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/types.ts
Labels: size/XL
