Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-06, with the labels that each got.

#1452 feat(matrix): improve matrix read/write using NumPy
  antarest/matrixstore/main.py
  antarest/matrixstore/model.py
  antarest/matrixstore/repository.py
  antarest/matrixstore/service.py
  antarest/matrixstore/utils.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/folder_node.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/output_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/link/area/area.py
  antarest/study/storage/variantstudy/model/command/replace_matrix.py
  antarest/study/storage/variantstudy/variant_command_extractor.py
  antarest/tools/cli.py
  antarest/tools/lib.py
  tests/integration/test_integration_variantmanager_tool.py
  tests/matrixstore/conftest.py
  tests/matrixstore/test_repository.py
  tests/matrixstore/test_service.py
  tests/storage/business/test_arealink_manager.py
Labels: size/XXL

#1539 refactor(variant): enhance implementation of variant commands
  antarest/core/persistence.py
  antarest/matrixstore/matrix_garbage_collector.py
  antarest/study/common/studystorage.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/variant_command_extractor.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/tools/lib.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/business/test_variant_study_service.py
  tests/variantstudy/model/test_variant_model.py
  tests/variantstudy/test_command_factory.py
Labels: technical story, size/XL, api, variante

#1553 build: specify the node versions supported
  webapp/.npmrc
  webapp/package.json
Labels: size/XS

#1546 refactor(api-model): improve `transform_name_to_id` implementation for more efficiency
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  tests/storage/repository/filesystem/config/test_utils.py
Labels: technical story, size/L, api

#1562 feat(matrix): improve matrix read/write using NumPy
  antarest/matrixstore/main.py
  antarest/matrixstore/model.py
  antarest/matrixstore/repository.py
  antarest/matrixstore/service.py
  antarest/matrixstore/utils.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/folder_node.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/output_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/link/area/area.py
  antarest/study/storage/variantstudy/model/command/replace_matrix.py
  antarest/study/storage/variantstudy/variant_command_extractor.py
  antarest/tools/cli.py
  antarest/tools/lib.py
  tests/integration/test_integration_variantmanager_tool.py
  tests/matrixstore/conftest.py
  tests/matrixstore/test_repository.py
  tests/matrixstore/test_service.py
  tests/storage/business/test_arealink_manager.py
Labels: size/XXL

#1551 fix(build): fix pyinstaller build
  .github/workflows/deploy.yml
  AntaresWebLinux.spec
  AntaresWebWin.spec
Labels: size/M

#1558 fix(worker): archive worker must be kept alive for processing
  antarest/core/interfaces/eventbus.py
  antarest/core/interfaces/service.py
  antarest/worker/archive_worker.py
  antarest/worker/simulator_worker.py
  antarest/worker/worker.py
  tests/conftest.py
  tests/core/test_tasks.py
  tests/worker/test_archive_worker.py
  tests/worker/test_simulator_worker.py
  tests/worker/test_worker.py
Labels: bug, size/L

#1567 fix(worker): archive worker must be kept alive for processing
  antarest/core/interfaces/eventbus.py
  antarest/core/interfaces/service.py
  antarest/worker/archive_worker.py
  antarest/worker/simulator_worker.py
  antarest/worker/worker.py
  tests/conftest.py
  tests/core/test_tasks.py
  tests/worker/test_archive_worker.py
  tests/worker/test_simulator_worker.py
  tests/worker/test_worker.py
Labels: size/L

#1570 style(ui): correct spelling mistake in webapp code
  webapp/src/components/App/Singlestudy/explore/Modelization/DebugView/StudyDataView/StudyFileView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/DebugView/StudyDataView/StudyMatrixView/StudyMatrixView.tsx
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/FormGenerator/AutoSubmitGenerator.tsx
  webapp/src/components/common/FormGenerator/index.tsx
Labels: bug, Front-End, size/M

#1568 fix(desktop): correct date parsing in localized environment
  antarest/study/storage/utils.py
  antarest/worker/archive_worker.py
  resources/deploy/README.md
Labels: size/L

#1572 fix(matrix): check invalid params and empty matrix in matrix update
  antarest/core/exceptions.py
  antarest/launcher/adapters/local_launcher/local_launcher.py
  antarest/matrixstore/business/matrix_editor.py
  antarest/matrixstore/repository.py
  antarest/matrixstore/service.py
  antarest/study/business/matrix_management.py
  antarest/study/business/utils.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/filestudytree.py
  antarest/study/storage/variantstudy/model/command/create_link.py
  tests/integration/study_data_blueprint/test_edit_matrix.py
  tests/integration/test_integration.py
  tests/launcher/test_local_launcher.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/repository/filesystem/root/input/hydro/common/capacity/test_capacity.py
  tests/study/business/test_matrix_management.py
Labels: size/XXL

#1582 fix(model): raise an error if the "about-the-study/parameters.ini" file is missing in the ZIP file
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  tests/storage/repository/filesystem/config/test_files.py
Labels: size/M

#1580 Fix Properties Form
  antarest/study/business/areas/__init__.py
  antarest/study/business/areas/hydro_management.py
  antarest/study/business/areas/properties_management.py
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/general_management.py
  antarest/study/business/table_mode_management.py
  antarest/study/business/utils.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/PropertiesForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/utils.ts
  webapp/src/components/common/fieldEditors/ColorPickerFE/index.tsx
Labels: size/XXL

#1590 fix(error): improve error handling with enhanced error message
  antarest/main.py
Labels: size/M

#1592 feat(common): display a snackbar error when async default values failed in Form
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/Form/types.ts
  webapp/src/components/common/FormTable/index.tsx
Labels: size/M

#1608 fix(filesystem): correct the handling of default matrices in `InputSeriesMatrix` node
  antarest/study/storage/rawstudy/model/filesystem/common/area_matrix_list.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/load/load.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/solar/solar.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/wind/wind.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/ts_numbers/ts_numbers.py
  antarest/study/storage/variantstudy/business/command_extractor.py
  tests/storage/repository/filesystem/root/input/hydro/common/capacity/test_capacity.py
  tests/storage/repository/filesystem/root/input/hydro/series/area/test_area.py
  webapp/src/components/common/Form/index.tsx
Labels: size/XL

#1606 build(launcher): use Antares-Launcher v1.3.0 to preserve "output"
  requirements.txt
Labels: size/XS, xpansion

#1605 fix(api): resolve version display issue in Desktop's `/version` endpoint
  antarest/core/version_info.py
  tests/core/test_version_info.py
Labels: size/M

#1615 fix(i18n): wrong translations and add missing keys
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/common/OutputFilters.tsx
Labels: size/S

#1618 fix(st-storage): replace inflow.txt by inflows.txt according to the changing doc
  antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/area/st_storage/st_storage.py
  antarest/study/storage/variantstudy/business/matrix_constants/st_storage/series.py
  docs/CHANGELOG.md
Labels: size/S

#1622 fix(variant): get synthesis now also works for level 2+ variants
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/integration/test_integration.py
Labels: size/S

#1621 fix(results): refresh study outputs when job completed and add back button
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/common/ButtonBack.tsx
  webapp/src/components/common/PropertiesView.tsx
  webapp/src/redux/ducks/studySyntheses.ts
  webapp/src/services/webSockets.ts
Labels: size/M

#1577 feature(api): add support for Microsoft Office documents in API
  antarest/core/swagger.py
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/assets/STA-mini.zip
  tests/integration/assets/__init__.py
  tests/integration/assets/config.template.yml
  tests/integration/assets/launcher_mock.sh
  tests/integration/conftest.py
  tests/integration/raw_studies_blueprint/__init__.py
  tests/integration/raw_studies_blueprint/assets/__init__.py
  tests/integration/raw_studies_blueprint/assets/user/bad/corrupted.json
  tests/integration/raw_studies_blueprint/assets/user/folder/example.csv
  tests/integration/raw_studies_blueprint/assets/user/folder/example.docx
  tests/integration/raw_studies_blueprint/assets/user/folder/example.json
  tests/integration/raw_studies_blueprint/assets/user/folder/example.odp
  tests/integration/raw_studies_blueprint/assets/user/folder/example.ods
  tests/integration/raw_studies_blueprint/assets/user/folder/example.odt
  tests/integration/raw_studies_blueprint/assets/user/folder/example.pdf
  tests/integration/raw_studies_blueprint/assets/user/folder/example.pptx
  tests/integration/raw_studies_blueprint/assets/user/folder/example.tsv
  tests/integration/raw_studies_blueprint/assets/user/folder/example.txt
  tests/integration/raw_studies_blueprint/assets/user/folder/example.xlsx
  tests/integration/raw_studies_blueprint/assets/user/unknown/example.dat
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/integration/study_data_blueprint/conftest.py
  tests/integration/test_studies_upgrade.py
Labels: size/XL

#1620 fix(service): set public mode to `NONE` and assign user groups to the study during copying
  antarest/study/storage/rawstudy/raw_study_service.py
  tests/storage/business/test_raw_study_service.py
Labels: size/XS

#1619 fix(service): set public mode to `NONE` and assign user groups to the study during import
  antarest/study/service.py
  tests/storage/business/test_import.py
Labels: size/XS
