Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-02, with the labels that each got.

#1282 feat(launcher): integrate Antares Solver v8.5.0-rc3.
  antarest/study/model.py
  antarest/study/service.py
Labels: size/M

#1279 feat(ui): add tooltips to collapsed main menu
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/wrappers/MenuWrapper/index.tsx
Labels: size/L

#1284 feat(github): add feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/S

#1283 feat(github): add bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/M

#1273 fix(ui-wording): correct french translations
  webapp/public/locales/fr/main.json
Labels: size/M

#1290 feat(ui-results): add download button on results matrix
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/utils/matrixUtils.ts
Labels: size/M

#1297 feat(ui-redux): add menu state in local storage
  webapp/src/components/wrappers/MenuWrapper/index.tsx
  webapp/src/redux/ducks/ui.ts
  webapp/src/redux/middlewares/localStorageMiddleware.ts
  webapp/src/redux/selectors.ts
  webapp/src/services/utils/localStorage.ts
Labels: size/M

#1293 feat(api,tablemode,ui-tablemode): add renewable and binding constraint type
  antarest/study/business/binding_constraint_management.py
  antarest/study/business/table_mode_management.py
  tests/integration/test_integration.py
  tests/integration/test_integration_table_mode_manager.py
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/utils.ts
Labels: size/XL

#1292 feat(ui-map): add layers and districts french translations
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/CreateDistrictDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/UpdateDistrictDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/CreateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/UpdateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/index.tsx
Labels: size/M

#1301 fix(api): unexpected behavior when launching simulations
  antarest/core/cache/business/local_chache.py
  antarest/core/config.py
  antarest/core/interfaces/service.py
  antarest/core/maintenance/service.py
  antarest/eventbus/service.py
  antarest/launcher/adapters/local_launcher/local_launcher.py
  antarest/launcher/adapters/log_manager.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/study/storage/rawstudy/model/filesystem/root/filestudytree.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/worker/archive_worker.py
  antarest/worker/simulator_worker.py
  antarest/worker/worker.py
  tests/conftest.py
  tests/core/test_tasks.py
  tests/eventbus/test_service.py
  tests/worker/test_worker.py
Labels: size/L

#1269 fix(storage): ignore zipped output if an unzipped version exists
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/rawstudy/io/reader/ini_reader.py
  antarest/study/storage/rawstudy/model/filesystem/config/exceptions.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/factory.py
  antarest/study/storage/rawstudy/model/helpers.py
  antarest/study/storage/variantstudy/business/command_extractor.py
  tests/storage/business/assets/__init__.py
  tests/storage/business/assets/test_output_zip_not_zipped.zip
  tests/storage/business/test_arealink_manager.py
  tests/storage/business/test_timeseries_config_manager.py
  tests/storage/business/test_xpansion_manager.py
  tests/storage/rawstudies/test_factory.py
  tests/storage/repository/antares_io/reader/test_ini_reader.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/storage/test_model.py
  tests/storage/test_service.py
  tests/variantstudy/model/command/test_manage_district.py
  tests/variantstudy/model/command/test_remove_link.py
Labels: size/XXL

#1263 fix(study-upgrader): add a fail-safe rollback to the upgrade process
  antarest/core/tasks/service.py
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/storage/study_version_upgrader.py
  antarest/study/web/studies_blueprint.py
  antarest/tools/cli.py
  tests/core/test_tasks.py
  tests/integration/test_studies_upgrade.py
  tests/storage/business/assets/broken_study_720.zip
  tests/storage/business/test_study_version_upgrader.py
  tests/storage/test_service.py
  tests/study/storage/__init__.py
  tests/study/storage/test_study_version_upgrader.py
  tests/worker/test_worker.py
Labels: size/XXL

#1311 ci(github): use ubuntu-20.04 instead of ubuntu-22.04 (latest)
  .github/workflows/compatibility.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
Labels: size/S

#1313 feat(ui-model,api): update renewable form
  antarest/study/business/hydro_management.py
  antarest/study/business/renewable_management.py
  antarest/study/business/table_mode_management.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/utils.ts
Labels: size/XL

#1323 build: update package.json and remove unused files
  webapp/.gitignore
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantDialog.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantModal/style.ts
  webapp/src/components/App/Singlestudy/HomeView/InformationView/index.tsx
  webapp/src/components/App/Singlestudy/PropertiesDialog.tsx
  webapp/src/components/App/Singlestudy/PropertiesDialog/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/common.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/DebugView/StudyDataView/utils/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/utils.ts
  webapp/src/components/common/ButtonLoader.tsx
  webapp/src/components/common/EditableMatrix/utils.test.ts
  webapp/src/components/common/FormGenerator/AutoSubmitGenerator.tsx
  webapp/src/components/common/FormGenerator/index.tsx
  webapp/src/components/common/SnackErrorMessage.tsx
  webapp/src/components/common/TagTextInput.tsx
  webapp/src/i18n.ts
  webapp/src/index.tsx
  webapp/src/reportWebVitals.ts
  webapp/src/services/api/client.ts
  webapp/src/services/api/file.ts
  webapp/src/services/api/matrix.ts
  webapp/src/services/api/study.ts
  webapp/src/services/api/xpansion.ts
  webapp/src/services/utils/index.ts
  webapp/src/setupTests.ts
  webapp/src/types/i18next.d.ts
Labels: size/XL

#1327 build: update `requirements.txt` and correct mypy issue
  antarest/core/logging/utils.py
  requirements.txt
Labels: size/M

#1317 feat(model,api): update thermal form
  antarest/study/business/table_mode_management.py
  antarest/study/business/thermal_management.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/utils.ts
Labels: size/XL

#1326 fix(ui-studies): remove regex support in search field
  webapp/src/utils/studiesUtils.ts
Labels: size/XS

#1328 feat(storage): add v8.5 template
  antarest/study/business/optimization_management.py
  antarest/study/model.py
  antarest/study/storage/rawstudy/model/filesystem/root/settings/generaldata.py
  resources/empty_study_850.zip
  tests/integration/test_integration.py
  tests/storage/business/test_raw_study_service.py
Labels: size/L

#1340 fix(ui-hydro): add path for ror matrix in hydro
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
Labels: size/XS

#1349 feat(study): make projection in XpansionSensitivitySettings optional + tests
  antarest/study/business/xpansion_management.py
  tests/storage/business/test_xpansion_manager.py
Labels: size/M

#1347 v2.12.2
  antarest/__init__.py
  antarest/core/logging/utils.py
  antarest/launcher/extensions/adequacy_patch/resources/post-processing-legacy.R
  antarest/launcher/extensions/adequacy_patch/resources/post-processing.R
  requirements.txt
  setup.py
  sonar-project.properties
  webapp/package.json
Labels: size/M

#1361 feat(adequacy-patch): consider `excluded_areas` before launching and cleanup output
  antarest/launcher/extensions/adequacy_patch/resources/post-processing-legacy.R
  antarest/launcher/extensions/adequacy_patch/resources/post-processing.R
Labels: size/XS
