Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-03, with the labels that each got.

#1364 feat(ui-hydro): update hydro matrices styles
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
Labels: size/L

#1363 feat(storage): add missing folders in empty_study_850.zip
  resources/empty_study_613.zip
  resources/empty_study_700.zip
  resources/empty_study_710.zip
  resources/empty_study_720.zip
  resources/empty_study_803.zip
  resources/empty_study_810.zip
  resources/empty_study_820.zip
  resources/empty_study_830.zip
  resources/empty_study_840.zip
  resources/empty_study_850.zip
  resources/templates/empty_study_840.zip
  tests/test_resources.py
Labels: size/M

#1370 Add matrices float handling
  webapp/src/components/common/EditableMatrix/index.tsx
Labels: size/XS

#1356 feat(ui-hydro): update hydro matrices
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
Labels: size/S

#1380 fix(api-slurm): avoid raising FileNotFound error when retrieving outputs
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/study/storage/patch_service.py
  tests/launcher/test_slurm_launcher.py
  tests/storage/business/test_patch_service.py
Labels: size/XL

#1386 feat(ui-matrix): update "Time" column and add index row headers
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/EditableMatrix/utils.ts
Labels: UI, size/M, feature request

#1393 Release v2.13.0 on dev
  antarest/__init__.py
  antarest/eventbus/main.py
  docs/CHANGELOG.md
Labels: size/M

#1390 fix(ui): fix typo on error page
  webapp/src/components/common/loaders/GlobalPageLoadingError.tsx
Labels: size/XS

#1384 fix(matrix): correct frequency some matrices
  antarest/study/storage/rawstudy/model/filesystem/matrix/date_serializer.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/output_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/common/capacity/capacity.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/series/area/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/binding_const.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/link.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/links.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/set.py
  tests/storage/repository/filesystem/matrix/output_series_matrix_test.py
  tests/storage/repository/filesystem/matrix/test_matrix_node.py
  tests/storage/repository/filesystem/root/__init__.py
  tests/storage/repository/filesystem/root/input/__init__.py
  tests/storage/repository/filesystem/root/input/hydro/__init__.py
  tests/storage/repository/filesystem/root/input/hydro/common/__init__.py
  tests/storage/repository/filesystem/root/input/hydro/common/capacity/__init__.py
  tests/storage/repository/filesystem/root/input/hydro/common/capacity/test_capacity.py
  tests/storage/repository/filesystem/root/input/hydro/series/__init__.py
  tests/storage/repository/filesystem/root/input/hydro/series/area/__init__.py
  tests/storage/repository/filesystem/root/input/hydro/series/area/test_area.py
  tests/storage/repository/filesystem/root/output/__init__.py
  tests/storage/repository/filesystem/root/output/simulation/__init__.py
  tests/storage/repository/filesystem/root/output/simulation/mode/__init__.py
  tests/storage/repository/filesystem/root/output/simulation/mode/common/__init__.py
  tests/storage/repository/filesystem/root/output/simulation/mode/common/test_area.py
  tests/storage/repository/filesystem/root/output/simulation/mode/common/test_binding_const.py
  tests/storage/repository/filesystem/root/output/simulation/mode/common/test_link.py
  tests/storage/repository/filesystem/root/output/simulation/mode/common/test_set.py
Labels: bug, size/XL, api

#1408 feat(ui): add @total-typescript/ts-reset lib and tsUtils
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Settings/index.tsx
  webapp/src/types/reset.d.ts
  webapp/src/utils/tsUtils.ts
Labels: size/S

#1417 fix(launcher): improved reliability of task state retrieval sent to SLUM
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  requirements.txt
Labels: size/M

#1419 fix(desktop): use Antares Solver v8.5.0 for Antares Web Desktop version
  scripts/package_antares_web.sh
Labels: size/M

#1431 feat: standardize log messsage formats
  antarest/core/logging/utils.py
  antarest/gui.py
  antarest/main.py
  antarest/singleton_services.py
  antarest/utils.py
Labels: size/L
