Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-08, with the labels that each got.

#1680 feat(ui-i18n): add missing adequacy patch translations
  webapp/public/locales/fr/main.json
Labels: size/XS

#1677 fix(ui-api): resolve Area deletion & Layers/Districts UI modification issues
  antarest/core/exceptions.py
  antarest/study/business/area_management.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/index.tsx
  webapp/src/components/common/FormTable/Table.tsx
  webapp/src/redux/ducks/studyMaps.ts
Labels: size/L

#1682 fix(log-parser): simplify parsing and make it accurate
  antarest/launcher/adapters/abstractlauncher.py
  antarest/launcher/adapters/log_parser.py
  tests/launcher/assets/__init__.py
  tests/launcher/assets/log_parser/.gitignore
  tests/launcher/assets/log_parser/simulation.error-big.history.json
  tests/launcher/assets/log_parser/simulation.error-big.log
  tests/launcher/assets/log_parser/simulation.error.history.json
  tests/launcher/assets/log_parser/simulation.error.log
  tests/launcher/assets/log_parser/simulation.fatal.history.json
  tests/launcher/assets/log_parser/simulation.fatal.log
  tests/launcher/assets/log_parser/simulation.nominal-big.history.json
  tests/launcher/assets/log_parser/simulation.nominal.history.json
  tests/launcher/assets/log_parser/simulation.nominal.log
  tests/launcher/test_log_parser.py
  tests/storage/integration/data/simulation_log.py
Labels: size/XXL

#1688 fix(variant): enhance `VariantCommandsExtractor` for Renewable Clusters and Short-Term Storage
  antarest/study/storage/variantstudy/variant_command_extractor.py
Labels: technical story, size/XS

#1684 fix(xpansion): correct field names and types in Xpansion settings
  antarest/study/business/xpansion_management.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/settings.py
  tests/integration/test_integration_xpansion.py
  tests/storage/business/test_xpansion_manager.py
Labels: size/L

#1673 fix(st-storage): fixing archived study configuration reading for short-term storages
  antarest/core/utils/utils.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  tests/storage/repository/filesystem/config/test_config_files.py
Labels: size/M

#1671 fix(launcher): fixing launcher versions display and API endpoint for solver versions
  antarest/core/config.py
  antarest/launcher/service.py
  antarest/launcher/web.py
  antarest/study/web/studies_blueprint.py
  tests/launcher/test_service.py
  tests/launcher/test_web.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/LauncherDialog.tsx
  webapp/src/services/api/study.ts
Labels: size/L

#1665 fix(st-storage): update "group" parameter values for Short-Term Storage
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  tests/variantstudy/model/command/test_create_st_storage.py
Labels: size/L

#1689 fix(ui-common): prevent null values for string cells in HandsonTable component
  webapp/src/components/common/Handsontable.tsx
Labels: size/S

#1674 fix(table-mode): fixes the reading of UI information in the case where the study has only one area
  antarest/study/business/area_management.py
  antarest/study/business/table_mode_management.py
Labels: size/L

#1693 fix(variant): fixed TS deletion of renewable clusters and short-term storage
  antarest/study/business/areas/renewable_management.py
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_st_storage.py
  tests/integration/variant_blueprint/test_renewable_cluster.py
  tests/variantstudy/model/command/test_create_area.py
  tests/variantstudy/model/command/test_remove_renewables_cluster.py
Labels: bug, hot, size/XXL

#1687 feat(ui-study): enhance study upgrade dialog
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/NavHeader.tsx
  webapp/src/components/App/Singlestudy/NavHeader/Actions.tsx
  webapp/src/components/App/Singlestudy/NavHeader/ActionsMenu.tsx
  webapp/src/components/App/Singlestudy/NavHeader/Details.tsx
  webapp/src/components/App/Singlestudy/NavHeader/index.tsx
  webapp/src/components/App/Singlestudy/UpgradeDialog.tsx
  webapp/src/components/App/Studies/StudyCard.tsx
  webapp/src/services/api/study.ts
  webapp/src/theme.ts
Labels: size/XXL

#1633 feat(ui-common): add GroupedDataTable
  .github/workflows/compatibility.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  docs/install/0-INSTALL.md
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/common/DynamicDataTable/TableRowGroup.tsx
  webapp/src/components/common/DynamicDataTable/TableRowItem.tsx
  webapp/src/components/common/DynamicDataTable/TableToolbar.tsx
  webapp/src/components/common/DynamicDataTable/index.tsx
  webapp/src/components/common/DynamicDataTable/utils.ts
  webapp/src/components/common/GroupedDataTable/CreateRowDialog.tsx
  webapp/src/components/common/GroupedDataTable/index.tsx
  webapp/src/theme.ts
Labels: size/XL

#1698 feat(ui): remove patch number in version list when it's equal to 0
  webapp/src/services/utils/index.ts
Labels: front-end, size/S

#1697 feat(st-storage): add ST Storage API endpoints
  antarest/core/exceptions.py
  antarest/study/business/st_storage_manager.py
  antarest/study/business/utils.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/area/list.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/area/area.py
  antarest/study/storage/variantstudy/model/command/create_st_storage.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/study/business/conftest.py
  tests/study/business/test_st_storage_manager.py
  tests/variantstudy/model/command/test_create_st_storage.py
Labels: size/XXL

#1708 fix(model): wrong frequency for `hydro energy credits` matrices
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/common/capacity/capacity.py
  tests/storage/repository/filesystem/root/input/hydro/common/capacity/test_capacity.py
Labels: size/S
