Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-07, with the labels that each got.

#1632 feat(service): set the user's name as author in `study.antares` when creating a study
  antarest/study/service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/utils.py
  antarest/study/storage/variantstudy/variant_command_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/variant_blueprint.py
  tests/integration/test_integration.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/test_service.py
  tests/variantstudy/model/test_variant_model.py
Labels: size/L

#1636 refactor(command): improve implementation of area management
  antarest/study/business/area_management.py
  antarest/study/storage/variantstudy/model/command/create_area.py
Labels: technical story, size/M, back-end

#1635 feat(matrix): improve unexpected exception error message
  antarest/study/storage/variantstudy/model/command/icommand.py
Labels: size/XS, back-end

#1638 test: improve fixtures in unit tests for better reuse
  tests/integration/test_studies_upgrade.py
  tests/integration/utils.py
  tests/storage/business/test_arealink_manager.py
  tests/variantstudy/assets/__init__.py
  tests/variantstudy/assets/empty_study_720.zip
  tests/variantstudy/conftest.py
  tests/variantstudy/model/command/test_create_cluster.py
  tests/variantstudy/model/command/test_create_link.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_replace_matrix.py
  tests/variantstudy/model/test_variant_model.py
Labels: technical story, testing story, size/L

#1637 docs: correct and improve the "Variant Manager" documentation
  LICENSE
  antarest/study/storage/variantstudy/business/utils.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  docs/user-guide/2-variant_manager.md
  mkdocs.yml
Labels: documentation, size/L

#1639 refactor(command): rename "cluster" as "thermal cluster"
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  antarest/study/storage/variantstudy/variant_command_extractor.py
  tests/integration/test_integration.py
  tests/variantstudy/test_command_factory.py
Labels: technical story, size/M, back-end

#1647 refactor: refactoring of unit tests and Model improvement
  antarest/core/tasks/model.py
  antarest/launcher/service.py
  tests/conftest.py
  tests/storage/conftest.py
  tests/storage/integration/test_exporter.py
Labels: technical story, testing story, size/L

#1652 fix(packaging): update the packaging script to use Antares Solver v8.6.1
  scripts/package_antares_web.sh
Labels: size/XS

#1656 fix(export): ZIP outputs are now uncompressed before export
  antarest/study/storage/utils.py
  tests/storage/integration/test_exporter.py
Labels: size/S

#1660 Fix login submit issue
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/Form/useFormApiPlus.ts
  webapp/src/components/common/Form/utils.ts
  webapp/src/components/wrappers/LoginWrapper.tsx
Labels: size/L
