Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-04, with the labels that each got.

#1437 Fix table size
  antarest/study/business/table_mode_management.py
  antarest/study/web/study_data_blueprint.py
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/tabs/Table.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/index.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/Form/useAsyncDefaultValues.ts
  webapp/src/components/common/FormTable/index.tsx
Labels: size/M

#1439 fix(common): field array change doesn't trigger auto submit
  webapp/src/components/common/Form/index.tsx
Labels: size/M

#1444 feat(ui): update react-hook-form lib and use the new API
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/App/Studies/MoveStudyDialog.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/Form/types.ts
  webapp/src/components/common/Form/useAsyncDefaultValues.ts
  webapp/src/components/common/FormGenerator/index.tsx
  webapp/src/components/common/FormTable/index.tsx
  webapp/src/hoc/reactHookFormSupport.tsx
Labels: size/L

#1445 feat(api): spacial correlation matrix
  antarest/core/exceptions.py
  antarest/study/business/correlation_management.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/remove_area.py
  antarest/study/web/study_data_blueprint.py
  examples/studies/STA-mini.zip
  tests/integration/study_data_blueprint/test_hydro_correlation.py
  tests/storage/business/test_arealink_manager.py
  tests/study/business/test_correlation_manager.py
  tests/variantstudy/conftest.py
  tests/variantstudy/model/command/test_remove_area.py
Labels: size/XXL

#1449 fix(api): correct the spatial correlation form update
  antarest/study/business/correlation_management.py
  tests/integration/study_data_blueprint/test_hydro_correlation.py
Labels: size/M

#1343 fix(log): reduce size of Antares Web Worker log file
  antarest/core/logging/utils.py
  antarest/worker/archive_worker_service.py
  tests/worker/test_archive_worker_service.py
Labels: size/L

#1456 fix(ui-thermal): remove duplicate fields
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
Labels: size/S

#1467 test(hydro): improve hydro allocation unit tests
  tests/integration/__init__.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
  tests/integration/test_integration.py
  tests/integration/utils.py
Labels: testing story, size/L, api

#1477 fix(api): fix uncaught exceptions in slurm launcher loop
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
Labels: size/S
