Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-01, with the labels that each got.

#1207 fix changes on study.antares file when calling study_version_upgrader
  antarest/study/storage/study_version_upgrader.py
  tests/storage/business/assets/little_study_700.zip
  tests/storage/business/assets/little_study_720.zip
  tests/storage/business/test_study_version_upgrader.py
Labels: size/S

#1186 build: use simulator v8.4.0 as default
  scripts/package_antares_web.sh
Labels: size/XS

#1217 fix(storage/ui): set correct energy cost variable paths
  antarest/study/business/table_mode_management.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  tests/integration/test_integration.py
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/PropertiesForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/utils.ts
Labels: size/L

#1198 v2.11.1
  antarest/__init__.py
  antarest/core/config.py
  antarest/core/exceptions.py
  antarest/core/utils/utils.py
  antarest/launcher/service.py
  antarest/matrixstore/service.py
  antarest/study/business/area_management.py
  antarest/study/business/table_mode_management.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/auto_archive_service.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/binding_const.py
  antarest/study/storage/study_version_upgrader.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/create_link.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/study_data_blueprint.py
  resources/application.yaml
  scripts/package_antares_web.sh
  setup.py
  sonar-project.properties
  tests/integration/test_integration.py
  tests/storage/business/assets/little_study_700.zip
  tests/storage/business/assets/little_study_720.zip
  tests/storage/business/test_arealink_manager.py
  tests/storage/business/test_autoarchive_service.py
  tests/storage/business/test_export.py
  tests/storage/business/test_study_version_upgrader.py
  tests/variantstudy/model/command/test_create_link.py
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/PropertiesForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/DebugView/StudyDataView/StudyMatrixView/StudyMatrixView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/utils.ts
  webapp/src/components/common/EditableMatrix/utils.test.ts
  webapp/src/components/common/EditableMatrix/utils.ts
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/dialogs/BasicDialog.tsx
Labels: size/XXL

#1219 feat(ui-map): refacto map and add layers
  antarest/core/exceptions.py
  antarest/study/business/area_management.py
  antarest/study/web/study_data_blueprint.py
  webapp/src/assets/mapbackground.png
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/AreaPropsView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/PropertiesForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/BindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkPropsView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/AreaConfig.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/AreaLink.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/AreaLinks.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/DeleteAreaDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/CreateAreaDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/GraphView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/LinksView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/CreateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/EditLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapGraph.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapHeader.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapPropsView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Node.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/NodeView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/PanelView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/utils.ts
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/hooks/useStudyData.ts
  webapp/src/components/App/index.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/utils/UsePromiseCond.tsx
  webapp/src/redux/ducks/index.ts
  webapp/src/redux/ducks/studies.ts
  webapp/src/redux/ducks/studyMaps.ts
  webapp/src/redux/ducks/studySyntheses.ts
  webapp/src/redux/hooks/useStudyMaps.ts
  webapp/src/redux/hooks/useStudySynthesis.ts
  webapp/src/redux/selectors.ts
  webapp/src/redux/utils.ts
  webapp/src/services/api/study.ts
  webapp/src/services/api/studydata.ts
  webapp/src/services/utils/index.ts
  webapp/src/services/webSockets.ts
Labels: size/XXL

#1221 Add properties menu to study listing card
  webapp/src/components/App/Singlestudy/PropertiesDialog/index.tsx
  webapp/src/components/App/Studies/StudyCard.tsx
  webapp/src/redux/ducks/studies.ts
  webapp/src/redux/ducks/studySyntheses.ts
Labels: size/L

#1222 feat(ui-config,api): add scenario builder form dialog
  antarest/core/utils/dict.py
  antarest/study/business/scenario_builder_management.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/business/command_reverter.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_scenario_builder.py
  antarest/study/web/study_data_blueprint.py
  docs/user-guide/2-variant_manager.md
  tests/integration/test_integration.py
  tests/variantstudy/test_command_factory.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/ConfigContext.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/Rulesets.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/tabs/Table.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/tabs/Thermal.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/index.tsx
  webapp/src/components/App/Singlestudy/explore/common/ListElement.tsx
  webapp/src/components/common/Form/utils.ts
  webapp/src/components/common/FormTable/index.tsx
  webapp/src/components/common/PropertiesView.tsx
  webapp/src/components/common/SplitLayoutView.tsx
  webapp/src/components/common/fieldEditors/SearchFE.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/redux/hooks/useStudySynthesis.ts
Labels: size/XXL

#1227 feat(ui-links): add links direction
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkMatrixView.tsx
Labels: size/S

#1231 fix(worker): clean up future list when task is done
  antarest/worker/worker.py
Labels: size/M

#1232 fix(auth): role runner and writer mixup
  antarest/core/roles.py
  tests/integration/test_integration.py
  webapp/src/common/types.ts
Labels: size/S

#1234 feat(ui): format scenarii matrices column names
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/BindingConstForm.tsx
  webapp/src/components/common/EditableMatrix/index.tsx
Labels: size/S

#1235 fix(storage): migration to 800 and 810
  antarest/study/storage/study_version_upgrader.py
  tests/storage/business/test_study_version_upgrader.py
Labels: size/XS

#1238 fix: clear snapshot when upgrading variant study
  antarest/study/service.py
Labels: size/XS

#1237 fix(ui-map): prevent duplicate layers and districts on creation/update
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/CreateDistrictDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/UpdateDistrictDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/CreateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/UpdateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapHeader.tsx
  webapp/src/redux/ducks/studyMaps.ts
  webapp/src/redux/selectors.ts
Labels: size/L

#1239 fix(ui-map): prevent duplicate layers and districts on create/update
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/CreateDistrictDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/CreateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/UpdateLayerDialog.tsx
Labels: size/M

#1243 fix(ui-maps): empty page
  webapp/src/common/types.ts
  webapp/src/redux/ducks/studyMaps.ts
Labels: size/S

#1241 feat(ui-common): add doc link on subsections
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Load.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/MiscGen.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Reserve.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Solar.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Wind.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/BindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/index.tsx
  webapp/src/components/common/DocLink.tsx
Labels: size/L

#1244 Prevent default workspace scan
  antarest/core/exceptions.py
  antarest/study/storage/rawstudy/watcher.py
  tests/storage/business/test_watcher.py
Labels: size/S

#1240 feat(api-websocket): Better handle the events in eventbus braodcasting
  antarest/core/interfaces/eventbus.py
  antarest/core/model.py
  antarest/core/permissions.py
  antarest/core/tasks/service.py
  antarest/eventbus/business/redis_eventbus.py
  antarest/eventbus/main.py
  antarest/eventbus/service.py
  antarest/eventbus/web.py
  antarest/launcher/adapters/abstractlauncher.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/service.py
  antarest/study/service.py
  antarest/study/storage/utils.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/worker/worker.py
  tests/core/test_file_transfer.py
  tests/core/test_tasks.py
  tests/eventbus/test_local_eventbus.py
  tests/eventbus/test_redis_event_bus.py
  tests/eventbus/test_service.py
  tests/eventbus/test_websocket_manager.py
  tests/worker/test_worker.py
Labels: size/XL

#1251 fix(ui-study): remove the create command button
  webapp/src/components/App/Singlestudy/Commands/Edition/AddCommandDialog.tsx
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
Labels: size/L

#1258 feat(ui-commands): add confirm dialog on delete command
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
Labels: size/M

#1260 fix(storage/variant): create filestudy config with correct output path
  antarest/study/storage/variantstudy/variant_study_service.py
Labels: size/XS

#1266 feat(redux): extend left menu by default
  webapp/src/redux/ducks/ui.ts
Labels: size/XS

#1271 fix(ui-wording): correct wording of user messages
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/PropertiesForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkMatrixView.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
  webapp/src/components/common/MatrixInput/MatrixAssignDialog.tsx
Labels: size/L

#1270 feat(ui-study): add text ellipsis on study name
  webapp/src/components/App/Singlestudy/NavHeader.tsx
Labels: size/M
