Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-10, with the labels that each got.

#1751 feat(ui-results): move filters on top of matrices
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/SelectionDrawer.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
Labels: enhancement, front-end, size/XL

#1754 fix(ui-xpansion): display issue in form
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
Labels: size/S

#1753 v2.15.1 on master
  antarest/__init__.py
  antarest/study/web/raw_studies_blueprint.py
  docs/CHANGELOG.md
  setup.py
  sonar-project.properties
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/integration/test_integration_xpansion.py
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/SelectionDrawer.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/utils.ts
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
Labels: size/XL

#1702 feat(model): handling binding constraints frequency in study configuration parsing
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/binding_constraint.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/bindingconstraints/bindingcontraints.py
  antarest/study/storage/variantstudy/business/command_extractor.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/storage/test_model.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/model/command/test_remove_cluster.py
Labels: size/L

#1727 feat(api): add endpoint get_nb_cores
  antarest/core/config.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  antarest/launcher/web.py
  resources/application.yaml
  resources/deploy/config.prod.yaml
  resources/deploy/config.yaml
  tests/conftest_db.py
  tests/core/assets/__init__.py
  tests/core/assets/config/application-2.14.yaml
  tests/core/assets/config/application-2.15.yaml
  tests/core/test_config.py
  tests/integration/assets/config.template.yml
  tests/integration/launcher_blueprint/test_launcher_local.py
  tests/launcher/test_local_launcher.py
  tests/launcher/test_service.py
  tests/launcher/test_slurm_launcher.py
  tests/study/business/conftest.py
  tests/test_resources.py
Labels: size/XXL

#1736 feat(st-storage): allow all parameters in endpoint for short term storage creation
  antarest/study/business/st_storage_manager.py
  antarest/study/business/utils.py
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_st_storage.py
Labels: size/L

#1766 fix(api-raw): correct the `/studies/{uuid}/raw` endpoint to return "text/plain" content for matrices
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/storage/web/test_studies_bp.py
Labels: size/M

#1533 feat(storage): make study_upgrader much faster
  antarest/study/storage/study_upgrader/__init__.py
Labels: size/L

#1767 v2.15.3
  antarest/__init__.py
  antarest/study/storage/study_upgrader/__init__.py
  antarest/study/web/raw_studies_blueprint.py
  docs/CHANGELOG.md
  setup.py
  sonar-project.properties
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/storage/web/test_studies_bp.py
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/index.tsx
Labels: size/L, release

#1769 fix(raw): fix HTTP exception when going on debug view
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
Labels: size/S

#1773 fix(ui-study): remove popup to prevent close after variant creation
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantDialog.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/FormTable/index.tsx
  webapp/src/components/common/dialogs/FormDialog.tsx
Labels: bug, front-end, size/L

#1761 feat(launcher): add information about which user launched a study
  alembic/versions/d495746853cc_add_owner_id_to_jobresult.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  docs/architecture/1-database.md
  scripts/create_db_migration.sh
  scripts/linter.sh
  scripts/pre-start.sh
  scripts/rollback.sh
  scripts/start-dev.sh
  scripts/start.sh
  tests/conftest_db.py
  tests/integration/test_integration.py
  tests/launcher/test_model.py
  tests/launcher/test_repository.py
  tests/launcher/test_service.py
  tests/launcher/test_web.py
Labels: size/XL

#1779 fix(results-ui): display results for a specific year
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/utils.ts
Labels: bug, front-end, hot, size/XS

#1776 feat(ui): use API to get launcher number of cores
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/LauncherDialog.tsx
  webapp/src/services/api/study.ts
Labels: size/M

#1770 test(api): added end-to-end test to ensure seamless functionality of API endpoints with the "bot" token
  tests/integration/test_integration_token_end_to_end.py
Labels: size/L

#1775 feat(permission): update permission types, replaced DELETE with WRITE for improved study control
  antarest/core/model.py
  antarest/core/permissions.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration_token_end_to_end.py
  tests/storage/test_service.py
Labels: size/S

#1771 build: v2.15.4
  antarest/__init__.py
  antarest/study/business/district_manager.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/business/command_extractor.py
  antarest/study/storage/variantstudy/model/command/create_cluster.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/web/raw_studies_blueprint.py
  docs/CHANGELOG.md
  scripts/update_version.py
  setup.py
  sonar-project.properties
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/integration/test_integration.py
  tests/integration/variant_blueprint/test_variant_manager.py
  tests/variantstudy/conftest.py
  tests/variantstudy/model/command/test_create_area.py
  tests/variantstudy/model/command/test_create_cluster.py
  tests/variantstudy/model/command/test_create_link.py
  tests/variantstudy/model/command/test_create_renewables_cluster.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_manage_district.py
  tests/variantstudy/model/command/test_replace_matrix.py
  tests/variantstudy/model/test_variant_model.py
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/utils.ts
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/FormTable/index.tsx
  webapp/src/components/common/dialogs/FormDialog.tsx
Labels: size/XXL

#1782 test: correct `test_commands_service`: ensure the admin user is in database
  tests/integration/assets/launcher_mock.bat
  tests/integration/assets/launcher_mock.sh
  tests/integration/conftest.py
  tests/integration/test_integration_token_end_to_end.py
  tests/variantstudy/model/test_variant_model.py
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantDialog.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/dialogs/FormDialog.tsx
Labels: size/L

#1784 feat(ui-studies): rework study launch dialog
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/LauncherDialog.tsx
Labels: size/L

#1789 feat(ui): update LauncherDialog
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/LauncherDialog.tsx
Labels: size/M
