Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-12, with the labels that each got.

#1851 chore(deps): upgrade material-react-table
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/common/GroupedDataTable/index.tsx
Labels: size/XS

#1835 feat(ui-modelization): add dynamic area selection on Areas tab click
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/index.tsx
  webapp/src/components/App/Singlestudy/explore/TabWrapper.tsx
  webapp/src/redux/ducks/studySyntheses.ts
Labels: enhancement, front-end, size/L, UX

#1842 Enhancements and explore button visibility fix in StudyCard component
  webapp/src/components/App/Studies/StudyCard.tsx
Labels: enhancement, size/M, user requests

#1852 feat(ui): add manual submit on clusters form
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/Form.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Form.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Form.tsx
Labels: size/M

#1710 doc(config): enhance application configuration documentation
  docs/install/1-CONFIG.md
  resources/application.yaml
  resources/deploy/config.prod.yaml
  resources/deploy/config.yaml
  scripts/package_antares_web.sh
  tests/core/test_config.py
Labels: size/XXL

#1849 fix(bc): correct the name and shape of the binding constraint matrices
  antarest/study/storage/rawstudy/model/filesystem/root/input/bindingconstraints/bindingconstraints_ini.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/bindingconstraints/bindingcontraints.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/input.py
  antarest/study/storage/variantstudy/business/matrix_constants/binding_constraint/series.py
  antarest/study/storage/variantstudy/business/matrix_constants_generator.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  tests/study/storage/variantstudy/business/test_matrix_constants_generator.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
Labels: size/L

#1856 fix(ui-matrix): calculate the prepend index according to the existence of a time column
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/EditableMatrix/utils.ts
Labels: bug, front-end, size/S

#1855 fix(ui-output): add the missing "ST Storages" option in the Display selector in results view
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/utils.ts
Labels: front-end, size/XS

#1837 feat(db-init): separate database initialization from global database session
  antarest/core/jwt.py
  antarest/core/tasks/model.py
  antarest/core/tasks/repository.py
  antarest/core/tasks/service.py
  antarest/core/utils/fastapi_sqlalchemy/exceptions.py
  antarest/login/main.py
  antarest/login/model.py
  antarest/login/repository.py
  antarest/main.py
  antarest/matrixstore/model.py
  antarest/matrixstore/repository.py
  antarest/matrixstore/service.py
  antarest/singleton_services.py
  antarest/study/main.py
  antarest/study/repository.py
  antarest/study/storage/variantstudy/business/command_extractor.py
  antarest/study/storage/variantstudy/business/matrix_constants_generator.py
  antarest/study/storage/variantstudy/variant_command_extractor.py
  antarest/tools/lib.py
  antarest/utils.py
  tests/conftest_services.py
  tests/core/test_tasks.py
  tests/login/conftest.py
  tests/login/test_login_service.py
  tests/login/test_model.py
  tests/login/test_repository.py
  tests/matrixstore/test_repository.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/integration/conftest.py
  tests/study/storage/variantstudy/business/test_matrix_constants_generator.py
  tests/variantstudy/conftest.py
  tests/variantstudy/model/test_variant_model.py
Labels: size/XXL

#1858 fix(api-bc): avoid duplicates in Binding Constraints creation through REST API
  antarest/core/exceptions.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
Labels: size/L

#1862 fix(ui): update current area after window reload
  webapp/src/components/App/Singlestudy/explore/Modelization/index.tsx
Labels: size/S

#1854 perf(variant): avoid snapshot generation if the snapshot directory already exists
  antarest/study/storage/variantstudy/model/dbmodel.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/study/storage/variantstudy/model/test_dbmodel.py
  tests/study/storage/variantstudy/test_snapshot_generator.py
Labels: size/L, variante, back-end

#1860 refactor(bc): remove duplicate class BindingConstraintType
  antarest/study/business/table_mode_management.py
  tests/integration/test_integration.py
Labels: size/S

#1866 Add a dialog to define a name when duplicate a cluster or a storage
  webapp/src/components/common/GroupedDataTable/CreateDialog.tsx
  webapp/src/components/common/GroupedDataTable/DuplicateDialog.tsx
  webapp/src/components/common/GroupedDataTable/index.tsx
  webapp/src/components/common/GroupedDataTable/utils.ts
  webapp/src/components/common/dialogs/FormDialog.tsx
Labels: enhancement, front-end, size/L

#1869 fix(ui): prevent synchro issues between tabs and react-router
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/AreasTab.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/index.tsx
  webapp/src/components/App/Singlestudy/explore/TabWrapper.tsx
Labels: size/M

#1868 feat(bc): add input validation for binding constraint creation
  antarest/core/exceptions.py
  antarest/study/business/binding_constraint_management.py
  tests/integration/test_integration.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddBindingConstDialog/AddBindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddBindingConstDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstPropsView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/preview.png
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/style.ts
  webapp/src/services/api/studydata.ts
Labels: size/L

#1870 fix(services): rollback the loop for services
  antarest/singleton_services.py
Labels: size/S

#1848 perf(db): improve performance by using joins instead of N+1 queries
  antarest/launcher/service.py
  antarest/study/repository.py
  antarest/study/service.py
  antarest/study/storage/auto_archive_service.py
  tests/launcher/test_service.py
  tests/storage/business/test_autoarchive_service.py
  tests/storage/test_service.py
  tests/study/test_repository.py
Labels: size/L

#1867 fix(bc): automatically change bc matrix when changing frequency
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/integration/test_integration.py
Labels: size/XL

#1872 fix(db): add missing constraints and relationships in `TaskJob` table
  alembic/versions/782a481f3414_fix_task_job_cascade_delete.py
  antarest/core/tasks/model.py
  antarest/core/tasks/repository.py
  antarest/login/model.py
  antarest/study/model.py
  antarest/study/storage/variantstudy/model/dbmodel.py
  pyproject.toml
  scripts/rollback.sh
  tests/core/tasks/__init__.py
  tests/core/tasks/test_model.py
  tests/core/test_tasks.py
Labels: size/XL, back-end, technical debt, performance
