Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2023-09, with the labels that each got.

#1722 fix(api): enhance Python detection in version info endpoint
  antarest/core/version_info.py
Labels: bug, size/XS, api

#1552 fix(docs): update README, removing obsolete instructions
  Dockerfile
  README.md
  docs/install/0-INSTALL.md
  docs/install/1-CONFIG.md
  docs/install/2-DEPLOY.md
Labels: size/L

#1726 fix(api): correct API endpoints and CLI tools
  antarest/gui.py
  antarest/login/ldap.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/study_data_blueprint.py
  antarest/tools/lib.py
  setup.cfg
  tests/core/test_utils_bp.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/test_integration.py
  tests/integration/test_integration_xpansion.py
  tests/integration/utils.py
  tests/matrixstore/test_service.py
  tests/storage/integration/test_exporter.py
  tests/storage/web/test_studies_bp.py
Labels: size/L

#1721 feat(service): assign to a copied study all groups of the user
  antarest/core/requests.py
  antarest/study/common/studystorage.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/studies_blueprint.py
  tests/integration/test_integration.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/business/test_variant_study_service.py
  tests/storage/web/test_studies_bp.py
  tests/study/storage/test_abstract_storage_service.py
Labels: size/XL

#1742 fix(thematic-trimming): correct the name of the "Profit by plant" variable
  antarest/study/business/thematic_trimming_management.py
  antarest/study/business/utils.py
  tests/integration/test_integration.py
  tests/storage/business/test_config_manager.py
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
Labels: size/L

#1743 feat(antares-launcher): use antares launcher v1.3.1
  requirements.txt
  tests/launcher/test_slurm_launcher.py
Labels: size/XS, back-end

#1746 bugfix(matrix): correct the loading and saving of empty matrices as TSV files
  antarest/matrixstore/repository.py
  antarest/matrixstore/service.py
  antarest/matrixstore/uri_resolver_service.py
  antarest/matrixstore/web.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/output_series_matrix.py
  antarest/tools/lib.py
  tests/matrixstore/test_repository.py
  tests/matrixstore/test_service.py
  tests/storage/repository/filesystem/matrix/output_series_matrix_test.py
Labels: size/L

#1739 fix(ui-xpansion): add the missing `batch_size` field in the Xpansion parameters view
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/types.ts
Labels: size/S

#1747 fix(ui-debug): issue to display json file in outputs
  webapp/src/components/App/Singlestudy/explore/Modelization/DebugView/StudyDataView/StudyFileView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/DebugView/StudyTreeView/utils.ts
Labels: size/XS

#1714 fix(raw): impossible to see matrix containing NaN values
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/integration/test_integration_xpansion.py
Labels: size/M
