Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-01, with the labels that each got.

#1878 feat(study-size): add new route to get a study disk usage (in bytes)
  antarest/study/business/binding_constraint_management.py
  antarest/study/service.py
  antarest/study/web/studies_blueprint.py
  tests/integration/studies_blueprint/test_disk_usage.py
  tests/study/test_service.py
Labels: size/L

#1873 docs(st-storage): add ST Sorage documentation
  docs/assets/media/user-guide/study/01-map.tab.png
  docs/assets/media/user-guide/study/02-areas.tab.png
  docs/assets/media/user-guide/study/03-links.tab.png
  docs/assets/media/user-guide/study/04-binding-constraints.tab.png
  docs/assets/media/user-guide/study/05-debug.tab.png
  docs/assets/media/user-guide/study/06-table-mode.tab.png
  docs/assets/media/user-guide/study/areas/01-properties-form.png
  docs/assets/media/user-guide/study/areas/01-properties-tab.png
  docs/assets/media/user-guide/study/areas/02-load.series.png
  docs/assets/media/user-guide/study/areas/02-load.tab.png
  docs/assets/media/user-guide/study/areas/03-thermals.form.png
  docs/assets/media/user-guide/study/areas/03-thermals.list.png
  docs/assets/media/user-guide/study/areas/03-thermals.series.png
  docs/assets/media/user-guide/study/areas/03-thermals.tab.png
  docs/assets/media/user-guide/study/areas/04-renewables.form.png
  docs/assets/media/user-guide/study/areas/04-renewables.list.png
  docs/assets/media/user-guide/study/areas/04-renewables.series.png
  docs/assets/media/user-guide/study/areas/04-renewables.tab.png
  docs/assets/media/user-guide/study/areas/05-hydro.management-options.form.png
  docs/assets/media/user-guide/study/areas/05-hydro.tab.png
  docs/assets/media/user-guide/study/areas/06-wind.tab.png
  docs/assets/media/user-guide/study/areas/07-solar.tab.png
  docs/assets/media/user-guide/study/areas/08-st-storages.form.png
  docs/assets/media/user-guide/study/areas/08-st-storages.list.png
  docs/assets/media/user-guide/study/areas/08-st-storages.series.png
  docs/assets/media/user-guide/study/areas/08-st-storages.tab.png
  docs/assets/media/user-guide/study/areas/09-reserves.series.png
  docs/assets/media/user-guide/study/areas/09-reserves.tab.png
  docs/assets/media/user-guide/study/areas/10-misc-gen.series.png
  docs/assets/media/user-guide/study/areas/10-misc-gen.tab.png
  docs/user-guide/0-introduction.md
  docs/user-guide/1-interface.md
  docs/user-guide/2-study.md
  docs/user-guide/3-variant_manager.md
  docs/user-guide/study/01-map.md
  docs/user-guide/study/02-areas.md
  docs/user-guide/study/03-links.md
  docs/user-guide/study/04-binding-constraints.md
  docs/user-guide/study/05-debug.md
  docs/user-guide/study/06-table-mode.md
  docs/user-guide/study/areas/01-properties.md
  docs/user-guide/study/areas/02-load.md
  docs/user-guide/study/areas/03-thermals.md
  docs/user-guide/study/areas/04-renewables.md
  docs/user-guide/study/areas/05-hydro.md
  docs/user-guide/study/areas/06-wind.md
  docs/user-guide/study/areas/07-solar.md
  docs/user-guide/study/areas/08-st-storages.md
  docs/user-guide/study/areas/09-reserves.md
  docs/user-guide/study/areas/10-misc-gen.md
  mkdocs.yml
  requirements-doc.txt
Labels: documentation, size/XL

#1879 perf(raw-study): improve INI file reading performance for RAW studies
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/study/storage/rawstudy/ini_reader.py
  antarest/study/storage/rawstudy/ini_writer.py
  antarest/study/storage/rawstudy/io/__init__.py
  antarest/study/storage/rawstudy/io/reader/__init__.py
  antarest/study/storage/rawstudy/io/reader/ini_reader.py
  antarest/study/storage/rawstudy/io/writer/__init__.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/json_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/areas/sets.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/allocation/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/settings/generaldata.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/settings.py
  antarest/study/storage/study_upgrader/upgrader_710.py
  antarest/study/storage/study_upgrader/upgrader_800.py
  antarest/study/storage/study_upgrader/upgrader_810.py
  antarest/study/storage/study_upgrader/upgrader_830.py
  antarest/study/storage/study_upgrader/upgrader_840.py
  antarest/study/storage/study_upgrader/upgrader_850.py
  antarest/study/storage/study_upgrader/upgrader_860.py
  antarest/study/storage/utils.py
  tests/integration/test_integration_variantmanager_tool.py
  tests/storage/business/test_study_version_upgrader.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/repository/antares_io/reader/test_ini_reader.py
  tests/storage/repository/antares_io/writer/test_ini_writer.py
  tests/storage/study_upgrader/test_upgrade_710.py
  tests/storage/study_upgrader/test_upgrade_800.py
  tests/storage/study_upgrader/test_upgrade_810.py
  tests/storage/study_upgrader/test_upgrade_820.py
  tests/storage/study_upgrader/test_upgrade_830.py
  tests/storage/study_upgrader/test_upgrade_840.py
  tests/storage/study_upgrader/test_upgrade_850.py
  tests/study/business/areas/test_st_storage_management.py
  tests/variantstudy/model/command/test_create_link.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_manage_district.py
  tests/variantstudy/model/command/test_update_config.py
Labels: size/XL, back-end, user requests, performance

#1871 fix(study-factory): ignore non-existent files in archived studies during build
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  tests/integration/variant_blueprint/test_renewable_cluster.py
  tests/storage/rawstudies/samples/__init__.py
  tests/storage/rawstudies/samples/v810/sample1/study.antares
  tests/storage/rawstudies/test_factory.py
  tests/storage/repository/filesystem/config/test_config_files.py
Labels: size/L, back-end, performance

#1865 fix(xpansion): update for improved parameter handling and code refactoring
  antarest/core/config.py
  antarest/study/business/xpansion_management.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/folder_node.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/settings.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/utils.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/xpansion_studies_blueprint.py
  examples/studies/STA-mini.zip
  tests/integration/assets/STA-mini.7z
  tests/integration/assets/STA-mini.zip
  tests/integration/test_integration_xpansion.py
  tests/integration/xpansion_studies_blueprint/__init__.py
  tests/integration/xpansion_studies_blueprint/test_integration_xpansion.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/business/test_xpansion_manager.py
  tests/storage/integration/test_STA_mini.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/types.ts
  webapp/src/components/common/SelectSingle.tsx
Labels: size/XXL

#1881 fix(db): correct alembic migration script used to purge obsolete tasks
  alembic/versions/782a481f3414_fix_task_job_cascade_delete.py
Labels: bug, technical story, hot, size/L, back-end

#1882 fix(thermals): correct TS Generator matrix index for thermal clusters
  antarest/study/storage/rawstudy/model/filesystem/root/input/thermal/prepro/area/thermal/thermal.py
  tests/integration/studies_blueprint/test_study_matrix_index.py
  tests/integration/test_integration.py
Labels: bug, hot, size/L, back-end

#1886 fix(ci): avoid reflecting user-controlled data (SonarCloud issue)
  antarest/study/web/study_data_blueprint.py
Labels: technical story, size/S, back-end

#1883 Update Table Mode view
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Settings/Groups/index.tsx
  webapp/src/components/App/Settings/Tokens/index.tsx
  webapp/src/components/App/Settings/Users/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/tabs/Table.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/tabs/Thermal.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/TableMode/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/dialogs/CreateTemplateTableDialog.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/dialogs/TableTemplateFormDialog.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/dialogs/UpdateTemplateTableDialog.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/index.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/utils.ts
  webapp/src/components/App/Singlestudy/index.tsx
  webapp/src/components/App/index.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/TableForm/Table.tsx
  webapp/src/components/common/TableForm/index.tsx
  webapp/src/components/common/TableForm/utils.ts
  webapp/src/components/common/TableMode.tsx
  webapp/src/components/common/TabsView.tsx
  webapp/src/services/api/constants.ts
  webapp/src/services/api/forms/tableMode.ts
  webapp/src/services/api/studies/tableMode/constants.ts
  webapp/src/services/api/studies/tableMode/index.ts
  webapp/src/services/api/studies/tableMode/type.ts
  webapp/src/services/utils/localStorage.ts
  webapp/src/utils/stringUtils.ts
  webapp/src/utils/studiesUtils.ts
Labels: enhancement, front-end, size/XXL

#1892 refactor(ui-debug): code review
  webapp/src/components/App/Singlestudy/explore/Modelization/Debug/Data/Json.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Debug/Data/Text.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Debug/DebugContext.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Debug/Tree/FileTreeItem.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Debug/Tree/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Debug/index.tsx
Labels: front-end, size/M

#1894 fix(ui-hydro): add areas encoding to hydro tabs path
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
Labels: size/M

#1893 fix: use CONG PROB for thematic trimming (fix typo)
  antarest/study/business/thematic_trimming_management.py
  tests/integration/test_integration.py
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
Labels: size/M

#1896 Bugfix/debug txt matrix
  webapp/src/components/App/Singlestudy/explore/Modelization/Debug/utils.ts
Labels: size/XS

#1898 Bugfix/debug view json
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Json.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Text.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/style.ts
  webapp/src/components/App/Singlestudy/explore/Debug/DebugContext.ts
  webapp/src/components/App/Singlestudy/explore/Debug/Tree/FileTreeItem.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Tree/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/utils.ts
  webapp/src/components/App/index.tsx
Labels: size/M

#1880 ci(docker): add the `ll` alias in `.bashrc` to simplify debugging
  Dockerfile
Labels: technical story, size/XS

#1895 feat(api-filesystem): add new API endpoints to manage filesystem and get disk usage
  antarest/core/filesystem_blueprint.py
  antarest/core/utils/web.py
  antarest/main.py
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/conftest.py
  tests/integration/filesystem_blueprint/__init__.py
  tests/integration/filesystem_blueprint/test_filesystem_endpoints.py
  tests/integration/filesystem_blueprint/test_model.py
Labels: technical story, front-end, size/XXL, api

#1899 New bugfix release v2.16.3 (2024-01-17)
  Dockerfile
  antarest/__init__.py
  antarest/core/filesystem_blueprint.py
  antarest/core/utils/web.py
  antarest/main.py
  antarest/study/business/thematic_trimming_management.py
  antarest/study/web/raw_studies_blueprint.py
  docs/CHANGELOG.md
  setup.py
  sonar-project.properties
  tests/integration/conftest.py
  tests/integration/filesystem_blueprint/__init__.py
  tests/integration/filesystem_blueprint/test_filesystem_endpoints.py
  tests/integration/filesystem_blueprint/test_model.py
  tests/integration/test_integration.py
  webapp/package-lock.json
  webapp/package.json
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/RegionalDistricts/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Json.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Text.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/style.ts
  webapp/src/components/App/Singlestudy/explore/Debug/DebugContext.ts
  webapp/src/components/App/Singlestudy/explore/Debug/Tree/FileTreeItem.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Tree/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Debug/DebugContext.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Debug/Tree/index.tsx
  webapp/src/components/App/index.tsx
  webapp/src/components/common/page/UnderConstruction.tsx
Labels: size/XXL, release

#1900 Add study disk usage
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/HomeView/InformationView/Notes/DetailsList.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/Notes/NodeEditorModal/index.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/Notes/index.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/Notes/utils.ts
  webapp/src/components/App/Singlestudy/HomeView/InformationView/index.tsx
  webapp/src/services/api/study.ts
  webapp/src/theme.ts
Labels: size/L

#1902 feat(db): index tables to improve study search and sorting performance
  alembic/versions/1f5db5dfad80_add_indexes_to_study_tables.py
  antarest/study/model.py
  scripts/rollback.sh
  tests/study/model.py
  tests/study/storage/rawstudy/test_raw_study_service.py
Labels: enhancement, size/L, feature request, performance

#1901 feat(ui-hydro): add split view to merge "Daily power" and "Energy credits" matrices
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/InflowStructure.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/SplitHydroMatrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/index.tsx
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/EditableMatrix/style.css
  webapp/src/components/common/EditableMatrix/style.ts
  webapp/src/components/common/EditableMatrix/utils.ts
  webapp/src/components/common/MatrixInput/MatrixAssignDialog.tsx
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/SplitLayoutView.tsx
  webapp/src/components/common/SplitView/index.tsx
  webapp/src/components/common/SplitView/style.css
  webapp/src/components/common/dialogs/DataViewerDialog/index.tsx
Labels: size/L

#1890 feat(study-search): optimize the studies search engine
  antarest/launcher/service.py
  antarest/study/repository.py
  antarest/study/service.py
  antarest/study/storage/auto_archive_service.py
  antarest/study/storage/rawstudy/model/filesystem/config/renewable.py
  antarest/study/web/studies_blueprint.py
  tests/integration/assets/ext-840.zip
  tests/integration/assets/ext-850.zip
  tests/integration/assets/ext-860.zip
  tests/integration/studies_blueprint/test_comments.py
  tests/integration/studies_blueprint/test_get_studies.py
  tests/storage/repository/test_study.py
  tests/storage/test_service.py
  tests/study/test_repository.py
Labels: size/XXL

#1910 feat(packaging): update the packaging script to use Antares Solver v8.8.2
  scripts/package_antares_web.sh
Labels: size/S, desktop, back-end

#1911 fix(ui-home): load synthesis to get areas and links count
  webapp/src/components/App/Singlestudy/HomeView/InformationView/Notes/index.tsx
Labels: size/S

#1912 build: fix issue with desktop app packaging
  docs/install/0-INSTALL.md
  scripts/build-front.sh
  webapp/src/i18n.ts
Labels: bug, size/S

#1918 fix(thermals): correct the default value of the "gen-ts" property to use "use global" instead of "use global parameter"
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/table_mode_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/thermal.py
  tests/integration/studies_blueprint/assets/test_synthesis/raw_study.synthesis.json
  tests/integration/studies_blueprint/assets/test_synthesis/variant_study.synthesis.json
  tests/integration/study_data_blueprint/test_thermal.py
  tests/integration/test_integration.py
  tests/study/business/areas/test_thermal_management.py
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/utils.ts
Labels: size/L

#1915 fix(disk-usage): fix bug on variants
  antarest/study/service.py
  tests/integration/studies_blueprint/test_disk_usage.py
Labels: hot, size/M, back-end, waiting for review
