Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-08, with the labels that each got.

#2111 Release v2.17.5
  .github/workflows/main.yml
  antarest/__init__.py
  antarest/core/tasks/web.py
  antarest/core/utils/utils.py
  antarest/matrixstore/service.py
  antarest/study/business/advanced_parameters_management.py
  antarest/study/storage/rawstudy/ini_reader.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  antarest/study/storage/study_download_utils.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/raw_studies_blueprint.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/variant_blueprint.py
  docs/CHANGELOG.md
  examples/studies/STA-mini.zip
  setup.py
  sonar-project.properties
  tests/integration/raw_studies_blueprint/test_download_matrices.py
  tests/integration/study_data_blueprint/test_advanced_parameters.py
  tests/storage/integration/conftest.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/integration/test_exporter.py
  tests/storage/integration/test_write_STA_mini.py
  tests/storage/repository/filesystem/test_ini_file_node.py
  tests/storage/web/test_studies_bp.py
  webapp/package-lock.json
  webapp/package.json
Labels: size/XL, release

#2115 fix(ui-areas): add correct unit in title in Properties form
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
Labels: bug, front-end, size/XS

#2116 fix(hydro): wrong frequency for inflow pattern
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/common/capacity/capacity.py
  tests/storage/repository/filesystem/root/input/hydro/common/capacity/test_capacity.py
Labels: bug, size/XS, api, back-end

#2118 ci(github): split npm jobs and add dependency caching
  .github/workflows/main.yml
Labels: size/M

#2123 fix(adequacy-patch): csr relaxation must be an integer
  antarest/study/business/adequacy_patch_management.py
  tests/integration/test_integration.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/Fields.tsx
  webapp/src/utils/validationUtils.ts
Labels: size/M

#2108 feat(upgrader): use `antares-study-version` package
  antarest/core/exceptions.py
  antarest/study/service.py
  antarest/study/storage/study_upgrader/__init__.py
  antarest/study/storage/study_upgrader/upgrader_710.py
  antarest/study/storage/study_upgrader/upgrader_720.py
  antarest/study/storage/study_upgrader/upgrader_800.py
  antarest/study/storage/study_upgrader/upgrader_810.py
  antarest/study/storage/study_upgrader/upgrader_820.py
  antarest/study/storage/study_upgrader/upgrader_830.py
  antarest/study/storage/study_upgrader/upgrader_840.py
  antarest/study/storage/study_upgrader/upgrader_850.py
  antarest/study/storage/study_upgrader/upgrader_860.py
  antarest/study/storage/study_upgrader/upgrader_870.py
  antarest/study/storage/study_upgrader/upgrader_880.py
  antarest/study/storage/utils.py
  antarest/tools/cli.py
  requirements.txt
  tests/integration/test_studies_upgrade.py
  tests/storage/business/test_study_version_upgrader.py
  tests/storage/study_upgrader/test_upgrade_710.py
  tests/storage/study_upgrader/test_upgrade_720.py
  tests/storage/study_upgrader/test_upgrade_800.py
  tests/storage/study_upgrader/test_upgrade_810.py
  tests/storage/study_upgrader/test_upgrade_820.py
  tests/storage/study_upgrader/test_upgrade_830.py
  tests/storage/study_upgrader/test_upgrade_840.py
  tests/storage/study_upgrader/test_upgrade_850.py
  tests/storage/study_upgrader/test_upgrade_860.py
  tests/storage/study_upgrader/test_upgrade_870.py
  tests/storage/study_upgrader/test_upgrade_880.py
  tests/storage/test_service.py
  tests/study/storage/test_study_version_upgrader.py
  tests/variantstudy/conftest.py
  tests/variantstudy/model/command/test_create_st_storage.py
  tests/variantstudy/model/command/test_remove_st_storage.py
Labels: size/XXL, waiting for review

#2122 build: move all build and project configuration to pyproject.toml
  pyproject.toml
  scripts/update_version.py
  setup.cfg
  setup.py
Labels: size/L

#2125 build: use relative paths in coverage report
  .github/workflows/main.yml
  pyproject.toml
Labels: size/XS

#2112 feat(ts-gen): add timeseries generation
  antarest/core/tasks/model.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/variantstudy/business/command_reverter.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  antarest/study/web/study_data_blueprint.py
  requirements.txt
  tests/core/test_tasks.py
  tests/integration/assets/timeseries_generation/case_1.txt
  tests/integration/assets/timeseries_generation/case_2.txt
  tests/integration/assets/timeseries_generation/case_3.txt
  tests/integration/assets/timeseries_generation/input_gen_ts.txt
  tests/integration/assets/timeseries_generation/reference_case.txt
  tests/integration/study_data_blueprint/test_generate_thermal_cluster_timeseries.py
  tests/variantstudy/test_command_factory.py
Labels: size/XXL, waiting for review

#2126 build: remove auto-generated changelog from desktop package
  .github/workflows/deploy.yml
Labels: size/XS

#2109 feat(bc): show existing matrices only
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/binding_constraint.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/lazy_node.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/bindingconstraints/bindingcontraints.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  requirements-dev.txt
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/storage/repository/filesystem/matrix/test_input_series_matrix.py
  tests/storage/repository/filesystem/test_lazy_node.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
Labels: size/XL, waiting for review

#2092 feat(aggregation-api)!: add new endpoint for `economy/mc-all` aggregation
  antarest/core/exceptions.py
  antarest/study/business/aggregator_management.py
  antarest/study/service.py
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/assets/STA-mini.7z
  tests/integration/assets/STA-mini.zip
  tests/integration/filesystem_blueprint/test_filesystem_endpoints.py
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-01-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-02-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-02.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-03-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-04-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-05-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-06-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-06.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-07-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-07.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-08-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-01-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-02-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-03-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-04-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-05-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-05.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-06-all.result.tsv
  tests/integration/raw_studies_blueprint/test_aggregate_raw_data.py
  tests/integration/studies_blueprint/assets/test_synthesis/raw_study.synthesis.json
  tests/integration/studies_blueprint/test_disk_usage.py
  tests/integration/test_integration.py
  tests/integration/test_integration_token_end_to_end.py
Labels: size/XXL, api, back-end, changes requested

#2114 docs: add installer directions
  docs/install/2-DEPLOY.md
Labels: documentation, size/S

#2128 fix(launcher-api): remove orphan JobResults visibility permissions
  antarest/launcher/service.py
  tests/integration/launcher_blueprint/test_launcher_local.py
  tests/launcher/test_service.py
Labels: size/M, api, back-end
