Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-10, with the labels that each got.

#2166 fix(pydantic): allow `str` fields to be populated by `int`
  antarest/core/cache/business/local_chache.py
  antarest/core/cache/business/redis_cache.py
  antarest/core/configdata/model.py
  antarest/core/core_blueprint.py
  antarest/core/filetransfer/model.py
  antarest/core/interfaces/eventbus.py
  antarest/core/jwt.py
  antarest/core/model.py
  antarest/core/serialization/__init__.py
  antarest/core/tasks/model.py
  antarest/core/utils/__init__.py
  antarest/core/utils/utils.py
  antarest/core/version_info.py
  antarest/eventbus/web.py
  antarest/front.py
  antarest/launcher/adapters/log_parser.py
  antarest/launcher/model.py
  antarest/launcher/ssh_config.py
  antarest/login/auth.py
  antarest/login/model.py
  antarest/login/web.py
  antarest/matrixstore/matrix_editor.py
  antarest/matrixstore/model.py
  antarest/service_creator.py
  antarest/study/business/area_management.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/business/district_manager.py
  antarest/study/business/link_management.py
  antarest/study/business/xpansion_management.py
  antarest/study/model.py
  antarest/study/repository.py
  antarest/study/storage/rawstudy/model/filesystem/config/cluster.py
  antarest/study/storage/rawstudy/model/filesystem/config/identifier.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command_context.py
  antarest/study/storage/variantstudy/model/model.py
  antarest/worker/archive_worker.py
  antarest/worker/simulator_worker.py
  antarest/worker/worker.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/study/business/test_all_optional_metaclass.py
Labels: size/XL

#2167 fix(api): allow `min_stable_power` to be a float inside API response
  antarest/study/business/area_management.py
  tests/integration/study_data_blueprint/test_thermal.py
Labels: size/XS

#2169 fix(snapshot_cleaning): set `ref_id` to `None` to prevent postgresql crash
  antarest/study/storage/variantstudy/variant_study_service.py
Labels: size/XS

#2168 fix(allocation): show matrix even with only one area
  antarest/study/business/allocation_management.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
Labels: size/S

#2172 fix: enable foreign keys for sqlite
  antarest/core/utils/fastapi_sqlalchemy/middleware.py
  tests/conftest.py
  tests/conftest_instances.py
  tests/core/test_tasks.py
  tests/matrixstore/test_matrix_garbage_collector.py
Labels: size/L

#2173 feat: increase cleaning snapshot frequency
  antarest/core/config.py
  antarest/study/storage/auto_archive_service.py
  docs/install/1-CONFIG.md
  tests/storage/business/test_autoarchive_service.py
Labels: size/M

#2177 fix(matrix-index): return the right year
  antarest/study/storage/utils.py
  tests/storage/business/test_study_service_utils.py
Labels: size/S

#2178 fix(tests): adapt new year for index test
  tests/integration/raw_studies_blueprint/test_download_matrices.py
Labels: size/XS

#2180 feat(tests): add tests on matrix index
  antarest/study/storage/utils.py
  tests/integration/raw_studies_blueprint/test_download_matrices.py
  tests/storage/business/test_study_service_utils.py
Labels: size/L

#2179 style(variant): improve logs
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/variant_blueprint.py
  requirements.txt
Labels: size/M

#2185 fix(db): migrate db to use foreign key inside sqlite
  alembic/versions/490b80a84bb5_add_cascade_delete_for_sqlite.py
Labels: size/L

#2184 refactor(workers): remove the `simulator` worker
  antarest/service_creator.py
  antarest/singleton_services.py
  antarest/worker/simulator_worker.py
  tests/worker/test_simulator_worker.py
Labels: size/L

#2165 perf(scripts): improve load balancing
  scripts/start.sh
Labels: size/M

#2187 feat(desktop): open browser when server is started
  antarest/desktop/systray_app.py
Labels: size/XS

#2190 feat(ui-tablemode): prevent duplicate columns
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/TableModeList/dialogs/TableTemplateFormDialog.tsx
  webapp/src/components/common/TableMode.tsx
  webapp/src/utils/validationUtils.ts
Labels: bug, front-end, size/L

#2189 feat(watcher): filter out upgrade and TS generation `.tmp` folders
  antarest/study/storage/rawstudy/watcher.py
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  requirements.txt
  tests/storage/business/test_watcher.py
Labels: size/M

#2192 test(ui-utils): add tests for validation utils & refactor imports
  webapp/src/common/types.ts
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/App/Settings/Users/dialog/UserFormDialog/UserForm.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantDialog.tsx
  webapp/src/components/App/Singlestudy/PropertiesDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Allocation/AllocationField.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Correlation/CorrelationField.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintFields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/CreateAreaDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/CreateDistrictDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/CreateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/UpdateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/dialogs/TableTemplateFormDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CreateCandidateDialog.tsx
  webapp/src/components/common/GroupedDataTable/CreateDialog.tsx
  webapp/src/components/common/GroupedDataTable/DuplicateDialog.tsx
  webapp/src/utils/validation/array.test.ts
  webapp/src/utils/validation/array.ts
  webapp/src/utils/validation/number.test.ts
  webapp/src/utils/validation/number.ts
  webapp/src/utils/validation/string.test.ts
  webapp/src/utils/validation/string.ts
  webapp/tsconfig.json
  webapp/vite.config.ts
Labels: size/XL

#2195 fix(docker): reduce docker image size
  .github/workflows/deploy.yml
  Dockerfile
  README.md
  requirements-desktop.txt
  requirements-dev.txt
  requirements.txt
Labels: size/S

#2198 fix(matrix): return empty index for empty matrices
  antarest/matrixstore/uri_resolver_service.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/storage/repository/filesystem/root/input/hydro/common/capacity/test_capacity.py
Labels: size/M

#2191 feat(tasks): add new endpoint to fetch task progress
  alembic/versions/b33e1f57a60c_add_task_progress.py
  antarest/core/interfaces/eventbus.py
  antarest/core/tasks/model.py
  antarest/core/tasks/service.py
  antarest/core/tasks/web.py
  antarest/launcher/service.py
  antarest/matrixstore/service.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/watcher.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/conftest_services.py
  tests/core/test_tasks.py
  tests/integration/variant_blueprint/test_thermal_cluster.py
  tests/storage/conftest.py
  tests/storage/test_service.py
Labels: size/L

#2199 fix(archive): raise Exception when (un)archiving wrong outputs
  antarest/core/exceptions.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/utils.py
  tests/integration/test_integration.py
  tests/storage/test_service.py
Labels: size/L

#2013 feat(archive-apis)!: use `.7z` format to archive studies
  antarest/core/exceptions.py
  antarest/core/utils/archives.py
  antarest/core/utils/utils.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/service.py
  antarest/matrixstore/service.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/inode.py
  antarest/study/storage/rawstudy/model/filesystem/lazy_node.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/areas/list.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/utils.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/studies_blueprint.py
  antarest/worker/archive_worker.py
  tests/core/test_utils.py
  tests/core/utils/test_extract_zip.py
  tests/integration/assets/STA-mini.7z
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/integration/studies_blueprint/assets/test_synthesis/raw_study.synthesis.json
  tests/integration/studies_blueprint/assets/test_synthesis/variant_study.synthesis.json
  tests/integration/test_integration.py
  tests/storage/business/test_export.py
  tests/storage/business/test_import.py
  tests/storage/integration/conftest.py
  tests/storage/integration/test_exporter.py
  tests/storage/repository/filesystem/special_node/input_areas_list_test.py
  tests/storage/repository/filesystem/test_folder_node.py
  tests/storage/repository/filesystem/test_ini_file_node.py
  tests/storage/test_service.py
  tests/storage/web/test_studies_bp.py
  tests/study/storage/test_abstract_storage_service.py
Labels: enhancement, size/XXL, feature request, api, back-end

#2105 feat(bc): use `update_config` instead of `update_bc` for multiple updates
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
Labels: size/L, waiting for review

#2164 build(python): bump python version to use v3.11
  .github/workflows/deploy.yml
  .github/workflows/license_header.yml
  .github/workflows/main.yml
  .github/workflows/worker.yml
  Dockerfile
  antarest/core/config.py
  antarest/core/configdata/model.py
  antarest/core/interfaces/eventbus.py
  antarest/core/maintenance/model.py
  antarest/core/model.py
  antarest/core/tasks/model.py
  antarest/core/utils/archives.py
  antarest/eventbus/web.py
  antarest/gui.py
  antarest/launcher/adapters/abstractlauncher.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  antarest/matrixstore/service.py
  antarest/service_creator.py
  antarest/study/business/aggregator_management.py
  antarest/study/business/area_management.py
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/enum_ignore_case.py
  antarest/study/business/link_management.py
  antarest/study/business/scenario_builder_management.py
  antarest/study/business/table_mode_management.py
  antarest/study/business/thematic_trimming_management.py
  antarest/study/business/timeseries_config_management.py
  antarest/study/business/xpansion_management.py
  antarest/study/model.py
  antarest/study/repository.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/config/ruleset_matrices.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/date_serializer.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  antarest/study/web/study_data_blueprint.py
  docs/install/0-INSTALL.md
  pyproject.toml
  readthedocs.yml
  requirements-dev.txt
  requirements.txt
  scripts/install-debug.sh
  scripts/stacktrace.sh
  sonar-project.properties
  tests/cache/test_local_cache.py
  tests/cache/test_redis_cache.py
  tests/integration/test_integration.py
  tests/variantstudy/conftest.py
  tests/variantstudy/model/command/test_create_area.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#2194 feat(ts-gen): display progress bar via websockets
  antarest/core/filesystem_blueprint.py
  antarest/core/interfaces/eventbus.py
  antarest/core/tasks/service.py
  antarest/launcher/service.py
  antarest/matrixstore/service.py
  antarest/study/business/utils.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/config/ini_properties.py
  antarest/study/storage/rawstudy/watcher.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_cluster.py
  antarest/study/storage/variantstudy/model/command/create_district.py
  antarest/study/storage/variantstudy/model/command/create_link.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/create_st_storage.py
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/remove_area.py
  antarest/study/storage/variantstudy/model/command/remove_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_district.py
  antarest/study/storage/variantstudy/model/command/remove_link.py
  antarest/study/storage/variantstudy/model/command/remove_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_st_storage.py
  antarest/study/storage/variantstudy/model/command/replace_matrix.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_comments.py
  antarest/study/storage/variantstudy/model/command/update_config.py
  antarest/study/storage/variantstudy/model/command/update_district.py
  antarest/study/storage/variantstudy/model/command/update_playlist.py
  antarest/study/storage/variantstudy/model/command/update_raw_file.py
  antarest/study/storage/variantstudy/model/command/update_scenario_builder.py
  antarest/study/storage/variantstudy/model/command_listener/__init__.py
  antarest/study/storage/variantstudy/model/command_listener/command_listener.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_command_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/conftest_services.py
  tests/core/test_tasks.py
  tests/storage/conftest.py
  tests/storage/test_service.py
  tests/study/storage/variantstudy/test_snapshot_generator.py
Labels: size/XL, waiting for review

#2193 feat(watcher): add new endpoint for optimized scanning
  antarest/core/exceptions.py
  antarest/service_creator.py
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/storage/explorer_service.py
  antarest/study/storage/rawstudy/watcher.py
  antarest/study/storage/utils.py
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  antarest/study/web/explorer_blueprint.py
  antarest/study/web/watcher_blueprint.py
  tests/integration/explorer_blueprint/test_explorer.py
  tests/storage/business/test_explorer_service.py
  tests/storage/business/test_watcher.py
  tests/study/storage/test_utils.py
Labels: size/XL, api, back-end
