Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-07, with the labels that each got.

#2080 ci: update Actions in GitHub workflows
  .github/workflows/compatibility.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
Labels: testing story, front-end, size/M

#2079 test: rename 'study_id' fixture to 'internal_study_id' to avoid confusion with `study_id` variable
  tests/integration/conftest.py
  tests/integration/raw_studies_blueprint/test_aggregate_raw_data.py
  tests/integration/raw_studies_blueprint/test_download_matrices.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/integration/studies_blueprint/test_comments.py
  tests/integration/studies_blueprint/test_disk_usage.py
  tests/integration/studies_blueprint/test_study_matrix_index.py
  tests/integration/studies_blueprint/test_synthesis.py
  tests/integration/studies_blueprint/test_update_tags.py
  tests/integration/study_data_blueprint/test_advanced_parameters.py
  tests/integration/study_data_blueprint/test_config_general.py
  tests/integration/study_data_blueprint/test_edit_matrix.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
  tests/integration/study_data_blueprint/test_hydro_correlation.py
  tests/integration/study_data_blueprint/test_hydro_inflow_structure.py
  tests/integration/study_data_blueprint/test_renewable.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/study_data_blueprint/test_table_mode.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/integration/test_integration.py
  tests/integration/test_studies_upgrade.py
  tests/integration/variant_blueprint/test_renewable_cluster.py
  tests/integration/variant_blueprint/test_st_storage.py
  tests/integration/variant_blueprint/test_thermal_cluster.py
Labels: weight 1, testing story, size/XL

#2082 docs(user-guide): updating Binding Constraints Commands documentation and metadata for search
  docs/user-guide/0-introduction.md
  docs/user-guide/1-interface.md
  docs/user-guide/2-study.md
  docs/user-guide/3-variant_manager.md
Labels: bug, documentation, size/M

#2087 fix(ui-clusters): improve cell number values accuracy by using rounding instead of truncating
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/clustersUtils.ts
Labels: bug, front-end, size/L

#2089 fix(ui-commons): prompt form Form displayed on dialog validation
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantDialog.tsx
  webapp/src/components/common/Fieldset.tsx
  webapp/src/components/common/Form/index.tsx
Labels: bug, front-end, size/M

#2085 build: Update tables and PyYaml versions for python > 3.8
  requirements.txt
Labels: size/XS

#2094 fix(area): allow removal when aggregated mode used
  antarest/study/storage/variantstudy/model/command/remove_area.py
  tests/integration/test_integration.py
  tests/variantstudy/model/command/test_remove_area.py
Labels: size/S

#2088 feat(output): enhance output synthesis view
  antarest/core/exceptions.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/output_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/mcall/grid.py
  tests/storage/integration/data/digest_file.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/repository/filesystem/matrix/test_output_series_matrix.py
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
Labels: size/L, waiting for review

#2101 feat(ui-study): add button to display display 'digest' file on successful tasks in task list
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/DigestDialog.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/JobStepper.tsx
  webapp/src/utils/tsUtils.ts
Labels: size/L, feature request

#2100 docker-compose: change webapp folder from build to dist
  docker-compose.yml
Labels: size/XS

#2103 feat(ui-results): add button to display 'digest' file in result list
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/DigestDialog.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/JobStepper.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/Table.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/TableMode.tsx
  webapp/src/components/common/dialogs/ConfirmationDialog.tsx
  webapp/src/components/common/dialogs/DigestDialog.tsx
  webapp/src/components/common/page/SimpleContent.tsx
  webapp/src/components/common/utils/UsePromiseCond.tsx
Labels: size/L, feature request

#2098 fix(sonar): resolve sonar security issues
  .github/workflows/main.yml
  antarest/core/tasks/web.py
  antarest/core/utils/utils.py
  antarest/matrixstore/service.py
  antarest/study/business/advanced_parameters_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/study_download_utils.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/raw_studies_blueprint.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/variant_blueprint.py
  tests/integration/raw_studies_blueprint/test_download_matrices.py
  tests/integration/study_data_blueprint/test_advanced_parameters.py
  tests/storage/integration/conftest.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/integration/test_exporter.py
  tests/storage/integration/test_write_STA_mini.py
  tests/storage/web/test_studies_bp.py
Labels: size/L, waiting for review

#2106 fix(sc_builder): make section case insensitive
  antarest/study/storage/rawstudy/ini_reader.py
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  tests/storage/repository/filesystem/test_ini_file_node.py
Labels: size/M

#2107 fix(output): endpoint GET `/variables` works with no `areas` or `links` folder
  antarest/study/storage/study_download_utils.py
  examples/studies/STA-mini.zip
  tests/storage/integration/test_STA_mini.py
Labels: hot, size/M, waiting for review
