Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-02, with the labels that each got.

#1920 Fix issue with desktop app packaging for Windows
  scripts/build-front.sh
  webapp/.gitignore
  webapp/vite.config.ts
Labels: bug, size/M

#1919 feat(api-ui): add inflow structure form
  antarest/study/business/areas/hydro_management.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/prepro/area/prepro.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_hydro_inflow_structure.py
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/InflowStructure/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/InflowStructure/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/SplitHydroMatrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
  webapp/src/components/App/index.tsx
  webapp/src/components/common/Form/index.tsx
Labels: size/L

#1922 fix(config): add Swagger proxy settings in Vite configuration
  webapp/vite.config.ts
Labels: size/S

#1664 feat(service): use slurm `sinfo` command to improve "cluster load" indicator
  antarest/core/config.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  antarest/launcher/ssh_client.py
  antarest/launcher/ssh_config.py
  antarest/launcher/web.py
  docs/install/1-CONFIG.md
  requirements.txt
  tests/integration/test_integration.py
  tests/launcher/test_service.py
  tests/launcher/test_slurm_launcher.py
  tests/launcher/test_ssh_client.py
Labels: size/XL

#1923 feature(tag-db): add tag and study_tag tables to the db (migration)
  alembic/versions/3c70366b10ea_add_tag_and_study_tag_tables.py
  antarest/study/css4_colors.py
  antarest/study/model.py
  scripts/rollback.sh
  tests/study/model.py
  tests/study/test_model.py
Labels: size/L

#1903 fix(bc): correct case sensitivity for binding constraint term IDs
  antarest/core/exceptions.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/OptionsList.tsx
Labels: size/L

#1924 fix(api-model): correct `AllOptionalMetaclass` for field validation in form models
  antarest/launcher/ssh_client.py
  antarest/main.py
  antarest/study/business/areas/hydro_management.py
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/thematic_trimming_management.py
  antarest/study/business/utils.py
  antarest/study/business/xpansion_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/cluster.py
  antarest/study/storage/variantstudy/model/command/create_cluster.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/create_st_storage.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_st_storage.py
  antarest/study/web/study_data_blueprint.py
  tests/core/test_config.py
  tests/integration/study_data_blueprint/test_renewable.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/study/business/areas/test_st_storage_management.py
  tests/study/business/test_all_optional_metaclass.py
  tests/variantstudy/model/command/test_create_st_storage.py
Labels: size/XXL, api, back-end

#1926 fix(disk-usage): correct disk usage calculation for study variants with simulation results
  antarest/study/service.py
  antarest/study/storage/utils.py
  docs/assets/media/img/userguide_studyoverview.png
  tests/integration/studies_blueprint/test_disk_usage.py
Labels: bug, size/M, variante, back-end

#1928 fix(ui): update hydro labels and initial level label
  webapp/public/locales/en/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/SplitHydroMatrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
Labels: size/XS

#1927 fix(ui-map): reload map data on study revisit
  webapp/src/redux/ducks/studies.ts
  webapp/src/redux/hooks/useStudyMaps.ts
Labels: size/M

#1932 feat(hydro): add "Min Gen." tab to Hydro section for studies in v8.6 and later
  docs/assets/media/user-guide/study/areas/05-hydro.min-generation.series.png
  docs/user-guide/study/areas/05-hydro.md
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
Labels: front-end, size/S

#1929 feat(tags-db): populate `tag` and `study_tag` tables using pre-existing patch data in `study_additional_data` table
  alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
  scripts/rollback.sh
Labels: size/L

#1934 fix(tags-db): correct `tag` and `study_tag` migration script
  alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
Labels: bug, hot, size/S, back-end

#1888 perf(watcher): improve performance of the Watcher service
  alembic/versions/fd73601a9075_add_delete_cascade_studies.py
  antarest/study/model.py
  antarest/study/repository.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/model/dbmodel.py
  tests/integration/studies_blueprint/test_synthesis.py
  tests/storage/repository/test_study.py
  tests/storage/test_service.py
Labels: size/L

#1940 fix(ui-hydro): add missing matrix path encoding
  webapp/src/services/api/matrix.ts
Labels: size/XS

#1943 fix(variant-db): correct foreign key constraints on variant study table
  alembic/versions/c0c4aaf84861_add_delete_cascade_variant_studies.py
  antarest/study/storage/variantstudy/model/dbmodel.py
  scripts/rollback.sh
  tests/storage/repository/test_study.py
Labels: bug, hot, size/L, back-end

#1937 feat(tags): handle case-insensitive tags and remove orphans
  alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
  antarest/study/model.py
  antarest/study/repository.py
  tests/integration/studies_blueprint/test_get_studies.py
  tests/integration/studies_blueprint/test_update_tags.py
  tests/study/test_repository.py
  webapp/src/utils/studiesUtils.ts
Labels: front-end, size/L, back-end

#1931 feat(permission-db): check user permission through the db query
  antarest/launcher/service.py
  antarest/study/repository.py
  antarest/study/service.py
  antarest/study/storage/auto_archive_service.py
  antarest/study/storage/rawstudy/watcher.py
  antarest/study/web/studies_blueprint.py
  tests/integration/studies_blueprint/test_get_studies.py
  tests/storage/repository/test_study.py
  tests/storage/test_service.py
  tests/study/test_repository.py
Labels: size/XXL, feature request, back-end

#1944 fix(tags): resolve issue with `study.additional_data.patch` attribute reading
  antarest/study/storage/patch_service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/storage/business/test_patch_service.py
Labels: bug, size/L

#1947 fix(variants): correct the generation of variant when a snapshot is removed
  antarest/study/model.py
  antarest/study/storage/variantstudy/model/dbmodel.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  tests/study/storage/variantstudy/model/test_dbmodel.py
Labels: bug, size/S, api

#1946 fix(ui-tablemode): create modal is frozen when submitting without column
  webapp/src/components/common/fieldEditors/ListFE/index.tsx
  webapp/src/utils/feUtils.ts
Labels: bug, front-end, size/S

#1942 feat(study-search): add a studies counting endpoint
  antarest/study/service.py
  antarest/study/web/studies_blueprint.py
  tests/integration/studies_blueprint/test_get_studies.py
  tests/study/test_repository.py
Labels: size/L, back-end

#1954 fix(ui-study): add missing i18n dependency
  webapp/src/components/App/Singlestudy/index.tsx
Labels: size/XS

#1948 Hotfix v2.16.5
  antarest/__init__.py
  antarest/study/model.py
  antarest/study/storage/patch_service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/utils.py
  antarest/study/storage/variantstudy/model/dbmodel.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  docs/CHANGELOG.md
  setup.py
  sonar-project.properties
  tests/storage/business/test_patch_service.py
  tests/study/storage/variantstudy/model/test_dbmodel.py
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/utils.ts
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/index.tsx
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/EditableMatrix/style.ts
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/fieldEditors/ListFE/index.tsx
  webapp/src/services/api/matrix.ts
  webapp/src/services/api/studies/tableMode/index.ts
  webapp/src/services/api/studies/tableMode/utils.ts
  webapp/src/utils/feUtils.ts
Labels: size/L, release
