Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-06, with the labels that each got.

#2045 refactor(ui-utils): update localStorage utils types
  webapp/src/services/utils/localStorage.ts
Labels: front-end, size/S

#2046 feat(ui): update split view
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Data/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/SplitHydroMatrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Load.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/MiscGen.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Reserve.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Solar.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Wind.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/AreaConfig.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/style.ts
  webapp/src/components/App/Singlestudy/explore/TableModeList/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/index.tsx
  webapp/src/components/App/Singlestudy/explore/common/ListElement.tsx
  webapp/src/components/common/DocLink.tsx
  webapp/src/components/common/MatrixInput/MatrixAssignDialog.tsx
  webapp/src/components/common/PropertiesView.tsx
  webapp/src/components/common/SplitView/index.tsx
Labels: size/XL

#2048 fix(ui-commons): add of extensions accepted for matrix import in MatrixInput
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/dialogs/ImportDialog.tsx
Labels: bug, size/XS

#2049 fix(variants): display variants in chronological order in the variants tree
  antarest/study/storage/variantstudy/repository.py
  tests/storage/business/test_repository.py
Labels: bug, size/M, back-end

#2051 fix(ui-map): resolve map graph misalignment caused by `SplitView`
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapGraph.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
Labels: size/M

#2050 fix(api-aggregation): raise 404 HTTP exception for unfound output names
  antarest/core/exceptions.py
  antarest/study/business/aggregator_management.py
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/raw_studies_blueprint/test_aggregate_raw_data.py
Labels: size/M

#2059 fix(variants): display variants in reverse chronological order in the variants tree
  antarest/study/storage/variantstudy/repository.py
  tests/integration/variant_blueprint/test_variant_manager.py
  tests/storage/business/test_repository.py
Labels: bug, size/S, back-end

#2055 fix(table-mode): do not alter existing links that are not updated
  antarest/study/business/link_management.py
  tests/integration/study_data_blueprint/test_table_mode.py
Labels: size/S

#2060 fix(bc): only remove terms when asked
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
Labels: hot, size/M

#2062 fix(table-mode): correct the update of the `average_spilled_energy_cost` field in table mode
  antarest/study/business/area_management.py
  tests/integration/study_data_blueprint/test_table_mode.py
Labels: bug, size/M, api, back-end, table-mode

#2063 fix(ui): hide "upgrade" menu item for variant studies or studies with children
  webapp/src/components/App/Singlestudy/NavHeader/index.tsx
Labels: front-end, size/XS

#2054 feat(ui-api): add scenario builder v8.7 full support
  antarest/study/business/scenario_builder_management.py
  antarest/study/storage/rawstudy/ini_reader.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/ruleset_matrices.py
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/json_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/root/settings/scenariobuilder.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_scenario_builder.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_table_mode.py
  tests/storage/repository/antares_io/reader/test_ini_reader.py
  tests/storage/repository/filesystem/config/test_ruleset_matrices.py
  tests/storage/repository/filesystem/test_scenariobuilder.py
  tests/storage/test_model.py
  webapp/.eslintrc.cjs
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/ConfigContext.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/Rulesets.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/Table.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/tabs/Table.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/tabs/Thermal.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/withAreas.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/vite.config.ts
Labels: size/XXL

#2056 feat(api,ui-config): add 'MILP' value option in 'Unit Commitment Mode' field for study >= v8.8
  antarest/study/business/advanced_parameters_management.py
  tests/integration/study_data_blueprint/test_advanced_parameters.py
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/utils.ts
  webapp/src/components/common/fieldEditors/SelectFE.tsx
Labels: size/L

#2066 feat(worker): deploy AntaresWebWorker on its own
  .github/workflows/commitlint.yml
  .github/workflows/compatibility.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/worker.yml
  AntaresWebWorker.spec
  scripts/package_antares_web.sh
  scripts/package_worker.sh
Labels: size/L

#2065 feat(outputs): remove useless folder `updated_links`
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  tests/launcher/test_slurm_launcher.py
Labels: size/S

#2068 feat(ui): add save button static at bottom and fix style issues
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/AreasTab.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/InflowStructure/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/Form.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Form.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Form.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/index.tsx
  webapp/src/components/App/Singlestudy/explore/TabWrapper.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/index.tsx
  webapp/src/components/App/index.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/TabsView.tsx
  webapp/src/components/common/page/ViewWrapper.tsx
  webapp/src/components/wrappers/LoginWrapper.tsx
  webapp/src/utils/muiUtils.ts
Labels: bug, front-end, size/XL

#2069 feat(ui-theme): increase scrollbar size
  webapp/src/theme.ts
Labels: front-end, size/S

#2070 ci(sonar): bump github action download artifact
  .github/workflows/main.yml
Labels: size/XS

#2071 fix(ui-commons): display a popup to warn of unsaved modifications on Form
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/common/Form/index.tsx
Labels: bug, front-end, size/S

#2072 feat(desktop): add desktop version for ubuntu 22
  .github/workflows/deploy.yml
Labels: size/XS

#2073 chore(deps): add `GlideDataGrid` package
  webapp/package-lock.json
  webapp/package.json
Labels: size/XS

#2075 Release v2.17.2 to dev
  antarest/__init__.py
  docs/CHANGELOG.md
  setup.py
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
Labels: size/M, release

#2061 feat(api): do not allow areas, links or thermals deletion when referenced in a binding constraint
  antarest/core/exceptions.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/web/study_data_blueprint.py
  tests/core/test_exceptions.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/integration/test_integration.py
Labels: size/XL

#2064 feat(outputs): build outputs tree based on filesystem
  antarest/study/storage/rawstudy/model/filesystem/common/area_matrix_list.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/commons/__init__.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/commons/prepro_series.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/input.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/link/area/capacities/capacities.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/load/load.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/renewables/clusters.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/solar/__init__.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/solar/solar.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/thermal/cluster/area/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/thermal/prepro/area/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/thermal/series/area/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/wind/__init__.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/wind/wind.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/areas.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/binding_const.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/link.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/links.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/set.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/utils.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/economy.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/mcall/grid.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/mcind/mcind.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/mcind/scn.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/simulation.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/ts_generator/ts_generator.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/ts_numbers/ts_numbers.py
  examples/studies/STA-mini.zip
  tests/helpers.py
  tests/storage/integration/data/set_id_annual.py
  tests/storage/integration/data/set_values_monthly.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/integration/test_exporter.py
  tests/storage/repository/filesystem/root/output/simulation/mode/common/test_area.py
  tests/storage/repository/filesystem/root/output/simulation/mode/common/test_binding_const.py
  tests/storage/repository/filesystem/root/output/simulation/mode/common/test_link.py
  tests/storage/repository/filesystem/root/output/simulation/mode/common/test_set.py
  tests/storage/repository/filesystem/utils.py
Labels: size/XXL

#2078 feat(api-raw): raise a 404 Not Found error when a resource is missing in the study
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/output_series_matrix.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/storage/repository/filesystem/matrix/input_series_matrix_test.py
  tests/storage/repository/filesystem/matrix/output_series_matrix_test.py
  tests/storage/repository/filesystem/matrix/test_date_serializer.py
  tests/storage/repository/filesystem/matrix/test_head_writer.py
  tests/storage/repository/filesystem/matrix/test_input_series_matrix.py
  tests/storage/repository/filesystem/matrix/test_output_series_matrix.py
Labels: size/XL, feature request, api, back-end
