Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-11, with the labels that each got.

#2208 fix(ts-gen): add failing info in the front and fix pandas issue in the back
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  tests/integration/study_data_blueprint/test_generate_thermal_cluster_timeseries.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/FreezeStudy.tsx
  webapp/src/components/common/LinearProgressWithLabel.tsx
Labels: size/L

#2212 fix(ui-maps): area positions are not saved
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
Labels: bug, front-end, size/XS

#2214 refactor(aggregation-apis): remove `time` column from the aggregated data
  antarest/study/business/aggregator_management.py
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-01-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-01.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-02-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-02.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-03-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-03.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-04-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-04.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-05-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-05.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-06-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-06.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-07-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-07.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-08-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-01-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-01.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-02-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-02.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-03-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-03.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-04-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-04.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-05-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-05.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-06-all.result.tsv
Labels: size/XXL

#2218 feat(matrix): allow import for various formats
  antarest/study/service.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
Labels: size/S

#2207 feat(ui-results): enhance results columns headers
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrixDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/ResultFilters.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/Matrix/components/MatrixActions/index.tsx
  webapp/src/components/common/Matrix/components/MatrixGrid/index.tsx
  webapp/src/components/common/Matrix/components/MatrixGrid/styles.ts
  webapp/src/components/common/Matrix/hooks/useGridCellContent/index.ts
  webapp/src/components/common/Matrix/hooks/useMatrix/index.ts
  webapp/src/components/common/Matrix/index.tsx
  webapp/src/components/common/Matrix/shared/__tests__/utils.test.ts
  webapp/src/components/common/Matrix/shared/utils.ts
Labels: size/L

#2213 feat(auto_archive_service): increase cleaning snapshot frequency
  antarest/core/config.py
  antarest/study/storage/auto_archive_service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  docs/install/1-CONFIG.md
  tests/storage/business/test_autoarchive_service.py
Labels: size/S

#2222 feat(ui-study): change error display in FreezeStudy
  webapp/src/components/App/Singlestudy/FreezeStudy.tsx
Labels: front-end, size/M

#2225 fix(ui-tasks): add missing new task notifications
  webapp/src/components/App/Tasks/NotificationBadge.tsx
Labels: bug, front-end, size/S

#2226 feat(ui-settings): allow to change app language
  webapp/public/locales/en/main.json
  webapp/public/locales/fr-FR
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Settings/General.tsx
  webapp/src/components/App/Settings/index.tsx
  webapp/src/i18n.ts
  webapp/src/utils/i18nUtils.ts
Labels: front-end, size/L, feature request

#2227 feat(ts-gen): add failing area and cluster info inside error msg
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  tests/integration/study_data_blueprint/test_generate_thermal_cluster_timeseries.py
Labels: size/L

#2232 fix(link): fix empty string handling in filter conversion
  antarest/study/storage/rawstudy/model/filesystem/config/links.py
  tests/integration/study_data_blueprint/test_link.py
Labels: size/M

#2230 feat(ui-results): add column filters
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/ResultFilters.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/utils.ts
  webapp/src/components/common/Matrix/shared/types.ts
  webapp/src/components/common/Matrix/shared/utils.ts
  webapp/src/hooks/useDebouncedField.tsx
Labels: size/XL

#2231 feat(ts-gen): add failing area and cluster info inside error msg (#2227)
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  tests/integration/study_data_blueprint/test_generate_thermal_cluster_timeseries.py
Labels: size/L

#2234 fix(ts-gen): make variant generation fail when it's supposed to
  antarest/study/service.py
  tests/integration/study_data_blueprint/test_generate_thermal_cluster_timeseries.py
Labels: size/M

#2235 chore(upgrader): remove duplicated tests
  tests/storage/study_upgrader/conftest.py
  tests/storage/study_upgrader/test_upgrade_710.py
  tests/storage/study_upgrader/test_upgrade_720.py
  tests/storage/study_upgrader/test_upgrade_800.py
  tests/storage/study_upgrader/test_upgrade_810.py
  tests/storage/study_upgrader/test_upgrade_820.py
  tests/storage/study_upgrader/test_upgrade_830.py
  tests/storage/study_upgrader/test_upgrade_840.py
  tests/storage/study_upgrader/test_upgrade_850.py
  tests/storage/study_upgrader/test_upgrade_860.py
  tests/storage/study_upgrader/test_upgrade_870.py
  tests/storage/study_upgrader/test_upgrade_880.py
  tests/storage/study_upgrader/upgrade_710/nominal_case/empty_study_700.expected.zip
  tests/storage/study_upgrader/upgrade_710/nominal_case/empty_study_700.zip
  tests/storage/study_upgrader/upgrade_720/nominal_case/empty_study_710.expected.zip
  tests/storage/study_upgrader/upgrade_720/nominal_case/empty_study_710.zip
  tests/storage/study_upgrader/upgrade_800/nominal_case/empty_study_720.expected.zip
  tests/storage/study_upgrader/upgrade_800/nominal_case/empty_study_720.zip
  tests/storage/study_upgrader/upgrade_810/nominal_case/empty_study_800.expected.zip
  tests/storage/study_upgrader/upgrade_810/nominal_case/empty_study_800.zip
  tests/storage/study_upgrader/upgrade_820/nominal_case/little_study_810.expected.zip
  tests/storage/study_upgrader/upgrade_820/nominal_case/little_study_810.zip
  tests/storage/study_upgrader/upgrade_830/nominal_case/little_study_820.expected.zip
  tests/storage/study_upgrader/upgrade_830/nominal_case/little_study_820.zip
  tests/storage/study_upgrader/upgrade_840/nominal_case/empty_study_830.expected.zip
  tests/storage/study_upgrader/upgrade_840/nominal_case/empty_study_830.zip
  tests/storage/study_upgrader/upgrade_850/nominal_case/empty_study_840.expected.zip
  tests/storage/study_upgrader/upgrade_850/nominal_case/empty_study_840.zip
  tests/storage/study_upgrader/upgrade_860/nominal_case/little_study_850.expected.zip
  tests/storage/study_upgrader/upgrade_860/nominal_case/little_study_850.zip
  tests/storage/study_upgrader/upgrade_870/empty_binding_constraints/little_study_860.expected.zip
  tests/storage/study_upgrader/upgrade_870/empty_binding_constraints/little_study_860.zip
  tests/storage/study_upgrader/upgrade_870/nominal_case/little_study_860.expected.zip
  tests/storage/study_upgrader/upgrade_870/nominal_case/little_study_860.zip
  tests/storage/study_upgrader/upgrade_880/nominal_case/little_study_870.expected.zip
  tests/storage/study_upgrader/upgrade_880/nominal_case/little_study_870.zip
Labels: size/L

#2237 feat(matrix): allow import for comma-separated csv
  antarest/study/service.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
Labels: size/S

#2236 feat(ui-commons,ui-api): allow to export matrices to CSV
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/common/buttons/DownloadMatrixButton.tsx
  webapp/src/services/api/studies/raw/constants.ts
  webapp/src/services/api/studies/raw/types.ts
Labels: front-end, size/M, feature request

#2228 feat: add new build directory structure
  antarest/desktop/systray_app.py
  resources/antares-desktop-fs/README.md
  resources/antares-desktop-fs/archives/.placeholder
  resources/antares-desktop-fs/config.yaml
  resources/antares-desktop-fs/internal_studies/.placeholder
  resources/antares-desktop-fs/logs/.placeholder
  resources/antares-desktop-fs/matrices/.placeholder
  resources/antares-desktop-fs/studies/.placeholder
  resources/antares-desktop-fs/studies/README.md
  resources/antares-desktop-fs/tmp/.placeholder
  resources/deploy/examples/.placeholder
  scripts/package_antares_web.sh
Labels: size/M

#2241 feat(ui-studies): allow to move an archived study
  webapp/src/components/App/Studies/StudyCard/ActionsMenu.tsx
  webapp/src/components/App/Studies/StudyCard/index.tsx
  webapp/src/components/App/Studies/StudyCard/types.tsx
Labels: front-end, size/L

#2247 fix(desktop,windows): wait a few seconds for browser to open
  antarest/desktop/systray_app.py
Labels: size/S

#2249 fix(outputs): allow reading inside archive + output with `.` in the name
  antarest/study/storage/rawstudy/model/filesystem/inode.py
  antarest/study/storage/rawstudy/model/filesystem/lazy_node.py
  antarest/study/storage/utils.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/test_service.py
Labels: hot, size/M

#2175 feat(link): add update endpoint for link
  antarest/core/exceptions.py
  antarest/study/business/link_management.py
  antarest/study/business/model/link_model.py
  antarest/study/business/table_mode_management.py
  antarest/study/business/xpansion_management.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/business/command_reverter.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_link.py
  antarest/study/storage/variantstudy/model/command/update_link.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_link.py
  tests/variantstudy/model/command/test_create_link.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/test_command_factory.py
Labels: size/XL

#2216 feat(raw): allow folder creation inside `user` folder
  antarest/core/exceptions.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/business/command_reverter.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_user_resource.py
  antarest/study/storage/variantstudy/model/command/remove_user_resource.py
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/prepare_proxy.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/storage/test_service.py
  tests/study/storage/variantstudy/test_snapshot_generator.py
  tests/variantstudy/test_command_factory.py
Labels: size/XL
