Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-12, with the labels that each got.

#2257 fix(ui-tablemode): style missing
  webapp/src/components/common/Handsontable.tsx
Labels: bug, front-end, size/XS

#2258 fix(ui-studies): multiple API calls on study list view
  webapp/src/components/App/Studies/StudyCard/index.tsx
Labels: bug, front-end, size/M

#2259 fix(events): avoid slow processing of events
  antarest/eventbus/business/redis_eventbus.py
  antarest/eventbus/service.py
  resources/application.yaml
  tests/eventbus/test_redis_event_bus.py
Labels: size/M

#2261 Release v2.18.1
  antarest/__init__.py
  antarest/eventbus/business/redis_eventbus.py
  antarest/eventbus/service.py
  docs/CHANGELOG.md
  pyproject.toml
  resources/application.yaml
  sonar-project.properties
  tests/eventbus/test_redis_event_bus.py
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Studies/StudyCard/index.tsx
  webapp/src/components/common/Handsontable.tsx
Labels: bug, hot, size/L, release

#2255 fix(ci): use fixed versions for gh actions for build stability
  .github/workflows/main.yml
Labels: size/XS

#2256 fix(links): fix a bug that occurred when updating links via table-mode
  antarest/study/business/link_management.py
  antarest/study/business/model/link_model.py
  antarest/study/business/table_mode_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/links.py
  tests/integration/study_data_blueprint/test_link.py
  tests/integration/study_data_blueprint/test_table_mode.py
  tests/storage/business/test_arealink_manager.py
Labels: size/XL

#2263 fix(tasks): fix frozen task with load balanced pgpool
  antarest/core/tasks/repository.py
  antarest/core/tasks/service.py
  antarest/core/utils/utils.py
  tests/core/test_tasks.py
Labels: size/L

#2252 feat(commands): add creation timestamp and user name inside commands
  alembic/versions/bae9c99bc42d_add_user_name_and_updated_at_to_commands.py
  antarest/study/storage/variantstudy/model/dbmodel.py
  antarest/study/storage/variantstudy/model/model.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/integration/study_data_blueprint/test_hydro_inflow_structure.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/test_integration_token_end_to_end.py
  tests/study/storage/variantstudy/model/test_dbmodel.py
  tests/study/storage/variantstudy/test_variant_study_service.py
  tests/variantstudy/model/command/test_create_cluster.py
  tests/variantstudy/model/command/test_create_renewables_cluster.py
  tests/variantstudy/model/test_variant_model.py
Labels: size/L

#2266 v2.18.2
  antarest/__init__.py
  antarest/core/tasks/repository.py
  antarest/core/tasks/service.py
  antarest/core/utils/utils.py
  docs/CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  tests/core/test_tasks.py
  webapp/package-lock.json
  webapp/package.json
Labels: bug, hot, size/L, release

#2262 fix(ui-bc): use `matrixindex` timesteps for row display
  webapp/src/components/common/Matrix/hooks/useMatrix/index.ts
  webapp/src/components/common/Matrix/index.tsx
Labels: size/XS

#2265 feat(ui-cmd): add command details on variants commands panel
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/Commands/Edition/DraggableCommands/CommandListItem/CommandDetails.tsx
  webapp/src/components/App/Singlestudy/Commands/Edition/DraggableCommands/CommandListItem/index.tsx
  webapp/src/components/App/Singlestudy/Commands/Edition/DraggableCommands/CommandListItem/style.ts
  webapp/src/components/App/Singlestudy/Commands/Edition/DraggableCommands/CommandListView.tsx
  webapp/src/components/App/Singlestudy/Commands/Edition/commandTypes.ts
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
  webapp/src/components/App/Singlestudy/Commands/Edition/style.ts
  webapp/src/components/App/Singlestudy/Commands/Edition/utils.ts
Labels: size/L

#2260 feat(ui-debug): add unsupported files handling
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Image.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Text.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Unsupported.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/utils.ts
Labels: size/L

#2250 feat(aggregation-apis): rename aggregation cols
  antarest/study/business/aggregator_management.py
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/details-STstorage-annual.txt
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/expected_result_sts.csv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-02-all.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-02.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-07.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-08-all.result.tsv
  tests/integration/raw_studies_blueprint/test_aggregate_raw_data.py
Labels: size/XXL, api, back-end

#2239 feat(api,ui-studies): update study move
  antarest/study/service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/integration/studies_blueprint/test_move.py
  tests/integration/test_integration.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/MoveStudyDialog.tsx
  webapp/src/components/App/Studies/StudiesList/index.tsx
  webapp/src/components/App/Studies/StudyTree.tsx
  webapp/src/components/App/Studies/utils.ts
  webapp/src/services/api/study.ts
  webapp/src/utils/validation/array.ts
  webapp/src/utils/validation/number.ts
  webapp/src/utils/validation/string.ts
Labels: bug, front-end, size/L, back-end

#2269 fix(ui-results): resolve data misalignment in matrix column filtering
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/ResultFilters.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
Labels: size/L

#2244 feat(raw-api): add an endpoint to retrieve files in their original format
  antarest/core/exceptions.py
  antarest/core/swagger.py
  antarest/core/utils/archives.py
  antarest/study/business/matrix_management.py
  antarest/study/common/studystorage.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/rawstudy/model/filesystem/folder_node.py
  antarest/study/storage/rawstudy/model/filesystem/inode.py
  antarest/study/storage/rawstudy/model/filesystem/lazy_node.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/storage/repository/filesystem/matrix/test_matrix_node.py
Labels: size/XL, api, back-end

#2268 feat(ui-links): set first link as default when component mounts
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/index.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CandidateForm.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/index.tsx
  webapp/src/components/common/PropertiesView.tsx
  webapp/src/components/common/page/ViewWrapper.tsx
Labels: size/L

#2271 refactor(ui): update clusters group names to lowercase
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/Form.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Form.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/utils.ts
Labels: size/M

#2272 v2.18.3
  antarest/__init__.py
  docs/CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/ResultFilters.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
Labels: size/L

#2224 feat(ui-studies): add on click fetch and display list of non studies folder
  antarest/study/model.py
  antarest/study/storage/explorer_service.py
  antarest/study/web/explorer_blueprint.py
  tests/integration/explorer_blueprint/test_explorer.py
  tests/storage/business/test_explorer_service.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/SideNav.tsx
  webapp/src/components/App/Studies/StudiesList/index.tsx
  webapp/src/components/App/Studies/StudyTree.tsx
  webapp/src/components/App/Studies/StudyTree/__test__/fixtures.ts
  webapp/src/components/App/Studies/StudyTree/__test__/utils.test.tsx
  webapp/src/components/App/Studies/StudyTree/index.tsx
  webapp/src/components/App/Studies/StudyTree/utils.ts
  webapp/src/components/App/Studies/utils.ts
  webapp/src/redux/ducks/studies.ts
  webapp/src/services/api/study.ts
Labels: size/XL

#2273 fix(xpansion): fix several issues related to weights and constraints
  antarest/study/business/xpansion_management.py
  tests/storage/business/test_xpansion_manager.py
Labels: size/L

#2277 feat(ui-debug): add download in original file format
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Json.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Text.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Unsupported.tsx
  webapp/src/components/common/Matrix/hooks/useMatrix/index.ts
  webapp/src/components/common/Matrix/hooks/useMatrix/useMatrix.test.tsx
  webapp/src/components/common/buttons/DownloadMatrixButton.tsx
  webapp/src/components/common/buttons/UploadFileButton.tsx
  webapp/src/services/api/studies/raw/index.ts
  webapp/src/services/api/studies/raw/types.ts
Labels: size/L
