Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-04, with the labels that each got.

#1993 feat(bc): fontend v8.7 support for binding constraints
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstPropsView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/AddConstraintTermForm/OptionsList.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/AddConstraintTermForm/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/BindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintFields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/OptionsList.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/constraintviews/ConstraintElement.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/constraintviews/OffsetInput.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/constraintviews/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/index.tsx
  webapp/src/components/App/Singlestudy/explore/common/OutputFilters.tsx
  webapp/src/components/common/FormGenerator/AutoSubmitGenerator.tsx
  webapp/src/components/common/FormGenerator/index.tsx
  webapp/src/components/common/SelectSingle.tsx
  webapp/src/components/common/TextSeparator.tsx
  webapp/src/services/api/studydata.ts
Labels: size/XXL

#1994 fix(storages-ui): change matrix titles
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Matrix.tsx
Labels: bug, front-end, size/S

#1997 fix(ui-api-bc): v8.7 binding constraints fix
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/index.tsx
Labels: size/M

#1989 feat(commands): add command ID in variant generation job results
  antarest/core/configdata/model.py
  antarest/core/filesystem_blueprint.py
  antarest/launcher/web.py
  antarest/main.py
  antarest/matrixstore/main.py
  antarest/matrixstore/repository.py
  antarest/study/business/areas/properties_management.py
  antarest/study/business/table_mode_management.py
  antarest/study/repository.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/remove_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_config.py
  antarest/study/storage/variantstudy/model/model.py
  antarest/study/storage/variantstudy/repository.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_command_generator.py
  antarest/utils.py
  tests/helpers.py
  tests/study/storage/variantstudy/test_snapshot_generator.py
  tests/variantstudy/model/test_variant_model.py
Labels: size/L, variante

#1988 fix(study-search): correct pagination SQL query
  antarest/study/repository.py
  tests/integration/studies_blueprint/test_get_studies.py
  tests/study/test_repository.py
Labels: size/XL

#2002 feat(thermal): add thermal matrices for v8.7
  antarest/study/business/areas/thermal_management.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/thermal/series/area/thermal/thermal.py
  antarest/study/storage/study_upgrader/upgrader_870.py
  antarest/study/storage/variantstudy/model/command/create_cluster.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/storage/business/test_study_version_upgrader.py
  tests/storage/study_upgrader/upgrade_870/empty_binding_constraints/little_study_860.expected.zip
  tests/storage/study_upgrader/upgrade_870/nominal_case/little_study_860.expected.zip
Labels: size/L

#2009 fix(bc): change exception messages for binding constraints validation
  antarest/core/exceptions.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/integration/study_data_blueprint/test_thermal.py
Labels: size/L

#2006 feat(simulator): API change to add support for study version 8.8
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/thematic_trimming_field_infos.py
  antarest/study/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  antarest/study/storage/study_upgrader/__init__.py
  antarest/study/storage/study_upgrader/upgrader_880.py
  resources/empty_study_880.zip
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/storage/business/test_study_version_upgrader.py
  tests/storage/study_upgrader/test_upgrade_880.py
  tests/storage/study_upgrader/upgrade_870/empty_binding_constraints/little_study_860.expected.zip
  tests/storage/study_upgrader/upgrade_880/nominal_case/little_study_870.expected.zip
  tests/storage/study_upgrader/upgrade_880/nominal_case/little_study_870.zip
  tests/study/business/areas/test_st_storage_management.py
Labels: size/L

#1996 feat(common-ui,results-ui): update matrix buttons (import & export)
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/utils.ts
  webapp/src/components/common/DownloadMatrixButton.tsx
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/MatrixInput/style.ts
  webapp/src/components/common/TableMode.tsx
  webapp/src/components/common/buttons/SplitButton.tsx
  webapp/src/services/api/constants.ts
  webapp/src/services/api/studies/raw/index.ts
  webapp/src/services/api/studies/raw/types.ts
  webapp/src/services/api/studies/tableMode/index.ts
  webapp/src/services/api/studies/tableMode/type.ts
  webapp/src/services/api/studies/tableMode/types.ts
  webapp/src/services/api/studies/tableMode/utils.ts
  webapp/src/utils/fileUtils.ts
  webapp/src/utils/matrixUtils.ts
Labels: front-end, size/XL, feature request

#2004 fix(bc): better handling of default values
  antarest/study/business/all_optional_meta.py
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/business/thematic_trimming_field_infos.py
  antarest/study/business/utils.py
  antarest/study/business/xpansion_management.py
  antarest/study/storage/variantstudy/business/command_extractor.py
  antarest/study/storage/variantstudy/business/command_reverter.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  antarest/study/storage/variantstudy/model/interfaces.py
  antarest/study/storage/variantstudy/variant_command_generator.py
  antarest/study/web/study_data_blueprint.py
  antarest/tools/lib.py
  tests/integration/assets/base_study.zip
  tests/integration/assets/variant_study.zip
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/integration/test_integration.py
  tests/integration/test_integration_variantmanager_tool.py
  tests/study/business/test_all_optional_metaclass.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/test_command_factory.py
Labels: size/XXL

#1984 feat(clusters-ui): implement new duplication endpoint and optimistic update
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/clustersUtils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/utils.ts
  webapp/src/components/App/Singlestudy/explore/TabWrapper.tsx
  webapp/src/components/common/GroupedDataTable/CreateDialog.tsx
  webapp/src/components/common/GroupedDataTable/DuplicateDialog.tsx
  webapp/src/components/common/GroupedDataTable/cellRenderers/BooleanCell.tsx
  webapp/src/components/common/GroupedDataTable/index.tsx
  webapp/src/components/common/GroupedDataTable/types.ts
  webapp/src/components/common/GroupedDataTable/utils.ts
  webapp/src/hooks/useOperationInProgressCount.ts
  webapp/src/hooks/useUpdateEffectOnce.ts
  webapp/src/i18n.ts
  webapp/src/index.tsx
  webapp/src/utils/fnUtils.ts
  webapp/src/utils/i18nUtils.ts
  webapp/src/utils/tsUtils.ts
  webapp/src/utils/validationUtils.ts
Labels: front-end, size/XXL

#1981 feat(api-study): add new endpoint to aggregate raw data
  antarest/study/common/default_values.py
  antarest/study/common/studystorage.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/study_upgrader/__init__.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-01.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-02.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-03.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-04.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_areas_raw_data/test-05.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-01.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-02.result.tsv
  tests/integration/raw_studies_blueprint/assets/aggregate_links_raw_data/test-03.result.tsv
  tests/integration/raw_studies_blueprint/test_aggregate_raw_data.py
Labels: size/XXL

#1643 feat(table-mode): add missing properties for v8.6 and 8.7
  antarest/core/exceptions.py
  antarest/study/business/area_management.py
  antarest/study/business/areas/properties_management.py
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/business/link_management.py
  antarest/study/business/table_mode_management.py
  antarest/study/business/timeseries_config_management.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/config/area.py
  antarest/study/storage/rawstudy/model/filesystem/config/binding_constraint.py
  antarest/study/storage/rawstudy/model/filesystem/config/cluster.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/ini_properties.py
  antarest/study/storage/rawstudy/model/filesystem/config/links.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/renewable.py
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  antarest/study/storage/rawstudy/model/filesystem/config/thermal.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/date_serializer.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/hydro_ini.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/input.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/area.py
  antarest/study/storage/study_download_utils.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_binding_constraint.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/integration/study_data_blueprint/test_renewable.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/study_data_blueprint/test_table_mode.py
  tests/integration/test_integration.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/study/business/areas/test_st_storage_management.py
  tests/variantstudy/model/command/test_create_area.py
  tests/variantstudy/model/command/test_create_renewables_cluster.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/model/command/test_remove_cluster.py
  tests/variantstudy/model/command/test_remove_renewables_cluster.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/index.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/dialogs/CreateTemplateTableDialog.tsx
  webapp/src/components/common/TableMode.tsx
  webapp/src/services/api/studies/tableMode/constants.ts
  webapp/src/services/api/studies/tableMode/index.ts
  webapp/src/services/api/studies/tableMode/types.ts
  webapp/src/services/api/studies/tableMode/utils.ts
  webapp/src/services/api/studydata.ts
Labels: size/XXL

#1998 fix(ui-settings): prevent false duplicates on group form updates
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
Labels: size/XS
