Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-09, with the labels that each got.

#2132 Fix licensing-related issues
  antarest/core/utils/fastapi_sqlalchemy/LICENSE
  antarest/core/utils/fastapi_sqlalchemy/README.md
  antarest/core/utils/fastapi_sqlalchemy/__init__.py
  antarest/core/utils/fastapi_sqlalchemy/exceptions.py
  antarest/core/utils/fastapi_sqlalchemy/middleware.py
  antarest/eventbus/web.py
  antarest/login/auth.py
  antarest/login/main.py
  antarest/login/web.py
  antarest/main.py
  antarest/utils.py
  scripts/license_checker_and_adder.py
Labels: size/L

#2133 ci(test): parallel pytest execution
  .github/workflows/main.yml
  requirements-test.txt
  tests/integration/filesystem_blueprint/test_filesystem_endpoints.py
  tests/integration/filesystem_blueprint/test_model.py
  tests/storage/repository/filesystem/config/test_utils.py
  tests/variantstudy/test_command_factory.py
Labels: size/XL

#2136 fix(standalone): fix api path when embedding front-end
  .github/workflows/main.yml
  antarest/core/application.py
  antarest/core/config.py
  antarest/core/filetransfer/main.py
  antarest/core/maintenance/main.py
  antarest/core/tasks/main.py
  antarest/eventbus/main.py
  antarest/eventbus/web.py
  antarest/front.py
  antarest/gui.py
  antarest/launcher/main.py
  antarest/login/ldap.py
  antarest/login/main.py
  antarest/main.py
  antarest/matrixstore/main.py
  antarest/singleton_services.py
  antarest/study/business/all_optional_meta.py
  antarest/study/main.py
  antarest/tools/lib.py
  antarest/utils.py
  requirements-test.txt
  resources/application.yaml
  resources/deploy/config.prod.yaml
  resources/deploy/config.yaml
  resources/templates/.placeholder
  scripts/build-front.sh
  tests/integration/filesystem_blueprint/test_filesystem_endpoints.py
  tests/integration/filesystem_blueprint/test_model.py
  tests/launcher/test_web.py
  tests/login/test_web.py
  tests/matrixstore/test_web.py
  tests/storage/integration/conftest.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/integration/test_exporter.py
  tests/storage/web/test_studies_bp.py
  tests/test_front.py
  tests/variantstudy/test_command_factory.py
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/page/SimpleContent.tsx
Labels: size/XXL

#2093 feat(ui-debug): update the view
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Folder.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Image.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Json.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Text.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/style.ts
  webapp/src/components/App/Singlestudy/explore/Debug/Data/styles.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/DebugContext.ts
  webapp/src/components/App/Singlestudy/explore/Debug/Tree/FileTreeItem.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Tree/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/utils.ts
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/common/DownloadMatrixButton.tsx
  webapp/src/components/common/JSONEditor/index.tsx
  webapp/src/components/common/JSONEditor/utils.ts
  webapp/src/components/common/MatrixInput/MatrixAssignDialog.tsx
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/SelectSingle.tsx
  webapp/src/components/common/SnackErrorMessage.tsx
  webapp/src/components/common/SplitView/index.tsx
  webapp/src/components/common/TableForm/index.tsx
  webapp/src/components/common/buttons/DownloadButton.tsx
  webapp/src/components/common/buttons/DownloadMatrixButton.tsx
  webapp/src/components/common/buttons/SplitButton.tsx
  webapp/src/components/common/buttons/UploadFileButton.tsx
  webapp/src/hooks/useConfirm.ts
  webapp/src/services/api/studies/raw/index.ts
  webapp/src/services/api/studies/raw/types.ts
  webapp/src/services/api/study.ts
  webapp/src/theme.ts
  webapp/src/types/jsoneditor.d.ts
Labels: bug, front-end, size/XXL, feature request

#2139 feat(pydantic): use pydantic serialization
  alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
  antarest/core/cache/business/redis_cache.py
  antarest/core/configdata/repository.py
  antarest/core/serialization/__init__.py
  antarest/eventbus/web.py
  antarest/launcher/model.py
  antarest/login/auth.py
  antarest/login/main.py
  antarest/login/web.py
  antarest/main.py
  antarest/matrixstore/service.py
  antarest/service_creator.py
  antarest/singleton_services.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/patch_service.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/ini_properties.py
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/json_file_node.py
  antarest/study/storage/study_download_utils.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/dbmodel.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/raw_studies_blueprint.py
  antarest/study/web/xpansion_studies_blueprint.py
  antarest/tools/lib.py
  antarest/worker/archive_worker_service.py
  tests/cache/test_redis_cache.py
  tests/core/test_tasks.py
  tests/login/test_model.py
Labels: size/L

#2144 chore(variants): increase timeout duration for variant generation
  antarest/study/storage/variantstudy/variant_study_service.py
Labels: size/XS

#2150 chore(license): add a new ESLint rule to check license header
  webapp/.eslintrc.cjs
  webapp/.prettierignore
  webapp/package-lock.json
  webapp/package.json
  webapp/src/vite-env.d.ts
  webapp/tsconfig.json
  webapp/tsconfig.node.json
  webapp/vite.config.ts
Labels: front-end, size/M

#2151 feat(aggregation-api): delete index from the response file
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/raw_studies_blueprint/test_aggregate_raw_data.py
Labels: size/M, api, back-end

#2152 fix(playlist): change response model to accept optional answers
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_playlist.py
  tests/integration/test_integration.py
Labels: size/M

#2155 style(api): change apidoc example to make it work
  antarest/study/business/general_management.py
Labels: size/S

#2158 fix(api): allow `nominalcapacity` to be a float inside API response
  antarest/study/business/area_management.py
  antarest/study/business/xpansion_management.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/study_data_blueprint.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/integration/test_integration.py
  tests/storage/business/test_xpansion_manager.py
Labels: size/M

#2160 fix(adq_patch): set default value for field `enable-first-step` to False
  requirements.txt
  resources/empty_study_860.zip
  resources/empty_study_870.zip
  resources/empty_study_880.zip
  tests/storage/business/test_study_version_upgrader.py
Labels: size/XS

#2161 build(ui): fix rollup issue
  webapp/package-lock.json
  webapp/package.json
Labels: bug, front-end, size/XS

#2163 build(ui): fix issue with build result not working
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Data/index.tsx
  webapp/src/components/App/Settings/Groups/Header.tsx
  webapp/src/components/App/Settings/Groups/dialog/CreateGroupDialog.tsx
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/index.tsx
  webapp/src/components/App/Settings/Groups/index.tsx
  webapp/src/components/App/Settings/Tokens/Header.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenFormDialog/TokenForm.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenFormDialog/index.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenInfoDialog.tsx
  webapp/src/components/App/Settings/Tokens/index.tsx
  webapp/src/components/App/Settings/Users/Header.tsx
  webapp/src/components/App/Settings/Users/dialog/UserFormDialog/UserForm.tsx
  webapp/src/components/App/Settings/Users/dialog/UserFormDialog/index.tsx
  webapp/src/components/App/Settings/Users/index.tsx
  webapp/src/components/App/Settings/index.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/Notes/NodeEditorModal/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/AreaPropsView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Allocation/AllocationField.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Correlation/CorrelationField.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/constraintviews/ConstraintElement.tsx
  webapp/src/components/App/Singlestudy/index.tsx
  webapp/src/components/App/Tasks/LaunchJobLogView.tsx
  webapp/src/components/common/Fieldset.tsx
  webapp/src/components/common/FileTable.tsx
  webapp/src/components/common/GroupedDataTable/index.tsx
  webapp/src/components/common/LogModal.tsx
  webapp/src/components/common/MatrixGrid/style.ts
  webapp/src/components/common/SelectMulti.tsx
  webapp/src/components/common/SelectSingle.tsx
  webapp/src/components/common/TextSeparator.tsx
  webapp/src/components/common/TreeItemEnhanced.tsx
  webapp/src/components/common/dialogs/BasicDialog.tsx
  webapp/src/components/common/dialogs/ConfirmationDialog.tsx
  webapp/src/components/common/dialogs/DataViewerDialog/index.tsx
  webapp/src/components/common/dialogs/OkDialog.tsx
  webapp/src/components/common/loaders/SimpleLoader.tsx
  webapp/src/components/common/page/BasicPage.tsx
  webapp/src/components/common/page/RootPage.tsx
  webapp/src/hooks/useEnqueueErrorSnackbar.tsx
  webapp/src/redux/ducks/auth.ts
Labels: bug, front-end, size/XL
