Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-03, with the labels that each got.

#1962 fix(ui-common): dowload latest value in MatrixInput component
  webapp/src/components/common/MatrixInput/index.tsx
Labels: bug, front-end, size/M

#1964 fix(api-study): check area duplicates on creation
  antarest/core/exceptions.py
  antarest/study/business/area_management.py
  tests/integration/test_integration.py
Labels: bug, front-end, size/M, back-end

#1965 Hotfix v2.16.6
  antarest/__init__.py
  docs/CHANGELOG.md
  setup.py
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Tasks/JobTableView.tsx
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/utils/UsePromiseCond.tsx
  webapp/src/services/api/study.ts
Labels: size/L

#1973 refactor(eslint): add new rules and fix new errors
  webapp/.eslintrc.cjs
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Data/DatasetCreationDialog.tsx
  webapp/src/components/App/Data/MatrixDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Json.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/utils.ts
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/utils.ts
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CreateCandidateDialog.tsx
  webapp/src/components/App/Studies/ExportModal/ExportFilter/index.tsx
  webapp/src/components/App/Studies/ExportModal/index.tsx
  webapp/src/components/common/GroupedDataTable/utils.ts
  webapp/src/components/common/LogModal.tsx
  webapp/src/components/common/SplitLayoutView.tsx
  webapp/src/components/common/SplitView/index.tsx
  webapp/src/hoc/reactHookFormSupport.tsx
  webapp/src/hooks/useMemoLocked.ts
  webapp/src/hooks/useNavigateOnCondition.ts
  webapp/src/services/utils/index.ts
  webapp/src/utils/fnUtils.ts
  webapp/src/utils/stringUtils.ts
Labels: front-end, size/L

#1972 feat(clusters): add new endpoint for clusters duplication
  antarest/core/exceptions.py
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_renewable.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/study_data_blueprint/test_thermal.py
Labels: size/XL

#1971 fix(storages): use command when updating matrices
  antarest/core/exceptions.py
  antarest/study/business/areas/st_storage_management.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/study/business/areas/test_st_storage_management.py
Labels: size/L

#1967 fix(variants): avoid Recursive error when creating big variant tree
  antarest/study/storage/variantstudy/business/utils.py
  antarest/study/storage/variantstudy/model/model.py
  tests/integration/studies_blueprint/test_synthesis.py
  tests/integration/variant_blueprint/test_variant_manager.py
Labels: size/M

#1961 fix(xpansion): catch Exception when no sensitvity folder in xpansion
  antarest/study/business/xpansion_management.py
  antarest/study/storage/rawstudy/ini_reader.py
  antarest/study/storage/rawstudy/model/filesystem/bucket_node.py
  antarest/study/storage/rawstudy/model/filesystem/folder_node.py
  antarest/study/storage/rawstudy/model/filesystem/json_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/expansion.py
  antarest/study/storage/study_upgrader/__init__.py
  tests/storage/business/test_xpansion_manager.py
  tests/storage/repository/filesystem/test_folder_node.py
Labels: size/L

#1974 fix(study-search): skip repository study search tests pending a final fix
  tests/study/test_repository.py
Labels: bug, size/XS

#1975 fix(ui-results): correct weekly data formatting to support 53-week years
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
Labels: size/XS

#1977 fix(st-storage): correction of incorrect wording between "withdrawal" and "injection"
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Matrix.tsx
Labels: bug, front-end, size/M

#1956 feat(ui): enhance and refactor validation across UI components
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/App/Settings/Users/dialog/UserFormDialog/UserForm.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantDialog.tsx
  webapp/src/components/App/Singlestudy/PropertiesDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/CreateAreaDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/CreateDistrictDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/CreateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/UpdateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/dialogs/TableTemplateFormDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CreateCandidateDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/common/GroupedDataTable/CreateDialog.tsx
  webapp/src/components/common/GroupedDataTable/DuplicateDialog.tsx
  webapp/src/utils/validationUtils.ts
Labels: size/L

#1818 feat(backend): support v8.7's upgrader, clusters and binding constraints
  antarest/core/exceptions.py
  antarest/matrixstore/service.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/business/table_mode_management.py
  antarest/study/model.py
  antarest/study/storage/rawstudy/ini_writer.py
  antarest/study/storage/rawstudy/model/filesystem/common/area_matrix_list.py
  antarest/study/storage/rawstudy/model/filesystem/config/thermal.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/bindingconstraints/bindingcontraints.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/ts_numbers/ts_numbers.py
  antarest/study/storage/study_upgrader/__init__.py
  antarest/study/storage/study_upgrader/upgrader_860.py
  antarest/study/storage/study_upgrader/upgrader_870.py
  antarest/study/storage/variantstudy/business/command_reverter.py
  antarest/study/storage/variantstudy/business/matrix_constants/binding_constraint/__init__.py
  antarest/study/storage/variantstudy/business/matrix_constants/binding_constraint/series_after_v87.py
  antarest/study/storage/variantstudy/business/matrix_constants/binding_constraint/series_before_v87.py
  antarest/study/storage/variantstudy/business/matrix_constants_generator.py
  antarest/study/storage/variantstudy/business/utils.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_area.py
  antarest/study/storage/variantstudy/model/command/remove_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  antarest/study/storage/variantstudy/model/dbmodel.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/study_data_blueprint.py
  resources/empty_study_870.zip
  tests/integration/studies_blueprint/assets/test_synthesis/raw_study.synthesis.json
  tests/integration/studies_blueprint/assets/test_synthesis/variant_study.synthesis.json
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/integration/test_integration.py
  tests/storage/business/assets/little_study_700.zip
  tests/storage/business/test_study_version_upgrader.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/storage/study_upgrader/test_upgrade_870.py
  tests/storage/study_upgrader/upgrade_870/empty_binding_constraints/little_study_860.expected.zip
  tests/storage/study_upgrader/upgrade_870/empty_binding_constraints/little_study_860.zip
  tests/storage/study_upgrader/upgrade_870/nominal_case/little_study_860.expected.zip
  tests/storage/study_upgrader/upgrade_870/nominal_case/little_study_860.zip
  tests/study/business/areas/test_thermal_management.py
  tests/study/storage/variantstudy/business/test_matrix_constants_generator.py
  tests/study/storage/variantstudy/model/test_dbmodel.py
  tests/variantstudy/conftest.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/test_command_factory.py
Labels: draft, size/XXL

#1978 fix(commands): fix `remove_cluster` command and add unit tests for BC and area removal
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_area.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/variantstudy/assets/empty_study_810.zip
  tests/variantstudy/assets/empty_study_840.zip
  tests/variantstudy/assets/empty_study_870.zip
  tests/variantstudy/conftest.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/model/command/test_remove_cluster.py
Labels: bug, hot, size/L, back-end

#1979 refactor(api): refactor and rename the exceptions related to `.ini` file configuration
  antarest/core/exceptions.py
  antarest/matrixstore/service.py
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  tests/integration/study_data_blueprint/test_renewable.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/study/business/areas/test_st_storage_management.py
Labels: size/L, api, back-end

#1983 fix(db): correct conversion to `CommandDTO` when the version isn't provided in the database
  antarest/study/storage/variantstudy/model/dbmodel.py
Labels: bug, size/XS, api

#1958 fix(outputs): build outputs config even when using cache
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/factory.py
  tests/integration/variant_blueprint/test_variant_manager.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/variantstudy/conftest.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#1985 chore(eslint): add new rules
  webapp/.eslintrc.cjs
Labels: front-end, size/XS

#1987 chore(commitlint): add config
  .gitignore
  commitlint.config.js
  package-lock.json
  package.json
Labels: size/S

#1986 fix(study-search): correct the SQL query used for pagination
  antarest/study/repository.py
  tests/study/test_repository.py
Labels: size/L, back-end

#1990 feat(bc): fontend v8.7 support for binding constraints
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstPropsView.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/AddConstraintTermForm/OptionsList.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/AddConstraintTermForm/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/BindingConstForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintFields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/OptionsList.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintTerm/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/constraintviews/ConstraintElement.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/constraintviews/OffsetInput.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/constraintviews/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/style.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/index.tsx
  webapp/src/components/App/Singlestudy/explore/common/OutputFilters.tsx
  webapp/src/components/common/FormGenerator/AutoSubmitGenerator.tsx
  webapp/src/components/common/FormGenerator/index.tsx
  webapp/src/components/common/SelectSingle.tsx
  webapp/src/components/common/TextSeparator.tsx
  webapp/src/services/api/studydata.ts
Labels: size/XXL

#1982 feat(bc): add constraints groups endpoints and constraints service enhancements
  antarest/core/exceptions.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/business/table_mode_management.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/integration/test_integration.py
  tests/study/business/test_binding_constraint_management.py
  tests/variantstudy/test_command_factory.py
Labels: size/XXL
