Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2024-05, with the labels that each got.

#2021 feat(ui-storages): add parameter 'enabled' for v8.8
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/utils.ts
Labels: bug, front-end, size/S, feature request

#2023 feat(ui-thematictrimming): add groups and sort by alphabetical order
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
  webapp/src/components/common/dialogs/FormDialog.tsx
  webapp/src/services/api/studies/config/thematicTrimming/index.ts
  webapp/src/services/api/studies/config/thematicTrimming/types.ts
Labels: front-end, size/XL, feature request

#2003 feat(ui-thermals): add v8.7 thermal cluster fields
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Matrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/utils.ts
  webapp/src/components/common/EditableMatrix/index.tsx
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/utils/validationUtils.ts
Labels: size/L

#2020 feat(bc): add endpoint for multiple terms edition
  antarest/core/exceptions.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
Labels: size/L

#2026 fix(bc): handle undefined v8.3 fields
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintFields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/utils.ts
Labels: size/XS

#2027 fix(ui-common): allow only import of TSV file in MatrixInput
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/dialogs/ImportDialog.tsx
Labels: bug, front-end, size/S

#2029 feat(ui-utils): add overload signatures for `validateNumber` function in validationUtils
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintFields.tsx
  webapp/src/utils/validationUtils.ts
Labels: front-end, size/L

#2032 fix(import): allow import for users that are reader only
  antarest/study/service.py
  tests/integration/test_integration.py
Labels: size/L

#2012 feat(launcher): add new API endpoint `/v1/launcher/time-limit` and update `LauncherDialog`
  antarest/core/config.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/web.py
  tests/integration/launcher_blueprint/test_launcher_local.py
  tests/launcher/test_slurm_launcher.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/LauncherDialog.tsx
  webapp/src/services/api/study.ts
Labels: bug, enhancement, size/XL

#2030 build(pyinstaller): upgrade version of pyinstaller in build requirements
  AntaresWebLinux.spec
  AntaresWebWin.spec
  requirements-dev.txt
  requirements.txt
Labels: bug, dependencies, size/S

#2025 refactor(ui-storages): update form
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/common/Fieldset.tsx
Labels: front-end, size/L

#2041 fix(variant-command): correct behavior of creation command in special…
  antarest/study/storage/variantstudy/model/command/create_area.py
  tests/variantstudy/model/command/test_create_area.py
Labels: size/M

#2040 feat(ui-common): refactor and update ImportDialog
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Text.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrixDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/Matrix.tsx
  webapp/src/components/App/Studies/ExportModal/index.tsx
  webapp/src/components/App/Studies/HeaderTopRight.tsx
  webapp/src/components/common/FileTable.tsx
  webapp/src/components/common/LogModal.tsx
  webapp/src/components/common/MatrixInput/MatrixAssignDialog.tsx
  webapp/src/components/common/MatrixInput/index.tsx
  webapp/src/components/common/dialogs/DataViewerDialog/index.tsx
  webapp/src/components/common/dialogs/FormDialog.tsx
  webapp/src/components/common/dialogs/ImportDialog.tsx
Labels: bug, size/L

#2043 feat(ui): add studies archive tag
  webapp/src/components/App/Studies/StudyCard.tsx
Labels: size/XS

#2044 fix(ui): prevent `CreateVariantDialog` fields overflow
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantDialog.tsx
Labels: size/XS

#2038 bugfix(sb): handle missing objects in Scenario Builder configuration
  antarest/core/utils/dict.py
  antarest/study/business/scenario_builder_management.py
  antarest/study/business/timeseries_config_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/input.py
  antarest/study/storage/rawstudy/model/filesystem/root/settings/scenariobuilder.py
  antarest/study/storage/study_download_utils.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/remove_area.py
  antarest/study/storage/variantstudy/model/command/remove_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_link.py
  antarest/study/storage/variantstudy/model/command/remove_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_config.py
  antarest/study/storage/variantstudy/model/command/update_scenario_builder.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/test_integration.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/storage/repository/filesystem/test_scenariobuilder.py
  tests/storage/test_service.py
  tests/variantstudy/model/command/helpers.py
  tests/variantstudy/model/command/test_create_renewables_cluster.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/model/command/test_remove_cluster.py
  tests/variantstudy/model/command/test_remove_link.py
  tests/variantstudy/model/command/test_remove_renewables_cluster.py
Labels: bug, hot, size/XXL
