Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2025-03, with the labels that each got.

#2372 fix(bc): allow term modification
  antarest/study/business/binding_constraint_management.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
Labels: size/M

#2375 fix(matrix): change headers inside GET /raw endpoint when formatted is False
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/repository/filesystem/matrix/test_input_series_matrix.py
Labels: size/M

#2376 fix(all): refactor the camel case model annotation
  antarest/study/business/all_optional_meta.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/model/renewable_cluster_model.py
  antarest/study/business/model/sts_model.py
  tests/study/business/test_all_optional_metaclass.py
Labels: size/M

#2378 fix(ini): ignore case when performing update and delete of ini files
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/storage/repository/filesystem/test_ini_file_node.py
Labels: size/L

#2379 fix(commands): remove command notifications
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_command_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/study/storage/variantstudy/test_variant_study_service.py
Labels: size/M

#2340 feat(ui-matrix): add `MatrixResize` allowing columns resize on matrices
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/study_data_blueprint/test_generate_thermal_cluster_timeseries.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
  tests/integration/study_data_blueprint/test_hydro_correlation.py
  tests/integration/study_data_blueprint/test_playlist.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/test_integration.py
  webapp/eslint.config.js
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Data/MatrixDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrix.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrixDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/MiscGen.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Reserve.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Studies/StudyTree/utils.ts
  webapp/src/components/common/DataGrid.tsx
  webapp/src/components/common/DataGridForm.tsx
  webapp/src/components/common/Matrix/components/MatrixActions/MatrixActions.test.tsx
  webapp/src/components/common/Matrix/components/MatrixActions/index.tsx
  webapp/src/components/common/Matrix/components/MatrixGrid/MatrixGrid.test.tsx
  webapp/src/components/common/Matrix/components/MatrixGrid/index.tsx
  webapp/src/components/common/Matrix/components/MatrixResize.tsx
  webapp/src/components/common/Matrix/components/MatrixStats.tsx
  webapp/src/components/common/Matrix/context/MatrixContext.tsx
  webapp/src/components/common/Matrix/hooks/useGridCellContent/index.ts
  webapp/src/components/common/Matrix/hooks/useMatrix/index.ts
  webapp/src/components/common/Matrix/hooks/useMatrix/useMatrix.test.tsx
  webapp/src/components/common/Matrix/hooks/useMatrixColumns.ts
  webapp/src/components/common/Matrix/hooks/useMatrixData.ts
  webapp/src/components/common/Matrix/hooks/useMatrixMutations.ts
  webapp/src/components/common/Matrix/hooks/useSelectionStats/index.ts
  webapp/src/components/common/Matrix/index.tsx
  webapp/src/components/common/Matrix/shared/__tests__/utils.test.ts
  webapp/src/components/common/Matrix/shared/types.ts
  webapp/src/components/common/Matrix/shared/utils.ts
  webapp/src/components/common/dialogs/DataViewerDialog/index.tsx
  webapp/src/components/common/dialogs/DatabaseUploadDialog/components/MatrixContent.tsx
  webapp/src/components/common/dialogs/DatabaseUploadDialog/index.tsx
  webapp/src/components/common/dialogs/DigestDialog/DigestMatrix.tsx
  webapp/src/services/api/matrix.ts
  webapp/src/theme/components.ts
  webapp/src/utils/tsUtils.ts
Labels: size/XXL

#2381 perf(links): improve drastically perfs for update links inside table-mode
  antarest/study/business/link_management.py
Labels: size/S

#2384 perf(links): improve drastically perfs for links inside table-mode
  antarest/study/business/link_management.py
Labels: size/M

#2370 fix(hydro_management): fix read and write in hydro.ini
  antarest/study/business/areas/hydro_management.py
  tests/study/business/areas/test_hydro_management.py
Labels: size/L

#2387 fix(hydro): case insensitive read and write in hydro.ini
  antarest/study/business/areas/hydro_management.py
  tests/study/business/areas/test_hydro_management.py
Labels: size/XXL, size/L

#2390 fix(debug): ensure .json files with prefix file:// proper rendering
  webapp/src/components/App/Singlestudy/explore/Debug/utils.ts
Labels: size/S

#2367 feat(xpansion): add candidate commands
  antarest/core/exceptions.py
  antarest/study/business/model/xpansion_model.py
  antarest/study/business/xpansion_management.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/replace_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/xpansion_common.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/integration/xpansion_studies_blueprint/test_integration_xpansion.py
  tests/storage/business/test_xpansion_manager.py
  tests/variantstudy/model/command/test_xpansion_candidates.py
  tests/variantstudy/test_command_factory.py
Labels: size/XXL

#2274 feat(binding-constraints): create UpdateConstraints command
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/binding_constraint.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/variantstudy/model/command/test_update_binding_constraints.py
  tests/variantstudy/test_command_factory.py
Labels: size/XL

#2391 fix(mypy): change writing inside pandas `replace` method
  antarest/study/storage/rawstudy/model/filesystem/config/ruleset_matrices.py
Labels: size/XS

#2383 fix(ui-matrix): prevent fill handle updates for read-only matrices
  webapp/src/components/common/Matrix/components/MatrixGrid/index.tsx
Labels: size/XS

#2374 feat(hydro): add update hydro management option command
  antarest/study/business/areas/hydro_management.py
  antarest/study/business/model/hydro_model.py
  antarest/study/business/model/inflow_model.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_hydro_management.py
  antarest/study/storage/variantstudy/model/command/update_inflow_structure.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_hydro_inflow_properties.py
  tests/study/business/areas/test_hydro_management.py
  tests/variantstudy/test_command_factory.py
Labels: size/XL

#2397 chore(release): v2.19.1
  alembic/versions/423fe2c8ee40_add_commandblock_index.py
  alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
  antarest/__init__.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  antarest/launcher/web.py
  antarest/study/business/all_optional_meta.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/identifier.py
  docs/CHANGELOG.md
  mkdocs.yml
  pyproject.toml
  sonar-project.properties
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/launcher/test_service.py
  tests/study/test_field_validators.py
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Singlestudy/explore/Debug/utils.ts
Labels: size/L

#2393 feat(xpansion): add `update_xpansion_settings` command
  antarest/study/business/model/xpansion_model.py
  antarest/study/business/xpansion_management.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_xpansion_settings.py
  antarest/study/storage/variantstudy/model/command/xpansion_common.py
  tests/integration/xpansion_studies_blueprint/test_integration_xpansion.py
  tests/storage/business/test_xpansion_manager.py
  tests/variantstudy/model/command/test_update_xpansion_settings.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#2389 fix(ui-digest): conditionally render digest button based on synthesis availability
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/JobStepper.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/LauncherHistory/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/ResultFilters.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/index.tsx
  webapp/src/types/types.ts
Labels: size/L

#2392 test(sts, renewable): add command dto unit tests
  tests/variantstudy/test_command_factory.py
Labels: size/S

#2400 fix(study): allow creating old studies with new version format
  antarest/core/serde/ini_reader.py
  antarest/core/serde/ini_writer.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/storage/utils.py
  antarest/study/web/studies_blueprint.py
  tests/integration/studies_blueprint/test_study_version.py
  tests/launcher/test_service.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/repository/filesystem/matrix/test_input_series_matrix.py
  tests/storage/repository/filesystem/matrix/test_matrix_node.py
  tests/storage/repository/filesystem/special_node/test_lower_case_nodes.py
  tests/storage/test_service.py
  tests/storage/web/test_studies_bp.py
  tests/study/business/areas/test_st_storage_management.py
  tests/study/storage/test_utils.py
  tests/variantstudy/conftest.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_update_config.py
Labels: size/L

#2386 fix(perfs, variant): avoid loading study from disk for snapshot generation
  antarest/core/interfaces/cache.py
  antarest/study/business/utils.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/rawstudy/model/filesystem/config/area.py
  antarest/study/storage/rawstudy/model/filesystem/config/cluster.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/renewable.py
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  antarest/study/storage/rawstudy/model/filesystem/config/thermal.py
  antarest/study/storage/rawstudy/model/filesystem/config/validation.py
  antarest/study/storage/rawstudy/model/filesystem/factory.py
  antarest/study/storage/utils.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_cluster.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/create_st_storage.py
  antarest/study/storage/variantstudy/repository.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_command_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/test_model.py
  tests/study/business/areas/test_st_storage_management.py
  tests/study/test_field_validators.py
Labels: size/L

#2350 feat(area): replace update config in table mode areas
  antarest/study/business/area_management.py
  antarest/study/business/areas/hydro_management.py
  antarest/study/business/areas/properties_management.py
  antarest/study/business/model/area_model.py
  antarest/study/business/model/area_properties_model.py
  antarest/study/business/model/hydro_model.py
  antarest/study/business/model/inflow_model.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_areas_properties.py
  antarest/study/storage/variantstudy/model/command/update_hydro_management.py
  antarest/study/storage/variantstudy/model/command/update_inflow_structure.py
  antarest/study/web/study_data_blueprint.py
  tests/variantstudy/test_command_factory.py
Labels: size/XL

#2404 chore(config): remove unused cache dict
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  tests/storage/test_model.py
Labels: size/S

#2388 perf(ui-results): prevent infinite rendering in results matrices
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
Labels: size/M

#2407 fix(areas): allow negative spread costs
  antarest/study/storage/rawstudy/model/filesystem/config/area.py
  tests/integration/test_integration.py
Labels: size/S

#2408 fix(sts): fix create_st_storage v1 parsing
  antarest/study/storage/variantstudy/model/command/create_st_storage.py
  tests/variantstudy/test_command_factory.py
Labels: size/S

#2409 v2.19.2
  antarest/__init__.py
  antarest/study/storage/variantstudy/model/command/create_st_storage.py
  docs/CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  tests/variantstudy/test_command_factory.py
  webapp/package-lock.json
  webapp/package.json
Labels: size/M

#2406 fix(bc)!: allow terms writing in any case and allow area/cluster names in endpoint
  antarest/core/exceptions.py
  antarest/core/model.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
Labels: size/L

#2415 fix(adequacy_patch): fix bad tooltip
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/Fields.tsx
Labels: size/XS

#2418 fix(adequacy-patch): fix serialization issue inside the ini file
  antarest/study/storage/variantstudy/model/command/update_areas_properties.py
  tests/variantstudy/model/command/test_update_areas_properties.py
Labels: size/M

#2421 fix(terms): revert breaking change
  antarest/study/business/binding_constraint_management.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
Labels: size/M

#2416 perf(table-mode): speed-up mass update for thermal clusters
  antarest/study/business/areas/thermal_management.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_thermal_cluster.py
  antarest/study/storage/variantstudy/model/command/update_thermal_clusters.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/study/storage/variantstudy/test_snapshot_generator.py
  tests/variantstudy/model/command/test_update_thermal_cluster.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#2414 feat(logs): add task_id and user.id to logs
  antarest/core/logging/utils.py
  antarest/core/tasks/service.py
  antarest/core/tasks/web.py
  antarest/launcher/web.py
  antarest/login/utils.py
  antarest/login/web.py
  antarest/matrixstore/web.py
  antarest/study/web/raw_studies_blueprint.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/study_data_blueprint.py
  antarest/study/web/variant_blueprint.py
  antarest/study/web/watcher_blueprint.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/core/test_logging.py
Labels: size/XL

#2419 fix(ui-matrix): disable resize on non-timeseries matrices
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/StorageMatrices.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalConfig/ThermalMatrices.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkMatrixView.tsx
Labels: size/S

#2426 chore(ci): remove ubuntu20 from the ci
  .github/workflows/deploy.yml
  .github/workflows/license-header.yml
  .github/workflows/main.yml
  docker-compose.yml
  docs/developer-guide/install/2-DEPLOY.md
  scripts/package_antares_web.sh
Labels: size/S

#2429 fix(db): fix relationship issues inside tests
  antarest/dbmodel.py
Labels: size/XS

#2431 chore(tests): remove useless zip and introduce new study fixtures
  tests/conftest.py
  tests/storage/business/conftest.py
  tests/storage/business/test_xpansion_manager.py
  tests/study/business/conftest.py
  tests/variantstudy/assets/__init__.py
  tests/variantstudy/assets/empty_study_720.zip
  tests/variantstudy/assets/empty_study_810.zip
  tests/variantstudy/assets/empty_study_840.zip
  tests/variantstudy/assets/empty_study_870.zip
  tests/variantstudy/conftest.py
  tests/variantstudy/model/command/test_create_area.py
  tests/variantstudy/model/command/test_create_cluster.py
  tests/variantstudy/model/command/test_create_link.py
  tests/variantstudy/model/command/test_create_renewables_cluster.py
  tests/variantstudy/model/command/test_create_st_storage.py
  tests/variantstudy/model/command/test_create_xpansion_resource.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
  tests/variantstudy/model/command/test_manage_district.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/model/command/test_remove_cluster.py
  tests/variantstudy/model/command/test_remove_renewables_cluster.py
  tests/variantstudy/model/command/test_remove_st_storage.py
  tests/variantstudy/model/command/test_remove_xpansion_resource.py
  tests/variantstudy/model/command/test_replace_matrix.py
  tests/variantstudy/model/command/test_update_areas_properties.py
  tests/variantstudy/model/command/test_update_comments.py
  tests/variantstudy/model/command/test_update_config.py
  tests/variantstudy/model/command/test_update_rawfile.py
  tests/variantstudy/model/command/test_update_thermal_cluster.py
  tests/variantstudy/model/command/test_update_xpansion_settings.py
  tests/variantstudy/model/command/test_xpansion_candidates.py
Labels: size/XXL

#2432 fix(tests): fix relative import issue
  tests/conftest.py
Labels: size/XS

#2424 fix(commands): use ids inside newly introduced update commands
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/model/renewable_cluster_model.py
  antarest/study/business/model/thermal_cluster_model.py
  antarest/study/business/table_mode_management.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_renewables_clusters.py
  antarest/study/storage/variantstudy/model/command/update_thermal_clusters.py
  tests/variantstudy/model/command/test_update_renewable_cluster.py
  tests/variantstudy/model/command/test_update_thermal_cluster.py
Labels: size/L

#2425 perf(table-mode): speed-up mass update for short term storages
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/model/sts_model.py
  antarest/study/business/table_mode_management.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_st_storage.py
  antarest/study/storage/variantstudy/model/command/update_st_storages.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/study/business/areas/test_st_storage_management.py
  tests/variantstudy/model/command/test_update_short_term_storage.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#2420 feat(hydro): add new endpoint to get hydro related properties for the whole study
  antarest/study/business/areas/hydro_management.py
  antarest/study/business/model/hydro_model.py
  antarest/study/business/model/inflow_model.py
  antarest/study/storage/variantstudy/model/command/update_inflow_structure.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_hydro_inflow_properties.py
  tests/study/business/areas/test_hydro_management.py
  tests/study/business/conftest.py
Labels: size/L
