Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2025-09, with the labels that each got.

#2692 refactor(user): introduce dao for user commands
  antarest/core/exceptions.py
  antarest/study/business/model/user_model.py
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/api/user_resources_dao.py
  antarest/study/dao/file/file_study_dao.py
  antarest/study/dao/file/file_study_user_resources_dao.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_user_resource.py
  antarest/study/storage/variantstudy/model/command/remove_user_resource.py
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
Labels: size/L

#2699 fix(bc): fix a bug when creating new bc
  antarest/study/dao/file/file_study_constraint_dao.py
Labels: size/S

#2709 fix(ui-matrix): enable temporal filters for matrices with fixed column names
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/MiscGen.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Reserve.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalConfig/ThermalMatrices.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkConfig/LinkMatrices.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/index.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/utils/index.ts
Labels: size/M

#2712 build(ts-gen): bump `timeseries-generation` package
  requirements.txt
  tests/integration/study_data_blueprint/test_generate_thermal_cluster_timeseries.py
Labels: size/S

#2711 feat(ui-launcher): update the dialog
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/shared/studies/dialogs/LaunchStudyDialog.tsx
  webapp/src/services/api/study.ts
  webapp/src/types/types.ts
Labels: front-end, size/L

#2698 feat(ui-scenario): filter scenario builder tabs by version
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/Table.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/adapters.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/services.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/types.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/withAreas.tsx
  webapp/src/services/api/studies/config/scenarioBuilder/adapters.ts
  webapp/src/services/api/studies/config/scenarioBuilder/constants.ts
  webapp/src/services/api/studies/config/scenarioBuilder/index.ts
  webapp/src/services/api/studies/config/scenarioBuilder/types.ts
  webapp/src/services/api/studies/config/scenarioBuilder/utils.ts
Labels: size/XXL

#2717 feat(ui-matrix): enable filters on `Inflows` matrix
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/StorageMatrices.tsx
Labels: size/XS

#2733 fix(xpansion): rollback default value for max_iteration
  antarest/study/business/model/xpansion_model.py
  antarest/study/storage/rawstudy/model/filesystem/config/xpansion.py
  tests/integration/xpansion_studies_blueprint/test_integration_xpansion.py
  tests/storage/business/test_xpansion_manager.py
Labels: size/S

#2727 feat(launcher)!: add new endpoint for launchers
  antarest/core/config.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  antarest/launcher/web.py
  tests/integration/launcher_blueprint/test_launcher_local.py
  tests/launcher/test_service.py
  tests/test_resources.py
  webapp/src/components/App/shared/studies/dialogs/LaunchStudyDialog.tsx
  webapp/src/services/api/study.ts
  webapp/src/types/types.ts
Labels: front-end, size/XL, back-end

#2735 fix(commands): use impersonator instead of id for `user_id` attribute
  antarest/login/utils.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/integration/test_integration_token_end_to_end.py
Labels: size/M

#2732 fix(launcher): change cmd line for local launcher with v9.3
  antarest/launcher/adapters/local_launcher/local_launcher.py
  tests/launcher/test_local_launcher.py
Labels: size/M

#2736 fix(output): remove zipped output after unarchiving for all studies
  antarest/core/utils/archives.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/output_service.py
  antarest/study/storage/output_storage.py
  antarest/study/storage/storage_dispatchers.py
  antarest/study/web/output_blueprint.py
  antarest/worker/archive_worker.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/test_service.py
Labels: size/M

#2695 feat(area)!: rename some models
  antarest/study/business/allocation_management.py
  antarest/study/business/area_management.py
  antarest/study/business/areas/properties_management.py
  antarest/study/business/correlation_management.py
  antarest/study/business/model/area_model.py
  antarest/study/business/model/area_properties_model.py
  antarest/study/business/table_mode_management.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/config/area.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/validation.py
  antarest/study/storage/study_download_utils.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/update_areas_properties.py
  antarest/study/web/study_data_blueprint.py
  tests/cache/test_local_cache.py
  tests/cache/test_redis_cache.py
  tests/integration/study_data_blueprint/test_edit_matrix.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
  tests/integration/study_data_blueprint/test_hydro_correlation.py
  tests/integration/study_data_blueprint/test_scenario_builder.py
  tests/integration/study_data_blueprint/test_table_mode.py
  tests/integration/test_integration.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/business/test_xpansion_manager.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/storage/repository/filesystem/root/input/hydro/common/capacity/test_capacity.py
  tests/storage/repository/filesystem/special_node/input_areas_list_test.py
  tests/storage/repository/filesystem/special_node/test_lower_case_nodes.py
  tests/storage/repository/filesystem/test_scenariobuilder.py
  tests/storage/test_model.py
  tests/storage/test_service.py
  tests/study/business/test_allocation_manager.py
  tests/study/business/test_correlation_manager.py
  tests/variantstudy/model/command/test_update_areas_properties.py
  webapp/src/components/App/Singlestudy/explore/Configuration/index.tsx
  webapp/src/services/api/studies/tableMode/constants.ts
Labels: size/XXL

#2728 feat(ui): add filename to delete confirmation dialogs
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/DeleteAreaDialog.tsx
  webapp/src/components/App/shared/studies/dialogs/DeleteStudyDialog.tsx
  webapp/src/components/common/GroupedDataTable/index.tsx
Labels: size/M

#2718 fix(output)!: allow aggregation with columns mismatch
  antarest/core/exceptions.py
  antarest/core/serde/matrix_export.py
  antarest/core/serde/parquet_writer.py
  antarest/study/business/aggregator_management.py
  antarest/study/storage/df_download.py
  antarest/study/storage/output_service.py
  requirements-dev.txt
  tests/core/serde/test_matrix_export.py
  tests/core/serde/test_parquet_writer.py
  tests/integration/raw_studies_blueprint/assets/columns_mismatch.txt
  tests/integration/raw_studies_blueprint/test_aggregate_raw_data.py
Labels: size/XL
