Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2025-06, with the labels that each got.

#2459 feat(desktop): system workspaces
  antarest/core/config.py
  antarest/core/exceptions.py
  antarest/main.py
  antarest/study/storage/explorer_service.py
  antarest/study/storage/rawstudy/watcher.py
  antarest/study/storage/utils.py
  resources/antares-desktop-fs/config.yaml
  tests/storage/business/test_explorer_service.py
  tests/storage/business/test_watcher.py
  tests/storage/test_config.py
  webapp/src/services/api/study.ts
Labels: size/L

#2514 feat(ui-study): add copy dialog and rename action in context menu
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/HomeView/InformationView/index.tsx
  webapp/src/components/App/shared/studies/StudyActionsMenu.tsx
  webapp/src/components/App/shared/studies/dialogs/CopyStudyDialog.tsx
  webapp/src/components/common/Matrix/components/MatrixGrid/index.tsx
  webapp/src/components/common/dialogs/BasicDialog.tsx
  webapp/src/components/common/dialogs/ConfirmationDialog.tsx
  webapp/src/services/api/studies/index.ts
  webapp/src/services/api/studies/types.ts
  webapp/src/services/api/study.ts
  webapp/src/utils/validation/__tests__/number.test.ts
  webapp/src/utils/validation/__tests__/string.test.ts
  webapp/src/utils/validation/number.ts
  webapp/src/utils/validation/string.ts
Labels: front-end, size/L

#2520 feat(ui-debug): move the save button on menu bar in JSON view
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Json.tsx
  webapp/src/components/common/JSONEditor/index.tsx
Labels: front-end, size/L

#2519 fix(link): handle legacy commands
  antarest/study/business/link_management.py
  antarest/study/business/model/link_model.py
  antarest/study/storage/rawstudy/model/filesystem/config/link.py
  antarest/study/storage/variantstudy/model/command/create_link.py
  antarest/study/storage/variantstudy/model/command/update_link.py
  tests/integration/study_data_blueprint/test_link.py
  tests/variantstudy/model/command/test_create_link.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#2512 docs(desktop): add desktop cheat sheet for new devs
  docs/developer-guide/3-desktop-version-cheat-sheet.md
  docs/developer-guide/desktop_artifacts_ui.png
  mkdocs.yml
Labels: size/M

#2509 refactor(renewable): introduce the DAO layer and improve classes design
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/model/renewable_cluster_model.py
  antarest/study/dao/api/renewable_dao.py
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/file/file_study_dao.py
  antarest/study/dao/file/file_study_renewable_dao.py
  antarest/study/dao/file/file_study_thermal_dao.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/renewable.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/create_cluster.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/update_renewables_clusters.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_renewable.py
  tests/integration/study_data_blueprint/test_table_mode.py
  tests/integration/test_integration.py
  tests/integration/variant_blueprint/test_renewable_cluster.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/variantstudy/model/command/test_create_renewables_cluster.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/model/command/test_remove_renewables_cluster.py
  tests/variantstudy/test_command_factory.py
Labels: size/XXL

#2526 fix(launcher): job owner launches the unarchiving task
  antarest/launcher/main.py
  antarest/launcher/service.py
  antarest/service_creator.py
  tests/launcher/test_service.py
  tests/launcher/test_web.py
Labels: size/M

#2524 feat(study-tree,ui-study-tree): preview studies not scanned yet
  antarest/study/model.py
  antarest/study/storage/explorer_service.py
  antarest/study/storage/utils.py
  antarest/study/web/explorer_blueprint.py
  tests/integration/explorer_blueprint/test_explorer.py
  tests/storage/business/test_explorer_service.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/StudyTree/StudyTreeNode.tsx
  webapp/src/components/App/Studies/StudyTree/__test__/utils.test.ts
  webapp/src/components/App/Studies/StudyTree/index.tsx
  webapp/src/components/App/Studies/StudyTree/types.ts
  webapp/src/components/App/Studies/StudyTree/utils.ts
  webapp/src/components/common/TreeItemEnhanced.tsx
  webapp/src/services/api/study.ts
  webapp/src/services/utils/localStorage.ts
Labels: size/L

#2533 feat(sts): handle additional constraints files inside the tree
  antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/constraints/__init__.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/constraints/area/__init__.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/constraints/constraints.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/st_storage.py
  antarest/study/storage/variantstudy/business/matrix_constants/st_storage/series.py
  tests/storage/repository/filesystem/root/input/st_storage/__init__.py
Labels: size/L

#2536 fix(results): normalize `mode` output path segment
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/utils.ts
Labels: size/XS

#2532 fix(desktop): clean deleted studies desktop mode
  antarest/core/exceptions.py
  antarest/main.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/watcher.py
  tests/storage/test_service.py
Labels: size/L

#2542 fix(ui-bc): cannot create BC on study < 8.7
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintFields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/utils.ts
Labels: bug, front-end, size/M

#2544 fix(ui-studies): make study folder fields optional
  webapp/src/utils/studiesUtils.ts
Labels: bug, front-end, size/XS

#2530 docs(adequacy_patch): update of adequacy patch view
  docs/assets/media/user-guide/simulation-configuration/03-configuration-adequacy-patch-earlier.png
  docs/assets/media/user-guide/simulation-configuration/03-configuration-adequacy-patch-later.png
  docs/user-guide/simulation-configuration/all-configurations.md
Labels: size/S

#2548 fix(imagrid): use `economy` instead of `Economy`
  antarest/study/storage/study_download_utils.py
  tests/storage/test_service.py
Labels: size/XS

#2551 chore(release): v2.22.0 (2025-06-25)
  antarest/__init__.py
  docs/CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
Labels: size/M

#2553 chore(release): v2.22.0 (2025-06-25) (#2551)
  antarest/__init__.py
  docs/CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
Labels: size/M

#2550 fix(bc): forbid area/cluster deletion when referenced in a constraint
  antarest/study/dao/file/file_study_thermal_dao.py
  antarest/study/storage/variantstudy/business/utils_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_area.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  tests/variantstudy/model/command/test_remove_area.py
  tests/variantstudy/model/command/test_remove_cluster.py
Labels: size/L

#2513 refactor(st-storage): introduce the DAO layer and improve classes design
  antarest/core/model.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/model/sts_model.py
  antarest/study/dao/api/st_storage_dao.py
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/file/file_study_dao.py
  antarest/study/dao/file/file_study_st_storage_dao.py
  antarest/study/dao/file/file_study_thermal_dao.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  antarest/study/storage/variantstudy/model/command/binding_constraint_utils.py
  antarest/study/storage/variantstudy/model/command/create_st_storage.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/remove_st_storage.py
  antarest/study/storage/variantstudy/model/command/update_st_storages.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/variant_blueprint/test_st_storage.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/study/business/areas/test_st_storage_management.py
  tests/study/business/areas/test_thermal_management.py
  tests/study/storage/rawstudy/test_raw_study_service.py
  tests/study/storage/variantstudy/test_variant_study_service.py
  tests/variantstudy/model/command/test_create_st_storage.py
  tests/variantstudy/model/command/test_remove_st_storage.py
  tests/variantstudy/model/command/test_update_short_term_storage.py
  tests/variantstudy/test_command_factory.py
Labels: size/XXL

#2547 feat(ui-tasks): filter tasks by user
  webapp/src/components/App/Tasks/JobTableView.tsx
  webapp/src/components/App/Tasks/index.tsx
  webapp/src/components/common/fieldEditors/SearchFE.tsx
  webapp/src/services/api/study.ts
  webapp/src/services/utils/localStorage.ts
  webapp/src/types/types.ts
Labels: size/M

#2515 feat(matrix): add different handling of matrix for managed and unmanaged study
  antarest/launcher/extensions/adequacy_patch/extension.py
  antarest/matrixstore/matrix_uri_mapper.py
  antarest/study/main.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/factory.py
  antarest/study/storage/rawstudy/model/filesystem/lazy_node.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/utils.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/conftest.py
  tests/conftest_services.py
  tests/storage/business/conftest.py
  tests/storage/business/test_url_resolver_service.py
  tests/storage/rawstudies/test_factory.py
  tests/storage/repository/filesystem/matrix/test_input_series_matrix.py
  tests/storage/repository/filesystem/matrix/test_matrix_node.py
  tests/storage/repository/filesystem/test_folder_node.py
  tests/storage/repository/filesystem/test_lazy_node.py
  tests/study/business/areas/test_thermal_management.py
  tests/study/storage/variantstudy/test_snapshot_generator.py
Labels: size/XL, back-end, performance
