Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2025-02, with the labels that each got.

#2316 feat(study): normalize study path
  antarest/study/model.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/test_service.py
Labels: size/S

#2303 feat(ts-gen)!: replace legacy endpoints with new ones
  antarest/study/business/timeseries_config_management.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_generate_thermal_cluster_timeseries.py
  tests/integration/test_integration.py
  tests/storage/business/test_timeseries_config_manager.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/common/types.ts
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
  webapp/src/components/App/Singlestudy/FreezeStudy.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields/TypeConfigFields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/utils.ts
  webapp/src/components/common/buttons/DownloadMatrixButton.tsx
  webapp/src/redux/ducks/studyMaps.ts
  webapp/src/services/api/studies/links/types.ts
  webapp/src/services/api/studies/raw/types.ts
  webapp/src/services/api/studies/timeseries/constants.ts
  webapp/src/services/api/studies/timeseries/index.ts
  webapp/src/services/api/studies/timeseries/types.ts
  webapp/src/services/api/tasks/index.ts
  webapp/src/services/api/tasks/types.ts
  webapp/src/services/webSocket/types.ts
Labels: front-end, size/XL, back-end

#2328 feat(ui-commons): allow multiple cells to be pasted in DataGridForm
  webapp/src/components/common/DataGridForm.tsx
Labels: front-end, size/XS

#2330 fix(ui-common): bump MUI to v6.4.3 to resolve Select list bug causing crashes
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/common/DynamicList.tsx
  webapp/src/components/common/SelectMulti.tsx
  webapp/src/components/common/page/ViewWrapper.tsx
Labels: size/XS

#2331 build(all): bump pydantic and linting packages
  .github/workflows/main.yml
  antarest/core/filetransfer/service.py
  antarest/service_creator.py
  antarest/study/business/general_management.py
  requirements-dev.txt
  requirements.txt
  tests/integration/studies_blueprint/test_get_studies.py
  tests/variantstudy/model/command/test_remove_st_storage.py
Labels: size/M

#2113 feat(matrices): allow other formats for internal matrices storage
  antarest/core/config.py
  antarest/matrixstore/main.py
  antarest/matrixstore/migration_script.py
  antarest/matrixstore/repository.py
  antarest/service_creator.py
  docs/developer-guide/install/1-CONFIG.md
  requirements.txt
  tests/conftest_services.py
  tests/matrixstore/conftest.py
  tests/matrixstore/test_repository.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/integration/conftest.py
  tests/study/storage/variantstudy/business/test_matrix_constants_generator.py
Labels: size/XL

#2322 feat(area): move area command creation
  antarest/study/business/allocation_management.py
  antarest/study/business/area_management.py
  antarest/study/business/correlation_management.py
  antarest/study/business/model/area_model.py
  antarest/study/business/table_mode_management.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_area_ui.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_area.py
  tests/storage/business/test_arealink_manager.py
  tests/variantstudy/test_command_factory.py
Labels: size/XL

#2338 chore(release): v2.19.0
  antarest/__init__.py
  docs/CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
Labels: size/L

#2329 fix(explorer): normalize folder path
  antarest/study/model.py
  antarest/study/storage/explorer_service.py
  tests/storage/business/test_explorer_service.py
Labels: size/S

#2323 fix(commands): fix error on command notifications
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_command_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/study/storage/variantstudy/test_variant_study_service.py
Labels: size/M

#2341 refactor(ui-clusters): update clusters group names to lowercase
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/Form.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Form.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/utils.ts
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/utils.ts
Labels: size/M

#2296 feat(matrix): never return empty matrix
  antarest/matrixstore/uri_resolver_service.py
  antarest/study/storage/rawstudy/model/filesystem/common/prepro.py
  antarest/study/storage/rawstudy/model/filesystem/lazy_node.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/constants.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/common/capacity/capacity.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/hydro/prepro/area/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/link/area/area.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/link/area/capacities/capacities.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/thermal/prepro/area/thermal/thermal.py
  tests/integration/raw_studies_blueprint/test_download_matrices.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/integration/study_data_blueprint/test_generate_thermal_cluster_timeseries.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/repository/filesystem/matrix/test_input_series_matrix.py
  tests/storage/repository/filesystem/matrix/test_matrix_node.py
  tests/storage/repository/filesystem/test_lazy_node.py
Labels: size/L

#2344 refactor(all): remove pydantic v1 dependencies
  antarest/eventbus/business/redis_eventbus.py
  antarest/eventbus/web.py
  antarest/matrixstore/model.py
  antarest/matrixstore/repository.py
  antarest/matrixstore/service.py
  antarest/study/business/allocation_management.py
  antarest/study/business/area_management.py
  antarest/study/business/areas/hydro_management.py
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/business/correlation_management.py
  antarest/study/business/general_management.py
  antarest/study/business/optimization_management.py
  antarest/study/business/playlist_management.py
  antarest/study/business/xpansion_management.py
  antarest/study/model.py
  antarest/study/storage/patch_service.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/study_download_utils.py
  antarest/study/storage/utils.py
  tests/conftest.py
  tests/integration/filesystem_blueprint/test_model.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
  tests/integration/study_data_blueprint/test_hydro_correlation.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/launcher/test_slurm_launcher.py
  tests/login/test_web.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/conftest.py
  tests/storage/test_service.py
  tests/storage/web/test_studies_bp.py
  tests/study/business/test_allocation_manager.py
  tests/study/storage/rawstudy/test_raw_study_service.py
  tests/study/storage/variantstudy/test_variant_study_service.py
  tests/study/test_field_validators.py
  tests/variantstudy/model/command/test_create_st_storage.py
  tests/variantstudy/model/command/test_remove_cluster.py
  tests/variantstudy/model/command/test_replace_matrix.py
  tests/variantstudy/model/command/test_update_comments.py
  tests/variantstudy/model/test_variant_model.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#2347 feat(properties): add two fields to area properties form
  antarest/study/business/areas/properties_management.py
  tests/integration/test_integration.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/utils.ts
Labels: size/M

#2334 fix(scan): fix workspaces can't overlap nor be renamed
  antarest/core/config.py
  antarest/study/service.py
  tests/storage/test_config.py
  tests/storage/test_service.py
Labels: size/L

#2346 fix(ui-debug): treat 'file://*.json' files as JSON instead of unsupported
  webapp/src/components/App/Singlestudy/explore/Debug/utils.ts
Labels: size/XS

#2343 refactor(services): fix wrong dependency from business to service
  antarest/matrixstore/in_memory.py
  antarest/study/business/adequacy_patch_management.py
  antarest/study/business/advanced_parameters_management.py
  antarest/study/business/allocation_management.py
  antarest/study/business/area_management.py
  antarest/study/business/areas/hydro_management.py
  antarest/study/business/areas/properties_management.py
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/business/config_management.py
  antarest/study/business/correlation_management.py
  antarest/study/business/district_manager.py
  antarest/study/business/general_management.py
  antarest/study/business/link_management.py
  antarest/study/business/matrix_management.py
  antarest/study/business/optimization_management.py
  antarest/study/business/playlist_management.py
  antarest/study/business/scenario_builder_management.py
  antarest/study/business/study_interface.py
  antarest/study/business/table_mode_management.py
  antarest/study/business/thematic_trimming_management.py
  antarest/study/business/timeseries_config_management.py
  antarest/study/business/xpansion_management.py
  antarest/study/main.py
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command_context.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/study_data_blueprint.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/conftest_services.py
  tests/matrixstore/test_in_memory_matrix_service.py
  tests/matrixstore/test_matrix_garbage_collector.py
  tests/storage/business/conftest.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/business/test_config_manager.py
  tests/storage/business/test_timeseries_config_manager.py
  tests/storage/business/test_watcher.py
  tests/storage/business/test_xpansion_manager.py
  tests/storage/test_service.py
  tests/study/business/areas/test_st_storage_management.py
  tests/study/business/areas/test_thermal_management.py
  tests/study/business/conftest.py
  tests/study/business/test_allocation_manager.py
  tests/study/business/test_correlation_manager.py
  tests/study/business/test_district_manager.py
  tests/variantstudy/conftest.py
  tests/variantstudy/test_command_factory.py
Labels: size/XXL

#2355 chore(simulator): bump simulator v8.8 version inside Desktop app
  scripts/package_antares_web.sh
Labels: size/XS

#2339 fix(study-tree-ui): add exist true filter to studies request
  webapp/src/services/api/study.ts
Labels: size/XS

#2358 chore(deps): use `antares-study-version` package for study creation
  antarest/study/main.py
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/utils.py
  resources/empty_study_613.zip
  resources/empty_study_700.zip
  resources/empty_study_710.zip
  resources/empty_study_720.zip
  resources/empty_study_803.zip
  resources/empty_study_810.zip
  resources/empty_study_820.zip
  resources/empty_study_830.zip
  resources/empty_study_840.zip
  resources/empty_study_850.zip
  resources/empty_study_860.zip
  resources/empty_study_870.zip
  resources/empty_study_880.zip
  tests/conftest_services.py
  tests/storage/business/test_export.py
  tests/storage/business/test_import.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/test_service.py
  tests/storage/web/test_studies_bp.py
  tests/test_resources.py
Labels: size/L

#2359 chore(patch)!: remove patch service
  antarest/study/business/area_management.py
  antarest/study/business/model/area_model.py
  antarest/study/business/study_interface.py
  antarest/study/common/studystorage.py
  antarest/study/main.py
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/patch_service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/study_data_blueprint.py
  tests/conftest_services.py
  tests/integration/filesystem_blueprint/test_filesystem_endpoints.py
  tests/integration/test_integration.py
  tests/integration/variant_blueprint/test_st_storage.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/business/test_export.py
  tests/storage/business/test_import.py
  tests/storage/business/test_patch_service.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/business/test_variant_study_service.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/test_service.py
  tests/storage/web/test_studies_bp.py
  tests/study/storage/rawstudy/test_raw_study_service.py
  tests/study/storage/variantstudy/test_snapshot_generator.py
  tests/study/storage/variantstudy/test_variant_study_service.py
  tests/variantstudy/model/test_variant_model.py
  webapp/src/common/types.ts
  webapp/src/services/utils/index.ts
Labels: size/XXL

#2360 chore(dev): share pre-commit configuration for local dev
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: size/S

#2361 feat(xpansion): create `remove_xpansion_configuration` command
  antarest/study/business/xpansion_management.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_configuration.py
  tests/integration/xpansion_studies_blueprint/test_integration_xpansion.py
Labels: size/M

#2352 feat(renewable): add update renewable cluster command
  antarest/study/business/areas/renewable_management.py
  antarest/study/business/model/renewable_cluster_model.py
  antarest/study/business/table_mode_management.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_renewable_cluster.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_renewable.py
Labels: size/L

#2366 feat(xpansion)!: introduce `create_xpansion_configuration` command
  antarest/core/exceptions.py
  antarest/study/business/model/xpansion_model.py
  antarest/study/business/xpansion_management.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_configuration.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/integration/xpansion_studies_blueprint/test_integration_xpansion.py
  tests/storage/business/test_xpansion_manager.py
Labels: size/XL

#2354 feat(st-storage): add update st storage command
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/model/sts_model.py
  antarest/study/business/table_mode_management.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_st_storage.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/study/business/areas/test_st_storage_management.py
Labels: size/L

#2353 fix(ini): ignore case when performing update and delete of ini files
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/storage/repository/filesystem/test_ini_file_node.py
Labels: size/L

#2373 fix(commands): add missing index on commands table, for performances
  alembic/versions/423fe2c8ee40_add_commandblock_index.py
Labels: size/S

#2369 fix(xpansion): allow matrices normalization
  antarest/study/business/xpansion_management.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/user/expansion/matrix_resources.py
  tests/integration/xpansion_studies_blueprint/test_integration_xpansion.py
Labels: size/M
