Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2025-10, with the labels that each got.

#2741 fix(launcher): fix arguments handling in local launcher
  antarest/launcher/adapters/local_launcher/local_launcher.py
  antarest/launcher/adapters/log_manager.py
  antarest/study/service.py
  tests/launcher/test_local_launcher.py
  tests/storage/test_service.py
Labels: size/L

#2753 refactor(hydro): introduce DAO for allocation
  antarest/study/business/allocation_management.py
  antarest/study/business/model/hydro_allocation_model.py
  antarest/study/dao/api/hydro_dao.py
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/file/file_study_hydro_dao.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/replace_hydro_allocation.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
  tests/study/business/test_allocation_manager.py
  tests/variantstudy/model/command/test_replace_hydro_allocation.py
  tests/variantstudy/test_command_factory.py
Labels: size/XXL

#2746 refactor(ui-studies): update launch dialog
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/HomeView/InformationView/index.tsx
  webapp/src/components/App/Studies/StudiesList/index.tsx
  webapp/src/components/App/shared/studies/StudyActionsMenu.tsx
  webapp/src/components/App/shared/studies/dialogs/LaunchStudyDialog.tsx
  webapp/src/components/App/shared/studies/dialogs/StudyLaunchDialog/Fields.tsx
  webapp/src/components/App/shared/studies/dialogs/StudyLaunchDialog/LauncherMetrics.tsx
  webapp/src/components/App/shared/studies/dialogs/StudyLaunchDialog/StudyList.tsx
  webapp/src/components/App/shared/studies/dialogs/StudyLaunchDialog/index.tsx
  webapp/src/components/App/shared/studies/dialogs/StudyLaunchDialog/utils.ts
  webapp/src/services/api/study.ts
Labels: front-end, size/XXL
