Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2025-05, with the labels that each got.

#2481 chore(release): v2.20.0 into dev
  antarest/__init__.py
  antarest/study/business/allocation_management.py
  docs/CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  tests/integration/test_integration.py
  tests/study/business/test_allocation_manager.py
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Settings/Groups/Header.tsx
  webapp/src/components/App/Settings/Groups/dialog/CreateGroupDialog.tsx
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/index.tsx
  webapp/src/components/App/Settings/Groups/dialog/UpdateGroupDialog.tsx
  webapp/src/components/App/Settings/Groups/dialog/utils.ts
  webapp/src/components/App/Settings/Groups/index.tsx
  webapp/src/components/App/Settings/Tokens/Header.tsx
  webapp/src/components/App/Settings/Tokens/dialog/CreateTokenDialog.tsx
  webapp/src/components/App/Settings/Tokens/dialog/ReadTokenDialog.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenFormDialog/TokenForm.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenFormDialog/index.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenInfoDialog.tsx
  webapp/src/components/App/Settings/Tokens/dialog/utils.ts
  webapp/src/components/App/Settings/Tokens/index.tsx
  webapp/src/components/App/Settings/Users/Header.tsx
  webapp/src/components/App/Settings/Users/dialog/CreateUserDialog.tsx
  webapp/src/components/App/Settings/Users/dialog/UpdateUserDialog.tsx
  webapp/src/components/App/Settings/Users/dialog/UserFormDialog/UserForm.tsx
  webapp/src/components/App/Settings/Users/dialog/UserFormDialog/index.tsx
  webapp/src/components/App/Settings/Users/dialog/utils.ts
  webapp/src/components/App/Settings/Users/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields/TypeConfigFields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Allocation/AllocationField.tsx
  webapp/src/components/common/DataGridForm.tsx
  webapp/src/components/common/Form/index.tsx
Labels: size/XXL

#2480 fix(scan): use workspace and study path as key of missing studies
  antarest/study/model.py
  antarest/study/service.py
  tests/storage/test_service.py
Labels: size/M

#2487 fix(thermal): return `hard coal` group in lower case
  antarest/study/business/model/thermal_cluster_model.py
  tests/integration/study_data_blueprint/test_thermal.py
Labels: size/XS

#2488 fix(desktop): allow users to create empty studies
  requirements.txt
Labels: size/XS

#2484 feat(aggregation): streamed aggregation
  antarest/core/config.py
  antarest/core/serde/matrix_export.py
  antarest/study/business/aggregator_management.py
  antarest/study/storage/df_download.py
  antarest/study/storage/output_service.py
  antarest/study/web/output_blueprint.py
  antarest/study/web/raw_studies_blueprint.py
  docs/developer-guide/install/1-CONFIG.md
  requirements-dev.txt
  requirements-test.txt
  requirements.txt
  tests/core/serde/test_matrix_export.py
  tests/integration/raw_studies_blueprint/test_aggregate_raw_data.py
  tests/storage/test_config.py
  tests/study/business/test_aggregator_manager.py
Labels: size/XL

#2491 same work on groups
  antarest/login/service.py
  tests/login/test_login_service.py
Labels: size/L

#2490 perf(db): remove N+1 requests when getting users and groups list
  antarest/login/ldap.py
  antarest/login/main.py
  antarest/login/repository.py
  antarest/login/service.py
  tests/login/conftest.py
  tests/login/test_login_service.py
Labels: size/L

#2489 fix(bc): fix issue when updating `time_step` via table-mode
  antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
  tests/variantstudy/model/command/test_update_binding_constraints.py
Labels: size/L

#2477 fix(ui-studytree): minor fixes and improvement
  webapp/src/components/App/Studies/StudiesList/Header.tsx
  webapp/src/components/App/Studies/StudyTree/StudyTreeNode.tsx
  webapp/src/components/App/Studies/StudyTree/index.tsx
  webapp/src/components/App/Studies/StudyTree/utils.ts
  webapp/src/components/common/utils/constants.ts
  webapp/src/services/utils/localStorage.ts
Labels: size/L

#2457 fix(desktop): use antares-solver_windows instead of rte-antares--installer-64bits
  scripts/package_antares_web.sh
Labels: size/XS

#2394 feat(workspaces): forbid additional workspaces on desktop
  antarest/core/config.py
  antarest/core/core_blueprint.py
  antarest/study/repository.py
  antarest/study/storage/explorer_service.py
  tests/storage/test_config.py
Labels: size/L

#2466 feat(launcher): support multiple launchers
  antarest/core/config.py
  antarest/launcher/adapters/abstractlauncher.py
  antarest/launcher/adapters/factory_launcher.py
  antarest/launcher/adapters/local_launcher/local_launcher.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/model.py
  antarest/launcher/service.py
  antarest/launcher/web.py
  antarest/tools/admin_lib.py
  docs/developer-guide/install/1-CONFIG.md
  resources/antares-desktop-fs/config.yaml
  resources/application.yaml
  resources/deploy/config.prod.yaml
  resources/deploy/config.yaml
  tests/integration/assets/config.template.yml
  tests/integration/launcher_blueprint/test_launcher_local.py
  tests/integration/launcher_blueprint/test_solver_versions.py
  tests/integration/test_integration.py
  tests/launcher/test_local_launcher.py
  tests/launcher/test_service.py
  tests/launcher/test_slurm_launcher.py
  tests/launcher/test_web.py
  tests/test_resources.py
Labels: size/XXL

#2486 fix(study)!: rename variable for study copy
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/study_storage.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/studies_blueprint.py
  tests/integration/raw_studies_blueprint/test_download_matrices.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/integration/studies_blueprint/test_comments.py
  tests/integration/studies_blueprint/test_disk_usage.py
  tests/integration/studies_blueprint/test_synthesis.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
  tests/integration/study_data_blueprint/test_hydro_inflow_properties.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/test_integration.py
  tests/integration/variant_blueprint/test_thermal_cluster.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/web/test_studies_bp.py
  webapp/src/services/api/study.ts
Labels: size/M

#2494 feat(ui-desktop): show recursive scan checkbox only on desktop
  webapp/src/components/App/Studies/StudiesList/Header.tsx
Labels: size/M

#2498 fix(launcher): fix local launcher unit test
  tests/launcher/test_local_launcher.py
Labels: size/S

#2454 refactor(links): introduce a DAO layer and improve classes design
  antarest/study/business/link_management.py
  antarest/study/business/model/link_model.py
  antarest/study/business/study_interface.py
  antarest/study/business/table_mode_management.py
  antarest/study/dao/__init__.py
  antarest/study/dao/api/__init__.py
  antarest/study/dao/api/link_dao.py
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/file/__init__.py
  antarest/study/dao/file/file_study_dao.py
  antarest/study/dao/file/file_study_link_dao.py
  antarest/study/dao/memory/__init__.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/config/files.py
  antarest/study/storage/rawstudy/model/filesystem/config/link.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_link.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/remove_link.py
  antarest/study/storage/variantstudy/model/command/update_link.py
  antarest/study/storage/variantstudy/variant_command_generator.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_link.py
  tests/integration/study_data_blueprint/test_table_mode.py
  tests/storage/business/test_arealink_manager.py
  tests/storage/business/test_xpansion_manager.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/storage/test_service.py
  tests/variantstudy/model/command/test_create_link.py
  tests/variantstudy/model/command/test_create_link_in_memory.py
  tests/variantstudy/model/command/test_manage_district.py
Labels: size/XXL

#2497 fix(bc): allow updates for bc with a name as an integer
  antarest/core/serde/ini_reader.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/bindingconstraints/bindingconstraints_ini.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  tests/variantstudy/model/command/test_manage_binding_constraints.py
Labels: size/M

#2499 fix(ui-studies): minor workspaces related fixes
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/StudyTree/index.tsx
  webapp/src/services/api/study.ts
Labels: size/S

#2500 fix(import): reduce memory use when importing large files
  antarest/study/web/output_blueprint.py
  antarest/study/web/studies_blueprint.py
Labels: size/S

#2501 fix(user): allow to fetch ldap users
  antarest/login/repository.py
  antarest/login/service.py
  tests/login/test_login_service.py
Labels: size/M

#2495 fix(ui-playlist): some issues
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog/index.tsx
Labels: bug, front-end, size/S

#2506 chore(release): v2.21.0 (2025-05-26)
  antarest/__init__.py
  antarest/login/repository.py
  antarest/login/service.py
  antarest/study/web/output_blueprint.py
  antarest/study/web/studies_blueprint.py
  docs/CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  tests/login/test_login_service.py
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog/index.tsx
Labels: size/L

#2503 fix(desktop): add missing name field to config.yml desktop template
  resources/antares-desktop-fs/config.yaml
Labels: size/XS

#2510 fix(lint): remove obsolete `type: ignore`
  antarest/study/storage/rawstudy/model/filesystem/matrix/date_serializer.py
  requirements-dev.txt
Labels: size/XS

#2502 refactor(thermal)!: introduce the DAO layer for thermal clusters
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/study_interface.py
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/api/thermal_dao.py
  antarest/study/dao/file/file_study_dao.py
  antarest/study/dao/file/file_study_link_dao.py
  antarest/study/dao/file/file_study_thermal_dao.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/storage/rawstudy/model/filesystem/config/thermal.py
  antarest/study/storage/variantstudy/model/command/create_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  antarest/study/storage/variantstudy/model/command/update_thermal_clusters.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_thermal.py
  tests/variantstudy/model/command/test_create_cluster.py
  tests/variantstudy/model/command/test_create_link_in_memory.py
Labels: size/XXL
