Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2025-04, with the labels that each got.

#2434 fix(area): fix bug on allocation and correlation views
  antarest/study/business/allocation_management.py
  antarest/study/business/correlation_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/thermal.py
  tests/integration/study_data_blueprint/test_hydro_allocation.py
  tests/integration/study_data_blueprint/test_hydro_correlation.py
  tests/integration/study_data_blueprint/test_thermal.py
Labels: size/L

#2438 chore(variant): remove obsolete `execute_or_add_commands` method
  antarest/study/business/study_interface.py
  antarest/study/business/utils.py
  antarest/study/service.py
  tests/conftest.py
  tests/conftest_services.py
  tests/core/test_tasks.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/test_service.py
  tests/study/business/test_district_manager.py
  tests/study/storage/rawstudy/test_raw_study_service.py
  tests/study/storage/variantstudy/test_variant_study_service.py
  tests/variantstudy/conftest.py
Labels: size/L

#2405 feat(variant_study): copy variant as raw study
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/studies_blueprint.py
  antarest/study/web/variant_blueprint.py
  tests/integration/test_integration.py
  tests/integration/variant_blueprint/test_variant_manager.py
  tests/storage/business/test_variant_study_service.py
Labels: size/L

#2440 docs: add some docstring to some important database classes
  antarest/study/model.py
  antarest/study/storage/variantstudy/model/dbmodel.py
Labels: size/M

#2427 feat(ui-studies): display the study list in the tree even if folder list is loading
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/StudiesList/Header.tsx
  webapp/src/components/App/Studies/StudyTree/StudyTreeNode.tsx
  webapp/src/components/App/Studies/StudyTree/index.tsx
  webapp/src/components/App/Studies/StudyTree/types.ts
  webapp/src/components/App/Studies/StudyTree/utils.ts
  webapp/src/components/common/TreeItemEnhanced.tsx
  webapp/src/components/common/utils/constants.ts
Labels: front-end, size/L

#2443 fix(ui): theme issues
  webapp/index.html
  webapp/public/assets/img/antarest-logo.png
  webapp/public/assets/img/top-right-background.png
  webapp/public/main.css
  webapp/src/components/App/Singlestudy/explore/Results/index.tsx
  webapp/src/components/App/Tasks/JobTableView.tsx
  webapp/src/components/App/Tasks/LaunchJobLogView.tsx
  webapp/src/components/App/Tasks/index.tsx
  webapp/src/theme/components.ts
Labels: bug, front-end, size/L

#2439 feat(study): copy study with specific path
  antarest/study/common/studystorage.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/studies_blueprint.py
  tests/integration/test_integration.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/web/test_studies_bp.py
Labels: size/M

#2446 fix(raw): raise Exception when modifying expansion folder inside variant
  antarest/study/service.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
Labels: size/S

#2442 fix(ui-storages): disable resize on inflow matrix
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/StorageMatrices.tsx
Labels: size/S

#2441 feat(ui-matrix): add copy paste and keybinds support
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/common/Matrix/components/MatrixActions/index.tsx
  webapp/src/components/common/Matrix/components/MatrixGrid/index.tsx
  webapp/src/components/common/Matrix/hooks/useMatrixMutations.ts
Labels: size/L

#2447 feat(study): copy only selected outputs
  antarest/core/exceptions.py
  antarest/study/common/studystorage.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/studies_blueprint.py
  tests/integration/test_integration.py
  tests/storage/business/test_raw_study_service.py
  tests/storage/web/test_studies_bp.py
Labels: size/L

#2449 refactor(commands): remove apply config
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/create_cluster.py
  antarest/study/storage/variantstudy/model/command/create_district.py
  antarest/study/storage/variantstudy/model/command/create_link.py
  antarest/study/storage/variantstudy/model/command/create_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/create_st_storage.py
  antarest/study/storage/variantstudy/model/command/create_user_resource.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_configuration.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_constraint.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_matrix.py
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/remove_area.py
  antarest/study/storage/variantstudy/model/command/remove_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_district.py
  antarest/study/storage/variantstudy/model/command/remove_link.py
  antarest/study/storage/variantstudy/model/command/remove_multiple_binding_constraints.py
  antarest/study/storage/variantstudy/model/command/remove_renewables_cluster.py
  antarest/study/storage/variantstudy/model/command/remove_st_storage.py
  antarest/study/storage/variantstudy/model/command/remove_user_resource.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_configuration.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_resource.py
  antarest/study/storage/variantstudy/model/command/replace_matrix.py
  antarest/study/storage/variantstudy/model/command/replace_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/update_area_ui.py
  antarest/study/storage/variantstudy/model/command/update_areas_properties.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
  antarest/study/storage/variantstudy/model/command/update_comments.py
  antarest/study/storage/variantstudy/model/command/update_config.py
  antarest/study/storage/variantstudy/model/command/update_district.py
  antarest/study/storage/variantstudy/model/command/update_hydro_management.py
  antarest/study/storage/variantstudy/model/command/update_inflow_structure.py
  antarest/study/storage/variantstudy/model/command/update_link.py
  antarest/study/storage/variantstudy/model/command/update_playlist.py
  antarest/study/storage/variantstudy/model/command/update_raw_file.py
  antarest/study/storage/variantstudy/model/command/update_renewables_clusters.py
  antarest/study/storage/variantstudy/model/command/update_scenario_builder.py
  antarest/study/storage/variantstudy/model/command/update_st_storages.py
  antarest/study/storage/variantstudy/model/command/update_thermal_clusters.py
  antarest/study/storage/variantstudy/model/command/update_xpansion_settings.py
  antarest/study/storage/variantstudy/model/command/xpansion_common.py
  antarest/study/storage/variantstudy/variant_command_generator.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/variantstudy/model/command/test_create_st_storage.py
  tests/variantstudy/model/command/test_remove_st_storage.py
  tests/variantstudy/model/command/test_update_binding_constraints.py
Labels: size/XL

#2453 fix(ui-matrix): disable keybinds on read-only matrices
  webapp/src/components/common/Matrix/components/MatrixGrid/index.tsx
Labels: size/XS

#2458 fix(ui-adq-patch): fix display of `includeHurdleCostCsr` switch
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/Fields.tsx
Labels: size/XS

#2461 fix(ui-matrix): ensure consistent column sizing when switching between matrices
  webapp/src/components/common/Matrix/components/MatrixGrid/index.tsx
  webapp/src/components/common/Matrix/index.tsx
Labels: size/XS

#2462 fix(aggregation): allow aggregation for variants
  antarest/study/storage/abstract_storage_service.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/output_blueprint.py
  tests/integration/raw_studies_blueprint/test_aggregate_raw_data.py
  tests/study/business/test_aggregator_manager.py
Labels: size/M

#2456 fix(ui-matrix): add aggregates columns calculation on matrix resize
  webapp/src/components/common/Matrix/components/MatrixActions/MatrixActions.test.tsx
  webapp/src/components/common/Matrix/components/MatrixResize.tsx
  webapp/src/components/common/Matrix/context/MatrixContext.tsx
  webapp/src/components/common/Matrix/index.tsx
Labels: size/S

#2450 feat(matrix): support matrices with headers inside the matrixstore
  alembic/versions/9ba7fc46d4a0_add_version_to_matrices.py
  antarest/core/config.py
  antarest/matrixstore/exceptions.py
  antarest/matrixstore/in_memory.py
  antarest/matrixstore/migration_script.py
  antarest/matrixstore/model.py
  antarest/matrixstore/parsing.py
  antarest/matrixstore/repository.py
  antarest/matrixstore/service.py
  antarest/matrixstore/uri_resolver_service.py
  antarest/matrixstore/web.py
  antarest/study/business/matrix_management.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/variantstudy/business/matrix_constants/common.py
  antarest/study/storage/variantstudy/business/matrix_constants/hydro/v6.py
  antarest/study/storage/variantstudy/business/matrix_constants/hydro/v7.py
  antarest/study/storage/variantstudy/business/matrix_constants/link/v7.py
  antarest/study/storage/variantstudy/business/matrix_constants/link/v8.py
  antarest/study/storage/variantstudy/business/matrix_constants/prepro.py
  antarest/study/storage/variantstudy/business/matrix_constants/thermals/prepro.py
  antarest/study/storage/variantstudy/business/matrix_constants_generator.py
  antarest/study/storage/variantstudy/business/utils.py
  tests/integration/raw_studies_blueprint/test_download_matrices.py
  tests/integration/test_integration.py
  tests/matrixstore/conftest.py
  tests/matrixstore/test_in_memory_matrix_service.py
  tests/matrixstore/test_matrix_garbage_collector.py
  tests/matrixstore/test_repository.py
  tests/matrixstore/test_service.py
  tests/matrixstore/test_web.py
  tests/storage/business/test_url_resolver_service.py
  tests/storage/business/test_xpansion_manager.py
  tests/storage/repository/filesystem/matrix/test_matrix_node.py
  tests/study/storage/variantstudy/business/test_matrix_constants_generator.py
  tests/variantstudy/model/command/test_create_cluster.py
  tests/variantstudy/model/command/test_create_st_storage.py
  tests/variantstudy/model/command/test_create_xpansion_resource.py
  tests/variantstudy/model/command/test_replace_matrix.py
  tests/variantstudy/model/test_variant_model.py
Labels: size/XXL

#2460 fix(ui-digest): make first column fixed
  webapp/src/components/common/DataGridViewer.tsx
  webapp/src/components/common/Matrix/shared/types.ts
  webapp/src/components/common/Matrix/shared/utils.ts
  webapp/src/components/common/dialogs/DigestDialog/DigestMatrix.tsx
  webapp/src/utils/numberUtils.ts
  webapp/src/utils/validation/number.ts
Labels: size/M

#2455 fix(ui-clusters): handle area/cluster navigation by properly updating URL segments
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/AreasTab.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableConfig/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalConfig/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/index.tsx
  webapp/src/components/App/Singlestudy/explore/TabWrapper.tsx
  webapp/src/components/common/buttons/BackButton.tsx
  webapp/src/hooks/useNavigateOnCondition.ts
Labels: bug, front-end, size/L

#2465 fix(matrixstore): ensure we can read legacy null matrix
  antarest/matrixstore/parsing.py
  antarest/matrixstore/repository.py
  antarest/matrixstore/service.py
  tests/matrixstore/test_repository.py
Labels: size/M

#2468 fix(ui-settings): style issues in form dialogs
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Settings/Groups/Header.tsx
  webapp/src/components/App/Settings/Groups/dialog/CreateGroupDialog.tsx
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/GroupForm.tsx
  webapp/src/components/App/Settings/Groups/dialog/GroupFormDialog/index.tsx
  webapp/src/components/App/Settings/Groups/dialog/UpdateGroupDialog.tsx
  webapp/src/components/App/Settings/Groups/dialog/utils.ts
  webapp/src/components/App/Settings/Groups/index.tsx
  webapp/src/components/App/Settings/Tokens/Header.tsx
  webapp/src/components/App/Settings/Tokens/dialog/CreateTokenDialog.tsx
  webapp/src/components/App/Settings/Tokens/dialog/ReadTokenDialog.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenFormDialog/TokenForm.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenFormDialog/index.tsx
  webapp/src/components/App/Settings/Tokens/dialog/TokenInfoDialog.tsx
  webapp/src/components/App/Settings/Tokens/dialog/utils.ts
  webapp/src/components/App/Settings/Tokens/index.tsx
  webapp/src/components/App/Settings/Users/Header.tsx
  webapp/src/components/App/Settings/Users/dialog/CreateUserDialog.tsx
  webapp/src/components/App/Settings/Users/dialog/UpdateUserDialog.tsx
  webapp/src/components/App/Settings/Users/dialog/UserFormDialog/UserForm.tsx
  webapp/src/components/App/Settings/Users/dialog/UserFormDialog/index.tsx
  webapp/src/components/App/Settings/Users/dialog/utils.ts
  webapp/src/components/App/Settings/Users/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields/TypeConfigFields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/Fields/index.tsx
  webapp/src/components/common/DataGridForm.tsx
  webapp/src/components/common/Form/index.tsx
Labels: bug, front-end, size/XXL

#2464 fix(hydro): allow negative values for hydro allocation coefficients
  antarest/study/business/allocation_management.py
  tests/study/business/test_allocation_manager.py
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Allocation/AllocationField.tsx
Labels: size/M
