Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2025-01, with the labels that each got.

#2275 fix(ui): fix untranslated message
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
  webapp/vite.config.ts
Labels: size/XS

#2281 fix(link): add comment attribute in link that was missing and causing an 422 error
  antarest/study/business/model/link_model.py
  tests/integration/study_data_blueprint/test_link.py
  tests/integration/study_data_blueprint/test_table_mode.py
  tests/integration/test_integration.py
  tests/storage/business/test_arealink_manager.py
Labels: size/S

#2287 fix(matrix): remove columns full of `NaN` inside matrices at the import
  antarest/study/service.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
Labels: size/XS

#2286 fix(matrix): return default empty matrix even when called with formatted=False
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  tests/storage/integration/test_STA_mini.py
  tests/storage/repository/filesystem/matrix/test_matrix_node.py
Labels: size/L

#2279 fix(list_dir): check permissions and consider workspace filters config
  antarest/study/storage/explorer_service.py
  antarest/study/storage/rawstudy/watcher.py
  antarest/study/storage/utils.py
  tests/storage/business/test_explorer_service.py
Labels: size/M

#2292 fix(raw): change bytes serialization when formatting is False
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  tests/storage/integration/test_STA_mini.py
Labels: size/S

#2291 fix(desktop): fixes calendar issue when reading matrices on Linux
  antarest/study/storage/matrix_profile.py
  antarest/study/storage/utils.py
Labels: size/S

#2293 fix(disk-usage): suppress exceptions
  antarest/study/service.py
  tests/study/test_service.py
Labels: size/M

#2290 feat(variant): add reason when variant generation fails
  antarest/core/tasks/service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/core/test_tasks.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/storage/business/test_variant_study_service.py
Labels: size/M

#2284 chore(commands): fix user name display in commands
  antarest/core/tasks/service.py
  antarest/login/service.py
  antarest/login/utils.py
  antarest/main.py
  antarest/study/business/utils.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/variant_blueprint.py
  tests/core/test_tasks.py
  tests/integration/test_integration_token_end_to_end.py
  tests/storage/business/test_arealink_manager.py
  tests/study/storage/variantstudy/test_variant_study_service.py
Labels: size/L

#2251 feat(launcher): allow local launcher to work with xpress
  antarest/core/config.py
  antarest/launcher/adapters/abstractlauncher.py
  antarest/launcher/adapters/local_launcher/local_launcher.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  antarest/launcher/service.py
  antarest/study/storage/rawstudy/model/filesystem/root/filestudytree.py
  antarest/study/storage/rawstudy/model/filesystem/root/logs.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/output.py
  docs/developer-guide/install/1-CONFIG.md
  resources/antares-desktop-fs/config.yaml
  resources/antares-desktop-fs/local_workspace/.placeholder
  resources/deploy/config.yaml
  scripts/package_antares_web.sh
  tests/launcher/test_local_launcher.py
  tests/storage/test_service.py
Labels: size/L

#2295 feat(bc): add constraint duplication endpoint
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/areas/thermal_management.py
  antarest/study/business/binding_constraint_management.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
Labels: size/L

#2288 feat(ui-api, studies): optimize studies listing
  antarest/study/model.py
  antarest/study/storage/explorer_service.py
  antarest/study/storage/utils.py
  antarest/study/web/explorer_blueprint.py
  tests/integration/explorer_blueprint/test_explorer.py
  tests/storage/business/test_explorer_service.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Studies/SideNav.tsx
  webapp/src/components/App/Studies/StudiesList/index.tsx
  webapp/src/components/App/Studies/StudyTree.tsx
  webapp/src/components/App/Studies/StudyTree/StudyTreeNode.tsx
  webapp/src/components/App/Studies/StudyTree/__test__/fixtures.ts
  webapp/src/components/App/Studies/StudyTree/__test__/utils.test.ts
  webapp/src/components/App/Studies/StudyTree/index.tsx
  webapp/src/components/App/Studies/StudyTree/types.ts
  webapp/src/components/App/Studies/StudyTree/utils.ts
  webapp/src/components/App/Studies/utils.ts
  webapp/src/redux/ducks/studies.ts
  webapp/src/redux/selectors.ts
  webapp/src/services/api/study.ts
Labels: size/XXL

#2289 feat(ui-tablemode,ui-playlist): replace Handsontable by Glide Data Grid
  webapp/index.html
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/Commands/Edition/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/Table.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioPlaylistDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/TimeSeriesManagement/index.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Folder.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Text.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Unsupported.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/index.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/index.tsx
  webapp/src/components/App/Singlestudy/explore/common/ListElement.tsx
  webapp/src/components/common/DataGrid.tsx
  webapp/src/components/common/DataGridForm.tsx
  webapp/src/components/common/Form/index.tsx
  webapp/src/components/common/Form/types.ts
  webapp/src/components/common/Matrix/components/MatrixGrid/MatrixGrid.test.tsx
  webapp/src/components/common/Matrix/components/MatrixGrid/index.tsx
  webapp/src/components/common/Matrix/components/MatrixGridSynthesis/index.tsx
  webapp/src/components/common/Matrix/hooks/useColumnMapping/index.ts
  webapp/src/components/common/Matrix/hooks/useGridCellContent/index.ts
  webapp/src/components/common/Matrix/hooks/useMatrix/index.ts
  webapp/src/components/common/Matrix/hooks/useMatrixPortal/index.ts
  webapp/src/components/common/Matrix/hooks/useMatrixPortal/useMatrixPortal.test.tsx
  webapp/src/components/common/Matrix/index.tsx
  webapp/src/components/common/TableMode.tsx
  webapp/src/components/common/dialogs/DatabaseUploadDialog/components/MatrixContent.tsx
  webapp/src/components/common/dialogs/DigestDialog.tsx
  webapp/src/components/common/page/EmptyView.tsx
  webapp/src/components/common/utils/UsePromiseCond.tsx
  webapp/src/hooks/useCloseFormSecurity.ts
  webapp/src/hooks/useConfirm.ts
  webapp/src/services/api/studies/config/playlist/constants.ts
  webapp/src/services/api/studies/config/playlist/index.ts
  webapp/src/services/api/studies/config/playlist/types.ts
Labels: front-end, size/XXL, feature request

#2298 feat: add an endpoint to allow multiple deletion of binding constrain…
  antarest/study/business/binding_constraint_management.py
  antarest/study/storage/variantstudy/business/command_reverter.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/binding_constraint_utils.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_binding_constraint.py
  antarest/study/storage/variantstudy/model/command/remove_multiple_binding_constraints.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#2306 fix(study-tree): fix tooltip message key
  webapp/src/components/App/Studies/StudiesList/index.tsx
Labels: size/XS

#2305 fix(matrix): allow odd matrix format when importing
  antarest/core/exceptions.py
  antarest/study/service.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
Labels: size/M

#2309 feat(ui-hooks): update useSafeMemo and useUpdatedRef
  webapp/eslint.config.js
  webapp/src/components/App/Singlestudy/FreezeStudy.tsx
  webapp/src/components/common/Form/useFormApiPlus.ts
  webapp/src/components/common/Form/useFormUndoRedo.ts
  webapp/src/components/common/GroupedDataTable/index.tsx
  webapp/src/components/common/JSONEditor/index.tsx
  webapp/src/components/common/TableForm/index.tsx
  webapp/src/hooks/useAutoUpdateRef.ts
  webapp/src/hooks/useBlocker.ts
  webapp/src/hooks/useConfirm.ts
  webapp/src/hooks/useMemoLocked.ts
  webapp/src/hooks/usePromiseHandler.ts
  webapp/src/hooks/useSafeMemo.ts
  webapp/src/hooks/useUpdatedRef.ts
Labels: front-end, size/L

#2304 ci(github): add PR title lint job
  .github/workflows/commitlint.yml
  .github/workflows/license-header.yml
  .github/workflows/pr-title.yml
  commitlint.config.js
  package-lock.json
  package.json
Labels: size/M

#2300 feat(ui-studies): sort study tree folders
  webapp/src/components/App/Studies/StudyTree/StudyTreeNode.tsx
Labels: size/S

#2312 refactor(ui): disable TS null assertion and update the code that use it
  webapp/eslint.config.js
  webapp/src/components/App/Singlestudy/FreezeStudy.tsx
  webapp/src/components/App/Singlestudy/explore/Debug/index.tsx
  webapp/src/components/App/Singlestudy/index.tsx
  webapp/src/components/common/buttons/DownloadButton.tsx
  webapp/src/services/api/tasks/index.ts
  webapp/src/services/api/tasks/types.ts
Labels: front-end, size/M

#2317 fix: fix a bug that would occurs after deleting multiple bc
  antarest/study/storage/variantstudy/model/command/remove_multiple_binding_constraints.py
  tests/integration/study_data_blueprint/test_binding_constraints.py
Labels: size/S

#2319 feat(commitlint): add new rules for scope
  commitlint.config.js
Labels: size/S

#2320 fix(ui-tablemode): adjust the size of the column with the initial data
  webapp/src/components/common/DataGrid.tsx
  webapp/src/components/common/DataGridForm.tsx
  webapp/src/components/common/TableMode.tsx
  webapp/src/utils/domUtils.ts
Labels: bug, front-end, size/L

#2321 fix(ui-tablemode): prevent small values from being cut off and remove empty space at the bottom
  webapp/src/components/common/DataGrid.tsx
  webapp/src/components/common/DataGridForm.tsx
  webapp/src/utils/dataGridUtils.ts
Labels: front-end, size/M

#2324 fix(ui-commons): keep auto size for DataGrid
  webapp/src/components/common/DataGrid.tsx
Labels: size/S
