Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2025-08, with the labels that each got.

#2630 fix(matrix): don't raise when optional matrices don't exist
  antarest/matrixstore/matrix_uri_mapper.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/area/st_storage/st_storage.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/thermal/series/area/thermal/thermal.py
  tests/storage/business/test_optional_matrices.py
Labels: size/L

#2632 feat(matrix): when denormalizing, only write content if it isn't the default one
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  tests/storage/repository/filesystem/matrix/test_matrix_node.py
  tests/study/storage/variantstudy/test_snapshot_generator.py
Labels: size/S

#2624 feat(matrix): add arrow format for input matrices inside GET `/raw` endpoint
  antarest/core/exceptions.py
  antarest/study/service.py
  antarest/study/web/raw_studies_blueprint.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
  tests/storage/web/test_studies_bp.py
Labels: size/L

#2633 chore(node): clean normalization / denormalization methods
  antarest/study/storage/rawstudy/model/filesystem/ini_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/inode.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/matrix.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/output_series_matrix.py
  antarest/study/storage/rawstudy/model/filesystem/raw_file_node.py
  antarest/study/storage/rawstudy/model/filesystem/root/input/areas/list.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/output.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/mcall/grid.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/mcall/synthesis.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/ts_numbers/ts_numbers_data.py
  tests/storage/repository/filesystem/test_lazy_node.py
  tests/storage/repository/filesystem/utils.py
Labels: size/M

#2642 chore(release): v2.23.0
  antarest/__init__.py
  docs/CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
Labels: size/M

#2636 feat(scenario-builder): support sts inflows
  antarest/study/business/scenario_builder_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/ruleset_matrices.py
  antarest/study/storage/rawstudy/model/filesystem/root/settings/scenariobuilder.py
  tests/storage/repository/filesystem/config/test_ruleset_matrices.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/Table.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/utils.ts
Labels: size/L

#2645 fix(general): remove `building_mode` from the generaldata.ini
  antarest/study/storage/rawstudy/model/filesystem/config/general.py
  tests/variantstudy/model/command/test_update_general_config.py
Labels: size/S

#2646 fix(sts): make constraints matrices optional
  antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/constraints/area/st_storage/__init__.py
Labels: size/XS

#2648 fix(table-mode): remove `cluster` column for additional constraints
  webapp/src/services/api/studies/tableMode/constants.ts
Labels: size/XS

#2650 feat(ui-sts): add additional constraints matrix
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/AdditionalConstraints/ConstraintForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/AdditionalConstraints/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/index.tsx
Labels: size/L

#2635 refactor(thematic-trimming): introduce DAO and associated command
  antarest/study/business/model/thematic_trimming_model.py
  antarest/study/business/thematic_trimming_management.py
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/api/thematic_trimming_dao.py
  antarest/study/dao/file/file_study_dao.py
  antarest/study/dao/file/file_study_thematic_trimming_dao.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/storage/rawstudy/model/filesystem/config/thematic_trimming.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_thematic_trimming.py
  antarest/study/web/study_data_blueprint.py
  tests/storage/business/test_config_manager.py
  tests/variantstudy/model/command/test_update_thematic_trimming.py
  tests/variantstudy/test_command_factory.py
Labels: size/XL

#2637 refactor(xpansion): introduce DAO and new class design for settings
  antarest/study/business/model/xpansion_model.py
  antarest/study/business/xpansion_management.py
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/api/xpansion_dao.py
  antarest/study/dao/file/file_study_xpansion_dao.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/service.py
  antarest/study/storage/rawstudy/model/filesystem/config/xpansion.py
  antarest/study/storage/variantstudy/model/command/update_xpansion_settings.py
  antarest/study/storage/variantstudy/model/command/xpansion_common.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/integration/xpansion_studies_blueprint/test_integration_xpansion.py
  tests/storage/business/test_xpansion_manager.py
Labels: size/XL

#2640 refactor(settings): implement DAO for timeseries configuration
  antarest/study/business/model/config/timeseries_config_model.py
  antarest/study/business/timeseries_config_management.py
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/api/timeseries_config_dao.py
  antarest/study/dao/file/file_study_dao.py
  antarest/study/dao/file/file_study_timseries_config_dao.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/update_timeseries_config.py
  antarest/study/web/study_data_blueprint.py
  tests/storage/business/test_timeseries_config_manager.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#2641 perf(matrix): write matrices as integers when possible
  antarest/core/serde/matrix_export.py
  antarest/matrixstore/matrix_uri_mapper.py
  antarest/matrixstore/parsing.py
  antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
  tests/integration/raw_studies_blueprint/test_download_matrices.py
Labels: size/S

#2657 fix(migration): fixes migration for sqlite
  alembic/versions/d2942741ae68_drop_patch_data.py
Labels: size/XS

#2656 fix(thematic-trimming): regression introduced by the DAO
  antarest/study/business/model/thematic_trimming_model.py
  antarest/study/storage/rawstudy/model/filesystem/config/thematic_trimming.py
  tests/storage/business/test_config_manager.py
  tests/variantstudy/model/command/test_update_thematic_trimming.py
Labels: size/L

#2583 feat(matrix_usage_provider): add usage provider
  antarest/launcher/extensions/adequacy_patch/extension.py
  antarest/matrixstore/in_memory.py
  antarest/matrixstore/matrix_garbage_collector.py
  antarest/matrixstore/matrix_usage_provider.py
  antarest/matrixstore/model.py
  antarest/matrixstore/service.py
  antarest/service_creator.py
  antarest/singleton_services.py
  antarest/study/business/link_management.py
  antarest/study/storage/rawstudy/raw_study_matrix_usage_provider.py
  antarest/study/storage/rawstudy/raw_study_service.py
  antarest/study/storage/variantstudy/business/matrix_constants/matrix_constants_usage_provider.py
  antarest/study/storage/variantstudy/business/matrix_constants_generator.py
  antarest/study/storage/variantstudy/command_matrix_usage_provider.py
  antarest/study/storage/variantstudy/variant_study_service.py
  tests/matrixstore/test_in_memory_matrix_service.py
  tests/matrixstore/test_matrix_garbage_collector.py
  tests/matrixstore/test_matrix_usage_providers.py
  tests/variantstudy/test_command_factory.py
Labels: size/XL

#2661 fix(st-storage): fix issue when reading `hours` field for additional constraints
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  tests/variantstudy/model/command/test_update_st_storage_additional_constraints.py
Labels: size/M

#2662 fix(matrix): fix missing import in matrix service
  antarest/matrixstore/matrix_garbage_collector.py
  antarest/matrixstore/service.py
  antarest/service_creator.py
  tests/matrixstore/test_matrix_garbage_collector.py
Labels: size/M

#2653 refactor(xpansion): introduce DAO for resources
  antarest/core/exceptions.py
  antarest/study/business/model/xpansion_model.py
  antarest/study/business/xpansion_management.py
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/api/xpansion_dao.py
  antarest/study/dao/file/file_study_xpansion_dao.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/storage/rawstudy/model/filesystem/config/xpansion.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_configuration.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_constraint.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_matrix.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_configuration.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_resource.py
  antarest/study/storage/variantstudy/model/command/update_xpansion_settings.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/storage/business/test_xpansion_manager.py
  tests/variantstudy/model/command/test_remove_xpansion_resource.py
Labels: size/XL

#2660 fix(raw): fix getting link output data
  antarest/study/service.py
  tests/integration/raw_studies_blueprint/test_fetch_raw_data.py
Labels: size/S

#2664 feat(matrixstore): add a retention time inside the garbage collector
  antarest/core/config.py
  antarest/matrixstore/matrix_garbage_collector.py
  antarest/service_creator.py
  docs/developer-guide/install/1-CONFIG.md
  tests/matrixstore/test_matrix_garbage_collector.py
Labels: size/M

#2674 fix(ui-sts): preserve active tab when saving a matrix
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/StorageForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/index.tsx
  webapp/src/components/App/index.tsx
Labels: bug, front-end, size/M

#2676 fix(ui): preserve tab state by passing ReactNode to TabsView content
  webapp/src/components/App/Settings/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/StorageMatrices.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalConfig/ThermalMatrices.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkConfig/LinkMatrices.tsx
  webapp/src/components/common/TabsView.tsx
  webapp/src/components/common/dialogs/DigestDialog/DigestTabs.tsx
Labels: bug, front-end, size/L

#2669 fix(ui-optimization): add new options for 'exportMps' field
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/constants.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/utils.ts
  webapp/src/services/api/studies/config/optimization/adapters.ts
  webapp/src/services/api/studies/config/optimization/index.ts
  webapp/src/services/api/studies/config/optimization/types.ts
  webapp/src/utils/booleanUtils.ts
  webapp/src/utils/tsUtils.ts
Labels: bug, front-end, size/XL

#2665 refactor(dao): use dao inside the generate thermal timeseries command
  antarest/study/service.py
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  tests/core/test_tasks.py
Labels: size/L

#2681 feat(scenariobuilder): handle storages additional constraints
  antarest/core/utils/dict_utils.py
  antarest/study/business/model/scenario_builder_model.py
  antarest/study/business/model/study_index.py
  antarest/study/business/scenario_builder_management.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/scenario_builder.py
  antarest/study/web/views/scenario_builder_views.py
  tests/integration/study_data_blueprint/test_scenario_builder.py
  tests/storage/repository/filesystem/config/test_scenario_builder.py
  tests/study/business/test_scenario_builder_model.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#2685 refactor(comments): introduce dao
  antarest/study/dao/api/study_dao.py
  antarest/study/dao/file/file_study_dao.py
  antarest/study/dao/memory/in_memory_study_dao.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/command_factory.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/replace_comments.py
  antarest/study/web/studies_blueprint.py
  tests/storage/test_service.py
  tests/variantstudy/model/command/test_update_comments.py
  tests/variantstudy/test_command_factory.py
Labels: size/L

#2687 feat(ui-scenario): add sts constraints scenario builder UI
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/Table.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/adapters.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/services.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/types.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/utils.ts
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/withAreas.tsx
Labels: size/XL

#2689 fix(matrix-gc): reduce matrix gc memory usage
  antarest/matrixstore/matrix_usage_provider.py
  antarest/matrixstore/service.py
  antarest/study/storage/rawstudy/raw_study_matrix_usage_provider.py
  antarest/study/storage/variantstudy/business/matrix_constants/matrix_constants_usage_provider.py
  antarest/study/storage/variantstudy/command_matrix_usage_provider.py
  tests/matrixstore/test_matrix_usage_providers.py
Labels: size/M

#2691 fix(scenario): fix scenario builder API regressions
  antarest/study/business/model/sts_model.py
  antarest/study/business/scenario_builder_management.py
  antarest/study/dao/file/file_study_st_storage_dao.py
  antarest/study/storage/rawstudy/model/filesystem/config/model.py
  antarest/study/storage/rawstudy/model/filesystem/config/scenario_builder.py
  tests/integration/study_data_blueprint/test_scenario_builder.py
  tests/storage/repository/filesystem/config/test_config_files.py
  tests/storage/repository/filesystem/config/test_scenario_builder.py
  tests/variantstudy/model/command/test_create_st_storage.py
  tests/variantstudy/model/command/test_remove_st_storage.py
Labels: size/L
