Repository AntaresSimulatorTeam/AntaREST, pull requests merged in 2025-07, with the labels that each got.

#2545 feat(run): remove processing of `other_options`
  antarest/launcher/adapters/local_launcher/local_launcher.py
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  requirements.txt
  tests/launcher/test_local_launcher.py
  tests/launcher/test_slurm_launcher.py
Labels: size/L

#2560 fix(launcher): forbid single quotes in `other_options`
  antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
  tests/launcher/test_slurm_launcher.py
Labels: size/S

#2562 feat(scenario_builder): handle `hydro final levels` inside the front-end
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ScenarioBuilderDialog/utils.ts
Labels: size/XS

#2563 fix(output): dont scan whole output dir recursively
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/simulation.py
Labels: size/XS

#2566 fix(ui-commons): remove the column name from the copy on DataGrid
  webapp/src/components/common/DataGrid.tsx
Labels: size/XS

#2567 feat(thematic-trimming): add value to unselect constraints results
  antarest/study/business/model/thematic_trimming_model.py
  antarest/study/storage/rawstudy/model/filesystem/config/thematic_trimming.py
  tests/integration/studies_blueprint/test_study_settings.py
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
  webapp/src/services/api/studies/config/thematicTrimming/types.ts
Labels: size/S

#2570 fix(clusters): perform whole data validation before modifying files
  antarest/study/storage/variantstudy/model/command/update_renewables_clusters.py
  antarest/study/storage/variantstudy/model/command/update_st_storages.py
  antarest/study/storage/variantstudy/model/command/update_thermal_clusters.py
  tests/variantstudy/model/command/test_update_renewable_cluster.py
  tests/variantstudy/model/command/test_update_short_term_storage.py
  tests/variantstudy/model/command/test_update_thermal_cluster.py
Labels: size/M

#2572 v2.22.1
  antarest/__init__.py
  antarest/main.py
  antarest/service_creator.py
  antarest/study/business/model/thematic_trimming_model.py
  antarest/study/storage/rawstudy/model/filesystem/config/thematic_trimming.py
  antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/simulation.py
  docs/CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
  webapp/src/components/common/DataGrid.tsx
  webapp/src/services/api/studies/config/thematicTrimming/types.ts
Labels: size/M

#2522 feat(matrix): add advanced filtering and bulk editing system
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/utils.ts
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/ResultFilters.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/common/Matrix/components/FilterableMatrixGrid.tsx
  webapp/src/components/common/Matrix/components/MatrixActions/MatrixActions.test.tsx
  webapp/src/components/common/Matrix/components/MatrixActions/index.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/ColumnFilter.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/MultiRowFilter.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/Operations.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/RowFilter.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/SelectionSummary.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/__tests__/hourIndexing.test.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/components/ChipSelector.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/components/FilterControls.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/components/ListFilterControl.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/components/RangeFilterControl.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/components/TemporalFilterRenderer.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/constants.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/hooks/__tests__/useFilteredData.test.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/hooks/useFilterControls.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/hooks/useFilteredData.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/hooks/useMatrixFilter.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/hooks/useOperationControls.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/hooks/useTemporalData.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/index.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/styles.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/types.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/utils/__tests__/filterCombination.test.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/utils/dateUtils.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/utils/index.ts
  webapp/src/components/common/Matrix/components/MatrixGrid/index.tsx
  webapp/src/components/common/Matrix/components/MatrixResize.tsx
  webapp/src/components/common/Matrix/context/MatrixContext.tsx
  webapp/src/components/common/Matrix/hooks/useColumnMapping/__tests__/useColumnMapping.test.ts
  webapp/src/components/common/Matrix/hooks/useGridCellContent/__tests__/utils.ts
  webapp/src/components/common/Matrix/hooks/useMatrixData.ts
  webapp/src/components/common/Matrix/index.tsx
  webapp/src/components/common/page/ViewWrapper.tsx
  webapp/src/utils/date/constants.ts
  webapp/src/utils/date/dateUtils.ts
  webapp/src/utils/date/matrixDateUtils.ts
Labels: size/XXL

#2574 fix(matrix-filter): incorrect callback signatures for column filter controls
  webapp/src/components/common/Matrix/components/MatrixFilter/ColumnFilter.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/RowFilter.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/hooks/useFilterControls.ts
Labels: size/L

#2577 feat(storage): add coherence checks for v9.2
  antarest/core/exceptions.py
  antarest/study/business/areas/st_storage_management.py
  antarest/study/business/model/sts_model.py
  antarest/study/storage/rawstudy/model/filesystem/config/st_storage.py
  antarest/study/storage/variantstudy/model/command/update_st_storages.py
  tests/integration/study_data_blueprint/test_st_storage.py
  tests/integration/study_data_blueprint/test_table_mode.py
  tests/variantstudy/model/command/test_create_st_storage.py
  tests/variantstudy/model/command/test_update_short_term_storage.py
Labels: size/M

#2587 build(dependencies): bump antares-launcher to v1.4.5
  requirements.txt
Labels: size/XS

#2591 refactor(ui-studies): update StudyPathFE pre-validation
  webapp/src/components/App/Singlestudy/explore/Debug/Data/Folder/CreateFolderDialog.tsx
  webapp/src/components/App/shared/studies/StudyPathFE.tsx
  webapp/src/components/App/shared/studies/dialogs/CopyStudyDialog.tsx
  webapp/src/components/App/shared/studies/dialogs/MoveStudyDialog.tsx
  webapp/src/utils/studiesUtils.ts
Labels: front-end, size/M

#2561 feat(ui-studies): add select/deselect all in outputs fields in copy dialog
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/en/main.json
  webapp/public/locales/fr/main.json
  webapp/src/components/App/shared/studies/dialogs/CopyStudyDialog.tsx
  webapp/src/components/common/Form/useFormApiPlus.ts
  webapp/src/components/common/fieldEditors/CheckboxesTagsFE.tsx
  webapp/src/components/common/fieldEditors/ListFE/index.tsx
  webapp/src/components/common/fieldEditors/NewSelectFE.tsx
  webapp/src/components/common/fieldEditors/NumberFE.tsx
  webapp/src/components/common/fieldEditors/PasswordFE.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/hoc/reactHookFormSupport.tsx
Labels: front-end, size/L

#2575 feat(desktop): ui improvement
  antarest/study/model.py
  antarest/study/service.py
  antarest/study/storage/explorer_service.py
  antarest/study/web/explorer_blueprint.py
  tests/integration/explorer_blueprint/test_explorer.py
  tests/storage/business/test_explorer_service.py
  tests/storage/test_service.py
  webapp/src/components/App/Container/index.tsx
  webapp/src/components/App/Settings/index.tsx
  webapp/src/components/App/Studies/StudyTree/StudyTreeNode.tsx
  webapp/src/components/App/Studies/StudyTree/__test__/utils.test.ts
  webapp/src/components/App/Studies/StudyTree/index.tsx
  webapp/src/components/App/Studies/StudyTree/types.ts
  webapp/src/components/App/Studies/StudyTree/utils.ts
  webapp/src/hooks/useAppMode.ts
  webapp/src/redux/ducks/studies.ts
  webapp/src/redux/middlewares/localStorageMiddleware.ts
  webapp/src/services/api/study.ts
  webapp/src/services/utils/localStorage.ts
  webapp/src/services/webSocket/types.ts
Labels: size/L

#2586 feat(matrix): add endpoint to normalize studies
  antarest/core/exceptions.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/variant_study_service.py
  antarest/study/web/studies_blueprint.py
  tests/integration/studies_blueprint/test_normalization.py
Labels: size/L

#2564 fix(ui-results): resolve variant data display, infinite loops, and state inconsistencies
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/components/ResultFilters.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/components/ResultItemSelector.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/components/ResultMatrixViewer.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/components/SynthesisViewer.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/index.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/utils.ts
  webapp/src/components/App/Singlestudy/explore/Results/hooks/useStudyOutput.ts
  webapp/src/components/App/Singlestudy/explore/Results/index.tsx
  webapp/src/services/api/study.ts
Labels: size/XXL

#2595 feat(ui-sts): allow in study >= 9.2 to see the legacy group list in group text field
  webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/index.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/StorageForm.tsx
  webapp/src/components/App/Studies/HeaderActions/index.tsx
  webapp/src/components/App/shared/studies/StudyPathFE.tsx
  webapp/src/components/common/GroupedDataTable/CreateDialog.tsx
  webapp/src/components/common/fieldEditors/SearchFE.tsx
  webapp/src/components/common/fieldEditors/StringFE.tsx
  webapp/src/hoc/reactHookFormSupport.tsx
Labels: front-end, size/L, feature request

#2596 fix(xpansion): forbid capacity deletion if referenced inside a candidate
  antarest/study/storage/variantstudy/model/command/remove_xpansion_resource.py
  tests/variantstudy/model/command/test_remove_xpansion_resource.py
Labels: size/M

#2601 fix(xpansion): forbid candidate deletion when referenced in sensitivity
  antarest/core/exceptions.py
  antarest/study/business/xpansion_management.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/replace_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/xpansion_common.py
  antarest/study/web/xpansion_studies_blueprint.py
  tests/variantstudy/model/command/test_xpansion_candidates.py
Labels: size/M

#2606 perf(ui-matrix-filter): remove date parsing
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/components/ResultMatrixViewer.tsx
  webapp/src/components/common/Matrix/components/FilterableMatrixGrid.tsx
  webapp/src/components/common/Matrix/components/MatrixActions/MatrixActions.test.tsx
  webapp/src/components/common/Matrix/components/MatrixActions/index.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/MultiRowFilter.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/RowFilter.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/__tests__/hourIndexing.test.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/hooks/__tests__/useFilteredData.test.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/hooks/useFilteredData.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/hooks/useTemporalData.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/index.tsx
  webapp/src/components/common/Matrix/components/MatrixFilter/types.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/utils/__tests__/dateInfo.test.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/utils/__tests__/filterCombination.test.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/utils/dateUtils.ts
  webapp/src/components/common/Matrix/components/MatrixFilter/utils/index.ts
  webapp/src/components/common/Matrix/components/MatrixGrid/index.tsx
  webapp/src/components/common/Matrix/hooks/useGridCellContent/__tests__/fixtures.ts
  webapp/src/components/common/Matrix/hooks/useGridCellContent/index.ts
  webapp/src/components/common/Matrix/hooks/useGridCellContent/types.ts
  webapp/src/components/common/Matrix/hooks/useMatrixData.ts
  webapp/src/components/common/Matrix/shared/__tests__/fixtures.ts
  webapp/src/components/common/Matrix/shared/__tests__/utils.integration.test.ts
  webapp/src/components/common/Matrix/shared/__tests__/utils.test.ts
  webapp/src/components/common/Matrix/shared/types.ts
  webapp/src/components/common/Matrix/shared/utils.ts
  webapp/src/utils/date/dateUtils.ts
  webapp/src/utils/date/matrixDateUtils.ts
Labels: size/XXL

#2602 refactor(ui-commons): update NewSelectFE and replace deprecated SelectFE with it
  webapp/public/locales/fr/main.json
  webapp/src/components/App/Settings/General.tsx
  webapp/src/components/App/Singlestudy/HomeView/InformationView/CreateVariantDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdequacyPatch/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/General/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Configuration/Optimization/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/ManagementOptions/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Properties/Fields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableConfig/RenewableForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/StorageConfig/StorageForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalConfig/ThermalForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/AddDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/AddConstraintTermDialog/AddConstraintTermForm/OptionsList.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/BindingConstraints/BindingConstView/ConstraintFields.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkConfig/LinkForm.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/UpdateDistrictDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/UpdateLayerDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Results/ResultDetails/components/ResultFilters.tsx
  webapp/src/components/App/Singlestudy/explore/TableModeList/dialogs/TableTemplateFormDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Candidates/CreateCandidateDialog.tsx
  webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
  webapp/src/components/App/Studies/CreateStudyDialog.tsx
  webapp/src/components/App/Tasks/JobTableView.tsx
  webapp/src/components/App/shared/studies/dialogs/CopyStudyDialog.tsx
  webapp/src/components/App/shared/studies/dialogs/UpdateStudyDialog.tsx
  webapp/src/components/App/shared/studies/dialogs/UpgradeStudyDialog.tsx
  webapp/src/components/common/fieldEditors/BooleanFE.tsx
  webapp/src/components/common/fieldEditors/CheckboxesTagsFE.tsx
  webapp/src/components/common/fieldEditors/ListFE/index.tsx
  webapp/src/components/common/fieldEditors/NewSelectFE.tsx
  webapp/src/components/common/fieldEditors/SelectFE.tsx
  webapp/src/components/common/fieldEditors/StringFE.tsx
  webapp/src/hoc/reactHookFormSupport.tsx
  webapp/src/theme/components.ts
Labels: front-end, size/XL

#2608 perf(cluster): optimize a bit the update methods
  antarest/study/storage/variantstudy/model/command/update_renewables_clusters.py
  antarest/study/storage/variantstudy/model/command/update_st_storages.py
  antarest/study/storage/variantstudy/model/command/update_thermal_clusters.py
Labels: size/M

#2609 perf(commands): re-use the cache more often
  antarest/core/interfaces/cache.py
  antarest/study/service.py
  antarest/study/storage/variantstudy/model/command/common.py
  antarest/study/storage/variantstudy/model/command/create_area.py
  antarest/study/storage/variantstudy/model/command/create_district.py
  antarest/study/storage/variantstudy/model/command/create_user_resource.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/create_xpansion_configuration.py
  antarest/study/storage/variantstudy/model/command/generate_thermal_cluster_timeseries.py
  antarest/study/storage/variantstudy/model/command/icommand.py
  antarest/study/storage/variantstudy/model/command/remove_area.py
  antarest/study/storage/variantstudy/model/command/remove_district.py
  antarest/study/storage/variantstudy/model/command/remove_user_resource.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_configuration.py
  antarest/study/storage/variantstudy/model/command/remove_xpansion_resource.py
  antarest/study/storage/variantstudy/model/command/replace_matrix.py
  antarest/study/storage/variantstudy/model/command/replace_xpansion_candidate.py
  antarest/study/storage/variantstudy/model/command/update_area_ui.py
  antarest/study/storage/variantstudy/model/command/update_areas_properties.py
  antarest/study/storage/variantstudy/model/command/update_comments.py
  antarest/study/storage/variantstudy/model/command/update_config.py
  antarest/study/storage/variantstudy/model/command/update_district.py
  antarest/study/storage/variantstudy/model/command/update_hydro_management.py
  antarest/study/storage/variantstudy/model/command/update_inflow_structure.py
  antarest/study/storage/variantstudy/model/command/update_playlist.py
  antarest/study/storage/variantstudy/model/command/update_raw_file.py
  antarest/study/storage/variantstudy/model/command/update_scenario_builder.py
  antarest/study/storage/variantstudy/model/command/update_xpansion_settings.py
  antarest/study/storage/variantstudy/model/command/xpansion_common.py
  antarest/study/storage/variantstudy/model/model.py
  antarest/study/storage/variantstudy/snapshot_generator.py
  antarest/study/storage/variantstudy/variant_command_generator.py
  tests/study/storage/variantstudy/test_snapshot_generator.py
  tests/variantstudy/model/test_variant_model.py
Labels: size/L

#2617 fix(alembic): fix migration syntax for postgresql
  alembic/versions/fa59340767b0_make_all_managed_studies_folder_path_.py
Labels: size/XS

#2620 fix(sts-matrix): restore deprecated enpoint as a security net
  antarest/study/business/areas/st_storage_management.py
  antarest/study/web/study_data_blueprint.py
  tests/integration/study_data_blueprint/test_st_storage.py
Labels: size/L

#2627 fix(tests): remove inter-test dependency
  tests/launcher/test_local_launcher.py
Labels: size/S
